#+BEGIN_COMMENT
.. title: I Miss Her
.. slug: I-miss-her
.. date: 2019-09-06
#+BEGIN_COMMENT

I must have written this in the fall of 2006. Caitlin, my first
Seeing Eye dog, died on July 10, 2006. Elwood did not come into my
life until November 27th. I always remember Caitlin, my chocolate
Lab, on her birthday, September 6, 1992. Thinking about her still
brings tears to my eyes and a lump in my throat.

** I miss her

#+begin_verse
In the daily tasks,
in the ordinary doing of things,
I miss her.
25minutes to an appointment--
I will take her out. There is time for that.
And then, I miss her.
I will sit  in my chair. She will come to be petted, to ask for a biscuit.
And then, I miss her.
I lay down in bed at night and listen for her breathing by the foot of the bed.
And then, I miss her.
I awake in the morning and check the time. I will dress and take her out.
And then, I miss her.
Her water bowl is no longer on the floor under the dishwasher door when I load and unload.
And then, I miss her.
#+end_verse
