
	
 (
 (nil . (
        (org-static-blog-publish-url . "https://rillonline.github.io/")
        (org-static-blog-publish-title . "Rill Online")
        (org-static-blog-publish-directory . "~/blog/")
        (org-static-blog-drafts-directory . "~/blog/drafts/")
        (org-static-blog-index-file . "index.html")
        (org-static-blog-index-length . 1)
        (org-static-blog-archive-file . "archive.html")
        (org-static-blog-tags-file . "tags.html")
        (org-static-blog-enable-tags . t)
        (org-static-blog-enable-deprecation-warning . t)
        (org-static-blog-rss-file . "rss.xml")
        (org-static-blog-rss-excluded-tag . nil)
        (org-static-blog-no-comments-tag . nil)
        (org-static-blog-rss-extra . "Built with emacs, org-mode and org-static-blog.")
        (org-static-blog-rss-max-entries . 100)
        (org-static-blog-enable-tag-rss . nil)
        (org-static-blog-page-header . "")
        (org-static-blog-page-preamble . "<div><h1>You are reading Rill Online.</h1></div>")
        (org-static-blog-page-postamble . "<div id=\"postamble\" class=\"status\"><p class=\"postamble-text\">Copyright © by Rill. This work is licensed under a <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.</p></div>")
        (org-static-blog-post-preamble-text . "")
        (org-static-blog-post-postamble-text . "Thanks for reading.")
        (org-static-blog-post-comments . "")
        (org-static-blog-langcode . "en")
        (org-static-blog-use-preview . nil)
        (org-static-blog-no-post-tag . "dontpost")
        (org-static-blog-index-front-matter . "<h2>Hey there 👋</h2>"))
 ))
	    )
