
title: "Rill Woolnough"
tagline: ""
description: "Follow <a href=\"https://micro.blog/Rill\">@Rill on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/Rill\">@Rill on Micro.blog</a>."
baseurl: ""
url: "https://Rill.micro.blog"
markdown: "kramdown"
username: "Rill"
microblog_user: "Rill"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Rill Woolnough"
name: "Rill Woolnough"
gravatar_hash: "f33255562ca0efb0a0de15eff4616a2e"
avatar: "https://micro.blog/Rill/avatar.jpg"
full_name: "Rill Woolnough"
bio: ""
twitter_username: ""
github_username: "rillonline"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"
site_id: "3589"
gems: ["jekyll-paginate"]
itunes_description: "I am a guide dog user who enjoys telling stories. Some are true and some are not."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Rill Woolnough"
itunes_email: ""
podcast: false