# Site settings
titleRillOnline's Publishing Blog:
description: "Companion blog to RillOnline." 
url: "http://rillonline.github.io"
tagline ":My writing lives here". 

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
