#Site settings
name: Rill Online
title: My writing site.
tagline: All my writing lives here.
baseurl: ''
url: "http://rillonline.github.io/"

# Build settings
markdown: kramdown
kramdown:
#    auto_ids: true
paginate: 4
paginate_path: '/page:num/'
permalink: /:title/

# gems
gems: [jekyll-paginate]

# includes
include: ["_drafts"]
include: ["_pages"]

collections:
  dogwriting:
    output: true
    permalink: /:collection/:path/ 
  yogajournal:
    output: true
    permalink: /:collection/:path/


# defaults
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: page
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
