#Site settings
name: Rill Online
title: My writing site.
tagline: All my writing lives here.
baseurl: '' 
url: "http://rillonline.github.io/"

# Build settings
markdown: kramdown
kramdown:
#    auto_ids: true
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /:title/

# gems
gems: [jekyll-paginate]

# includes
include: ["_pages"]
