# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rill Online
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Rill Online's blog and writing repository.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rillonline.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/

# Build settings
markdown: kramdown
markdown_ext: "kd,kramdown,md,mk,markdown"
plugins:
  - jekyll-feed

# excludes
exclude:
   - bits-and-pieces

# additional Setup
paginate:            1
# About/contact
author:
  name:              Rill

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
