baseURL = 'https://rillonline.github.io/'
language.locale = 'en-us'
title = 'Notes to Myself'
theme = 'PaperMod'

[[menus.main]]
name = "About"
url = "/about/"
weight = 10

[[menus.main]]
name = "Star Runner Adventures"
url = "/adventures/"
weight = 20