** MEDITATION ON PSALM 22, MOSTLY
:PROPERTIES:
:CUSTOM_ID: meditation-on-psalm-22-mostly
:END:
** A GOOD FRIDAY Poem
:PROPERTIES:
:CUSTOM_ID: a-good-friday-poem
:END:
*** Good Friday, 2002
:PROPERTIES:
:CUSTOM_ID: good-friday-2002
:END:
Shadows--\\
The emptiness where no light penetrates.\\
Darkness--\\
It covers the face of the earth at Jesus' death.\\
Fearsome--\\
Forsaken by God and all humanity.

Hunted down--\\
The fearsome lion, the goring bull, the hounds of hell,\\
Ring the crucified.\\
Fingers--\\
Point.\\
Tongues--\\
Mock.\\
Stalkers--\\
Isolate their prey.

The body--\\
Vitality dribbles away like winter snow in spring.\\
Air--\\
One's own body smothers God-breathed-life.

The earth--\\
Covered its face with darkness.\\
The sun--\\
Hid itself behind shadows.\\
The vision--\\
Too terrible to see.

Jesus--\\
By humanity despised and rejected.\\
Jesus--\\
By God forsaken.\\
Jesus--\\
Utterly human.\\
Utterly divine.\\
Utterly alone.\\
Deus Absconditus.

Noise--\\
A prison door clanging shut?\\
A coffin lid closing?\\
A stone rolled against the opening of a newly hewn burial cave?\\
No! A mystery--\\
The stone rolled away.\\
The tomb empty.\\
Jesus--\\
Alive! Raised from the dead!

--------------

[[file:projects.html][Return to Projects Page]]

ABOUT THE AUTHOR

Pastor Merrill Louise is a podcaster, writer and spiritual guide. I
value the vulnerable, the poor and the poor in spirit. My podcasts are
for people who are actively seeking a connection with God or who have a
vague sense something is missing from their lives. Merrill Louise also
writes poetry and a personal blog. For more information, visit
http://www.YourRealLifeSpiritualGuide.com/

This work is licensed under a Creative Commons Attribution-ShareAlike
2.5 License.
