* ACT 1

1.	OPENING IMAGE (0 TO 1%): A “before” snapshot of your hero and their world. 

2.	THEME STATED (5%): A statement made by a character (typically not the hero) that hints at what the hero’s arc will be (that is, what the hero must learn/discover before the end of the book). Also referred to as a life lesson. 

	3.	SETUP (1% TO 10%): An exploration of the hero’s status quo life and all its flaws, where we learn what the hero’s life looks like before its epic transformation. Here we also introduce other supporting characters and the hero’s primary goal. But most important, we show the hero’s reluctance to change (aka learn the theme) while also hinting at the stakes at risk should the hero not change. 

	4.	CATALYST (10%): An inciting incident (or life-changing event) that happens to the hero, which will catapult them into a new world or new way of thinking. An action beat that should be big enough to prevent the hero from being able to return to their status quo Setup world. 

	5.	DEBATE (10% TO 20%): A reaction sequence in which the hero debates what they will do next. It’s usually presented in the form of a question (such as “Should I go?”). The purpose of this beat is to show the hero’s reluctance to change. 

ACT 2

	1.	BREAK INTO 2 (20%): The moment the hero decides to accept the call to action, leave their comfort zone, try something new, or venture into a new world or new way of thinking. It’s a decisive action beat that separates the status quo world of Act 1 from the new “upside-down” world of Act 2. 

	2.	B STORY (22%): The introduction of a new character or characters who will ultimately serve to help the hero learn the theme. Also referred to as a helper character, this can be a love interest, a nemesis, a mentor, a family member, or a friend. 

	3.	FUN AND GAMES (20% TO 50%): This is where we see the hero in their new world. They’re either loving it or hating it. Succeeding or floundering. Also called the promise of the premise, this section represents the “hook” of the story (why the reader picked up the novel in the first place). 

	4.	MIDPOINT (50%): Literally the middle of the novel, where the Fun and Games culminates in either a false victory (the hero has thus far been succeeding) or a false defeat (the hero has thus far been floundering). Something should happen here to raise the stakes and push the hero toward real change. 

	5.	BAD GUYS CLOSE IN (50% TO 75%): If the Midpoint was a false victory, this section will be a downward path where things get progressively worse for the hero. If the Midpoint was a false defeat, this section will be an upward path where things seem to get progressively 26 better for the hero. But regardless of path, the hero’s deep-rooted flaws (or internal bad guys) are closing in. 

	6.	ALL IS LOST (75%): The lowest point of the novel. An action beat where something happens to the hero that, combined with the internal bad guys, pushes the hero to rock bottom. 

	7.	DARK NIGHT OF THE SOUL (75% TO 80%): A reaction beat where the hero takes time to process everything that’s happened thus far. The hero should be worse off than at the start of the novel. The darkest hour—just before the dawn—is the moment right before the hero figures out the solution to their big problem and learns the theme or life lesson. 

ACT 3

	1.	BREAK INTO 3 (80%): The “aha!” moment. The hero realizes what they must do to not only fix all of the problems created in Act 2, but more important, fix themselves. The arc is nearly complete. 

	2.	FINALE (80% TO 99%): The hero proves they have truly learned the theme and enacts the plan they came up with in the Break Into 3. Bad guys are destroyed, flaws are conquered, lovers are reunited. Not only is the hero’s world saved, but it’s a better place than it was before. 

	3.	FINAL IMAGE (99% TO 100%): A mirror to the Opening Image, this is the “after” snapshot of who the hero is after going through this epic and satisfying transformation. 

MIDDLE GRADE NOVELS (READERS 8 TO 12)

WORD COUNT

ESTIMATED MANUSCRIPT PAGE COUNT*

Publishing Industry Standard

40,000 to 60,000

160 to 240

Holes by Louis Sachar

47,079

188

Wonder by R. J. Palacio

73,053

292

Harry Potter and the Sorcerer’s Stone

96,000

384

YOUNG ADULT NOVELS (READERS 12 TO 17)

WORD COUNT

ESTIMATED MANUSCRIPT PAGE COUNT

Publishing Industry Standard

60,000 to 90,000

240 to 360

The Giver by Lois Lowry

43,617

174

Lord of the Flies by William Golding

59,900

239

The Hunger Games by Suzanne Collins

99,750

399

GENERAL FICTION NOVELS

(READERS 18 AND UP)

WORD COUNT

ESTIMATED MANUSCRIPT PAGE COUNT

Publishing Industry Standard

70,000 to 100,000

280 to 400

Bridget Jones’s Diary by Helen Fielding

86,400

346

The Da Vinci Code by Dan Brown

138,952

556

Gone Girl by Gillian Flynn

145,719

582

Remember, however, that novels can vary greatly in length, so it’s important that you use these examples only as guidelines. Be flexible. Your novel’s length will change as you write and revise, but it’s always helpful to have a rough estimated word count or page count in mind when you start so you can calculate where each beat goes.

