** Big Mean Machine
:PROPERTIES:
:CUSTOM_ID: big-mean-machine
:END:
Who found you\\
in the vacant lot\\
behind my grandmother's Victorian farmhouse\\
in Brooklyn, New York?\\
Who abandoned you?\\
Who dismembered you?\\
Who stripped you\\
of your fenders\\
and handle grips?

I know it was my father\\
who covered your red paint with dark green.\\
What sort of a color\\
is that for a big mean machine\\
like you?

How emasculated\\
you must have felt\\
when he attached training wheels\\
to your 22-inch frame\\
to teach his girl child\\
how to ride.

You taught me well, big mean machine:\\
how to balance,\\
how to slow\\
by hovering feet on pedals\\
just before the point\\
where brake bit into chain.\\
how to brake,\\
hard and fast,\\
feet braced back on pedals,\\
your tires rubbing against macadam,\\
my feet sliding\\
across gravel and dirt.

You taught me\\
to lift my right leg\\
over your lean back,\\
to clear not one\\
but two bars.\\
No sissy bike, you.

It was grasp your sleek smooth handlebars,\\
kick away the stand,\\
vault over bars and seat\\
and ride, ride, ride.

Each of us were mean machines once.\\
Whatever became of you?\\
I did not mourn your passing then.\\
Only now I wonder:\\
What would you have been like\\
red,\\
fendered,\\
handle gripped?

And what would I have been like\\
if I had never forgotten\\
what you taught me, big mean machine:\\
Grasp.\\
Kick.\\
Vault.\\
Ride.\\
Ride.\\
Ride.

--------------

[[file:projects.html][Return to Projects Page]]
