* Novel Summary

The War of Consolidation continues. Documenting the war crimes of the
People of the Rainbow Sky is an important part of the Tigerfoo offense in
the ongoing war among several races within the eastern arm of the
galaxy. Detective Ronnie Camberwell, currently living among the Tigerfoo,
is anxious to help the Tigerfoo because the People of the Rainbow Sky
manipulated her friend and some time lover Captain Star Runner with near
fatal results.

Ronnie has just completed the introductory course so that she might join
the War Crimes Investigation Unit. Without any explanation, she is
informed she will not receive an assignment in The War Crimes
Investigation Unit. Instead, she is to meet with her new team leader
immediately.

Ronnie is upset. What could she have done wrong? She had completed all
her assignments successfully. In fact, she is in the top three to five
in the class. Her only shortcomings are her unfamiliarity with all the
nuances of Tigerfoo culture and its history. Or is it that the Tigerfoo do
not want a human involved in their war crime investigations? The Tigerfoo
think of themselves as being a very moral people.

Ronnie enters a room where a very elderly Tigerfoo stands. He leans on an
ornate staff. Ronnie still does not know a lot about Tigerfoo culture,
but she does know a staff like this one connotes wisdom and a position
of respect.

The elderly man addresses her as "Apprentice' and identifies himself
as"Master Awk". He tells her she has been assigned to him and they are
going to the Magic Lands. They are a team of two.

Ronnie storms from the room, convinced there has been a huge mistake.
However, the Director is gone for the day. Her instructors tell her they
cannot help her, that the director's decision is final. When she returns
to her room, she learns she must remove her possessions by midday and
she will have no access to the room after that time. She has no other
option but to return to the room where she left Master Awk. He is still
waiting for her. Reluctantly, she agrees to join his team. It annoys her
that everyone else already knew she had no other options. She declines
invitations by her classmates to accompany them them for a final
celebratory meal and spends the evening packing. Their spaceship leaves
in the wee hours of the morning. Without a good-bye to anyone, Ronnie
leaves the school.

on their space journey to The Magic Lands, Master Awk advises Ronnie
that magic is real in discrete parts of the galaxy. The Magic Lands are
a part of Tigerfoo Land. She has been reassigned because she both has an
aptitude for magic (hence her apprentice status) and investigation
skills that will determine if a spy is leaking information to the People
of the Rainbow Sky concerning a very important project. The Grand Master
requested Master Awk's help. Both wizzards understand the magic but do
not know how to investigate the traitor. The wizzards are creating a
great shift in mass and the expenditure of energy is huge. They are
supporting a a region of space the People of the Rainbow Sky devastated.
Master Awk and Ronnie will become a part of the project. In addition,
the project has run into a snag. It is expending wizzard energy to a
debilitating degree. Master Awk has been called in to find out why.
Ronnie needs to be a real apprentice for their cover to be effective.

Although Ronnie is upset that she was not consulted in her change of
status to Wizzard Apprentice and her assignment to The Magic Lands, she
is excited to be part of an important investigation.

The captain of the spaceship waylays Ronnie and advises her not to go to
The Magic Lands. He says he is afraid even to bring his spacecraft out
of hyperspace there, but orders are orders. Ronnie asks him why. He says
that people who go into The Magi c Lands never return again.

Master Awk says Ronnie must always remember the three laws of magic if
she is to survive this mission:

1. Respect the free will of others.
2. There is always a cost to the wizzard for doing magic.
3. The wizzard is responsible for consequences of all the magic he or
   she performs.

Master Awk provides the axiom "It is far easier to perform magic than to
unperform it later." This saying will come back to haunt Ronnie later.

The project has the wizzards design spells to break down moons and
asteroids so that they are converted into both material and energy which
is then transported via hyperspace to the devastated region of space
known as The Green Belt. When the infrastructure is rebuilt, spacecraft
can bring the needed seeds and plants so that this area can re-establish
itself as the best source of fruits and vegetables in the eastern arm.
Through a series of investigations, Ronnie learns The project leader is
being paid for intelligence about the project by the People of the
Rainbow Sky. His bounty is increased if he can also disrupt the
project.The scheme Roop puts in in place denudes their region of space
of valuable material resources

If the project continues on this path, all the wizzards connected with
it are, in effect, will die slowly as their life energy is drained away
from them. The People of the Rainbow Sky are playing on Roop's averous
and greed for power and his antipathy toward the Grand Master who has
criticized Roop's handling of projects before. Roop's heir hurry to
complete the task has caused the problems Master Awk was summoned to
correct.

When Master Awk receives Ronnie's report, he is appalled. He plans to
take his finds to the Grand Master of Wizzards for plan how to arrest
Roop and get the project back on track..

Along the way, Ronnie becomes enamored with the leader of the project,
Roop. She is confused by her attraction.This is the first man Ronnie has
ever been attracted to. To make the spells work faster, the project is
infusing them with their own life energy. Ronnie sees the ill-effects
this is having on Roop and she wants to save him.

In a confrontation with Roop, he reveals he knows about her
investigations and Master Awk's plan to turn him and his partner
wizzards into the Tribunal. Panicked that her own life is now at stake
and that Roop's health is so precarious, Ronnie uses her own magic to
disrupt the process. Roop and several of the other wizzards die because
their lives are so entwined with the transfer spells that disrupting
them disrupts their lives.

Ronnie is arrested by the Tribunal for murder and for not consulting her
master wizzard before acting. She is, after all, only an apprentice. Her
spell did not take into account all the needed safeguards. That is why
the wizzards died.

A tribunal of wizzards is called. Ronnie is placed on trial. The three
laws of magic are applied to her situation. The tribunal states Ronnie
has the potential to be an incredibly skillful wizzard. Because her
gifts will be needed for the Magic Lands to complete their work, she is
assigned to the energy project under the supervision of a local wizzard
until such time as the Tribunal believes she has paid her debt. Ronnie's
personal freedoms are greatly restricted including her freedom to
travel. She may not leave the Magic Lands and she may not associate with
anyone until her master aproves. Ronnie is, in effect, under house
arrest at the project. .

As the story ends, Master Awk bids her farewell and terminates her
connection to the Tigerfoo military. She is given a dishonorable
discharge pending the completion of her sentence in the Magic Lands.

* Questions for Lesson 1
  :PROPERTIES:
  :CUSTOM_ID: questions-for-lesson-1
  :END:

1. What is the issue, the human problem being studied, solved, or
   celebrated? The issue being studied in this novel is: With great
   power comes great responsibility.
2. Have you introduced your main character? Who is he/she? Detective
   Ronnie Camberwell is the central character. She is a capable
   investigator who finds herself the only human in an alien culture
   very far from home.
3. Do you set up your central question and does that central question
   set up the crises and climax? Yes.
4. Do you have subplots? No.
5. How will you use your archetypes to achieve your dramatic function?

   - I will use Detective Ronnie Camberwell to be my flawed heroine. She
     will come to acknowledge her wizard powers.
   - I will use the Director of the War Crimes Investigation School as
     my herald. He tells Ronnie she has been assigned to Grand Master
     Awke's team.
   - Grand Master Awke, Emeritus will be Ronnie's mentor. He will try to
     instill in her responsible wizardry. Only after his accidental
     death will Ronnie come to appreciate his teaching, mourn his loss
     and begin to come to terms with her power.
   - Tripp will be Ronnie's ally.
   - Senior Master Gaunt, Tripp's mentor, will be a kind of shift shaper
     though there is nothing cynister in this. He takes on the roles of
     threshold guardian and later ally at the Tribunal.Ronnie is quick
     to identify him as a potential Villon. Gaunt will argue Awke did
     not impress on Ronnie her potential for doing harm. His view will
     forcefully persuade the other wizards at the Tribunal.
   - Grand Mistress Vesha is a threshold guardian whose responsibility
     it is to ensure proper oversight of all wizards and that wizard
     status is not given to anyone undeserving. She will become Ronnie's
     mentor after Grand Master Awke's death. Her remarks to Ronnie on
     power and responsibility will sting.
   - The spaceship captain is a threshold guardian. He will try to
     dissuade Ronnie from entering The Magic Lands. He says once Ronnie
     goes there, she will not be able to return. He turns out to be
     right, at least in the short term.

6. We all have a set of talents. We often characterize these as
   God-given. We have no control over them. For Ronnie, one of these
   latent talents is the ability to perform magic. Circumstances find
   Ronnie involved with an alien culture which is involved in a space
   war between ancient combatents. With no family or friends nearby, she
   must find her way in these alien worlds. This makes her vulnerable to
   error and to transgressing local mores.

   Ronnie's story is compared and contrasted with that of the dedication
   of the wizzards of the Magic Lands to help others devastated by the
   space war.

7. Roop has cast a spell on Ronnie to make her attracted to him while
   her natural attraction is to women. He has done this for his own
   ends. He does not want her to question anything he does and he wants
   her to do everything he asks. Roop is secretly sending intelligence
   to The People of the Rainbow Sky about the project. He hopes for an
   opportunity to leave the Magic Lands and he believes the People of
   the Rainbow Sky will give him that opportunity. Roop, for his part,
   is beholden to the Most Master Wizzard for an earlier transgression.
   After Roop's death, the power of the spell on Ronnie dissipates and
   she is able to reconstruct Roop's crime for the Tribunal. This allows
   them to set a time limit on her sentence. Otherwise, it would be for
   life.

* Characters and Their Archetypes
  :PROPERTIES:
  :CUSTOM_ID: characters-and-their-archetypes
  :END:

- Ronnie: Ronnie is the hero though she does not do the right thing in
  the end.
- Master Awk is Ronnie's mentor. He fails in the end because he gets
  swept up with the importance of the project. Ferreting out the spy,
  his mandate, is deprecated to the magic itself. Master Awk has spent
  too much time away from places where magic works.
- The herald in this story is represented by several characters and
  situations. The Grand Master reaches out to Master Awk; the Tigerfu
  testing identifies Ronnie's aptitude for magic; Ronnie investigatory
  experience recommends her; The head of the War Crimes Unit reassigns
  Ronnie to Master Awk.
- Senior Master Gaunt (and he is) is skeptical of Ronnie's usefulness to
  the project and will block and come upon Ronnie unexpectedly during
  Ronnie's investigations. Ronnie suspects Gaunt of misdoing. In fact,
  Gaunt is doing his own investigations because he thinks something is
  wrong but he can't prove it.
- Tripp is a young wizzard, just finished her apprenticeship. She is
  attracted to Ronnie, gives her practical advice and shares living
  quarters with Ronnie. If Ronnie was not under Roop's spell, she would
  be mutually attracted to Tripp.
- Tripp and Gaunt also function as allies. They encourage Ronnie in her
  magic learning and provide Ronnie with important information in her
  investigations.eir testimony help to mitigate Ronnie's sentence.
- The People of the Rainbow Sky are the villains of the piece. Roop is a
  pawn in their plan of consolidation.
- Roop is the shape-shifter. He is a very talented wizzard has led his
  failings rule his life.
- 

  - The spaceship captain is a threshold guardian, trying to keep from
    :: taking Grand Master Awk and Ronnie to The Magic Lands and warning
    Ronnie about them during the trip through hyperspace.

- Captain Star Runner does not physically appear in this story. Star
  Runner is an fuchsia-colored UN gendered Pantheran who pilots
  spaceships. Star functions as an ally and mentor in Ronnie's mind.

* Questions for Lesson 2
  :PROPERTIES:
  :CUSTOM_ID: questions-for-lesson-2
  :END:

1. Ronnie's external problem as she begins her journey is the War of
   Consolidation. Once a mighty empire, the People of the Rainbow Sky
   turned their attention inward and their conquests gained
   independence. Now The People of the Rain Sky are mercilessly
   reconquering territory.

   Ronnie's internal problem is that she is leaving behind the War
   Crimes Training Program which would have been a form of detective
   work she understands with physical evidence and a crime scene. She
   has been unilaterally reassigned to apprentice as a magician which is
   hard to swallow. She has never considered magic to be real.

2. Ronnie is human. Her ordinary world consists of humans going about
   their every day tasks. Gradually, she has been introduced to aliens,
   especially Captain Star Runner, a Pantheran and an independent
   trader. Working with the Pantheran, Ronnie ended up living among the
   Tigerfu. Making her own way, she enrolled in the War Crimes
   Investigation branch of the Tigerfu military.
3. We see Ronnie in the ordinary world of the War Crimes Investigation
   School and aboard the spaceship with Master Awk on her way to The
   Magic Lands.
4. Ronnie's fantasy is the perfect lover who is always there for her,
   who is strong, kind, always understanding, sexually available and and
   attractive.. Ronnie herself is unable to commit herself to a
   monogamous relationship. She has had one human relationship fail
   because of her lack of commitment and her unwillingness to set aside
   all other relationships. Her relationship with Captain Star Runner is
   on again, off again. It does not survive long separations. She is
   jealous of any relationship Captain Star Runner has with anyone else.

   Ronnie craves her privacy in her personal affairs and total
   independence in her professional Although she would not admit it,
   Ronnie believes she is never good enough in her personal and
   professional lives. She is deeply wounded by the knowledge that she
   is not Troy Camberwell's daughter and does not know how to accept his
   generosity of continuing to be her father after the infidelity of her
   mother came to light. She knows she has disappointed Simon and Hilda
   Parge who provided a home for her while her father ran the police
   department in Ptolemy City. They disapproved of her relationship with
   Captain Star Runner and her ultimate decision to move away.

5. Ronnie's downfall will be believing that Roop loves her. She will try
   to save him from the diliterious effects of the project by acting
   alone to shut down the project.
6. Ronnie's universal human need is unconditional love.
7. Ronnie will believe Roop's attention toward her is real love. She
   will ignore Tripp's advances.
8. Ronnie's call to adventure originates with the Grand Master, but is
   delivered in two parts: by the Director of the War Crimes
   Investigations Branch and by Master Awk.

* Questions for Lesson 3
  :PROPERTIES:
  :CUSTOM_ID: questions-for-lesson-3
  :END:

** Refusing the Call
   :PROPERTIES:
   :CUSTOM_ID: refusing-the-call
   :END:

1. What are your characters afraid of? What are false fears or paranoia?
   What are real fears?

   - Apprentice Tripp

     - failing to learn magic
     - always being homesick
     - being alone

     These are all real fears.

   - Grand Master Awk, Emeritus

     #+BEGIN_QUOTE

       - His magic skills are not up to snuff. This includes both not

       being up-to-date with magic theory and practice as well as
       forgetfulness.

       #+BEGIN_{QUOTE}

       - letting down The Grand Master
       - being unable to train an alien apprentice
       - He will be unable to figure out what is going wrong at the
         project.
       - The People of the Rainbow Sky are involved.
       - old jealousies. Are jealousies real or imagined?
     #+END_QUOTE

     #+END_{QUOTE}

   - Master Gaunt

     - Losing Apprentice Tripp's devotion to him as she becomes more and
       more besotted with Apprentice Ronnie
     - his position at the project when Master Awk comes on board.
     - the war, The People of the Rainbow Sky, in short, anyone and
       anything that will change his current position.

     All these fears are about to spill over into paranoia and threaten
     his basic willingness to be kind, to respect others, including
     aliens and to be as helpful as possible to those learning the
     craft.

   - Senior Master Roop
   - Ronnie

     - Being the only human in a place where she has no Tigerfu friends.
     - BEING caught investigating.
     - Dying.
     - Not being able to leave The Magic Lands.
     - Not being able to see her friends ever again.
     - Being caught by The People of the Rainbow Sky or their allies.

   - The Grand Master

     Having The Project fail on her watch.

     - Old scores being settled.
     - Losing the Grand Master position.
     - Losing face.

   - The Spaceship Captain

     #+BEGIN_QUOTE

       - Being unable to leave The Magic Lands under his own power.
       - Having magic practiced on his ship while in transit. (This is

       impossible since magic can only be practiced inside The Magic
       Lands. While in port, courtesy prohibits the practice of magic on
       or in close proximity to his ship. Nevertheless, the captain is
       afraid.) - Being attacked by The People of the Rainbow Sky or
       their allies.
     #+END_QUOTE

   - Being hit by friendly fire.
   - What are the consequences of the refusal?

2. If you refused Calls to Adventure how would your life be different?

   I think it is impossible to refuse all calls to adventure. We are
   born. We go to school. We make friends. We Have romances and maybe
   marriages, we have children, have jobs, move to new places; we get
   sick and all of us die. These are all calls to adventure.

   There are, of course, many calls to adventure we evaluate. Some we
   accept. Others we reject. We break up with that person. We accept
   that marriage proposal. We take one job while we decline another. We
   move or we stay put.

3. Have you accepted Calls to Adventure that you wish you would have
   refused? Certainly.

** Mentor
   :PROPERTIES:
   :CUSTOM_ID: mentor
   :END:

1. This story has a full-blown mentor, Grand Master Awk, Emeritus.
2. Does not apply.
3. Ronnie has a general sort of ethics. She comes from Ptolemy City in
   the Pharaoh Star System. This city started out as a haven for space
   pirates. Later it became a place for powerful humans to operate
   outside the law. As a result, Ronnie does not consider certain kinds
   of behavior unethical or illegal. However, the powerful soon learned
   that they needed to rule of law to apply to their work force. These
   people are protected by labor laws and constrained in other ways.
   Nevertheless, it is important to remember that assassination, for
   example, is legal where Ronnie comes from.

   Ronnie's first job was as a police officer. Later she became a
   private investigator and had a contract with the Alliance of Free
   Planets. Working for an intelligence agency meant she had a certain
   latitude in her operation. Later Ronnie worked in several alien
   cultures and managed to understand their ethical systems. Now she
   must understand those of The Magic Lands.

4. Ronnie has a well-developed conscience. This manifests itself most
   clearly concerning personal loyalty. Ronnie is flexible with right
   and wrong. She values her autonomy and despises exploitation of the
   weak, theft and betrayal.
5. Ronnie is open to mentors. As this story begins, she has just
   completed The War Crimes Investigation course. She had a mentor when
   she was training to be a police officer. She is, however, at odds
   with Grand Master Awk, Emeritus because she does not like him, trust
   him or like her assignment.

** First Threshold
   :PROPERTIES:
   :CUSTOM_ID: first-threshold
   :END:

The audience knows that we've gone from one world to the next because we
have traveled in a spaceship through hyperspace to get there. The
ordinary world looks futuristic. The next world looks medieval at the
space port and non-industrial beyond it. Ronnie (and presumably the
audience) is disoriented. She expected The Magic Lands to appear even
more futuristic. Ronnie continues to be unwilling. She does her
homework, determined not to fail, but she continues to be uneasy about
the whole venture. Her reasons are twofold:

1. She still doesn't like the idea of magic.
2. Yes. The threshold guardians in the form of the captain, the setting
   and the locals at the River Walk raise questions which makes it
   difficult for Ronnie to be totally committed to her role. Her heart
   is not in it. She keeps thinking she is missing something important.
3. Ronnie deals with the threshold guardians by listening and observing.
   She asks questions and tries to draw conclusions while staying open
   to more information.

** Questions for Lesson Four
   :PROPERTIES:
   :CUSTOM_ID: questions-for-lesson-four
   :END:

Tests Allies Enemies

#+BEGIN_QUOTE
  Describe your special world in one solid paragraph (physical and
  mental welcomed.) Why do Heroes go through a series of tests? Why not
  go right through to the main event? Could you increase the contrast
  between Ordinary and Special World? How? What are the ways your Hero
  is tested? (There are no right ways; this is according to your story.)
  Is your Hero alone or with a group? Yes/No? Are you constructing an
  ensemble piece? Yes/No? (Elaborate upon this if you wish to flesh out
  the group your hero will be working with, again, this is according to
  your story.) How does your Hero react to the special world?
#+END_QUOTE

Approaching the Innermost Cave

#+BEGIN_QUOTE
  What are the continued tests you are making your characters go
  through? What special preparations are leading to the middle of your
  story / the crisis? Does the conflict build? Do obstacles get more
  difficult? Explain. Does your Hero want to turn back or is he/she
  fully committed? Explain. In what ways is your Hero facing external
  forces while also dealing with inner demons and defenses? Is there an
  actual villain and his cave or an emotional equivalent?
#+END_QUOTE

* Lesson Five Questions
  :PROPERTIES:
  :CUSTOM_ID: lesson-five-questions
  :END:

The Supreme Ordeal

We are at a very, very important point in your story. Go back and ask
the question:

#+BEGIN_QUOTE
  What is your main character's greatest fear? Ronnie's greatest fear is
  being controlled or manipulated by others.
#+END_QUOTE

By answering that question, you should be able to construct your main
crisis---you should be able to construct the scenes/paragraphs of this
step. (That's just a hint.)

1. Just what is your story's supreme ordeal? When Ronnie goes to prevent
   Roop from contacting The People of the Rain Sky, Roop attempts to
   block her interference with magic. Realizing that Roop is starting to
   control her body and her thoughts, Ronnie uses her own magic to
   combat him. The opposing forces of magic overloads the transfer
   controller. It sheds the magic in order to shut down. The ensuing
   magic blast kills Roop, Grand Master Awke who has felt the magic
   overload and has come to find out what is going on, and knocks Ronnie
   unconscious.

- In what ways is your Villain or Villain-energy your Hero's shadow?
  Roop believes Grand MAsters Awke and Vesha are in his way to become
  Grand Master. Unwilling to wait, he has accepted The People of the
  Rainbow Sky's promise to instate him as Grand Master when they conquer
  The MAgic Lands. He is ambitious like Ronnie and impatient with
  bureaucracy.
- Is the villain's power channeled through other characters/archetypes?
  If yes, give an example. Yes. Roop acts as an ally and a mentor to
  Ronnie. As a person of interest to The People of the Rainbow Sky, he
  plans to turn her over to them all the while he is ingraciating
  himself to her.

1. Ronnie faces actual death when she uses magic to stop Roop's magic.
   There are unattended consequences. The Transfer Controller

- Is your story gaining momentum at this point? Yes.

* Lesson Six Questions
  :PROPERTIES:
  :CUSTOM_ID: lesson-six-questions
  :END:

Reward, Road Back, Resurrection Reward ------

1.  The modern version of my campfire scene is Ronnie's hospital
    bedside. Here Ronnie gets to tell Grand Mistress Vesha her story.
    Grand Mistress Vesha fills Ronnie in on what has happened since
    Ronnie passed out. She also advises Ronnie that there will be a
    tribunal concerning her actions. She is charged with causing the
    deaths of Grand Master Awk and Senior Master Roop and exceeding her
    authority to practice magic.
2.  Ronnie learns that she is willing to die to thwart The People of the
    Rainbow Sky. She feels sad on learning Master Awk is dead. She did
    not know how fond she was of the old Tigerfu. She will miss her
    sessions with him. She realizes she was not attracted to Roop but to
    his magical power. She depises his betrayal of the Tigerfu.
3.  Ronnie takes possession of her ability to practice magic. She has
    demonstrated her willingness to help the Tigerfu in the War of
    Consolidation.
4.  The story does not change direction. It moves toward Ronnie
    accepting her role in the war. She is a wizzard.
5.  Ronnie does not yet have all she needs to complete her journey.
6.  There is not a new agenda.
7.  Ronnie now has the tool of knowledge about herself that comes from
    the inside rather than told to her on the outside.
8.  This is not a good time for a love scene.
9.  Ronnie realizes, through self-examination and reviewing what she has
    been told, that she has changed.
10. Ronnie has not yet learned to deal with her inner flaws. She is,
    however, quite chastened.

** Road Back
   :PROPERTIES:
   :CUSTOM_ID: road-back
   :END:

- Will your Hero be ejected or will he/she leave voluntarily from the
  special world? Ronnie will make The MAgic Lands her own.
- Do you feel heroic writing your story? Some.
- ow can you apply your feeling to your characters? This is a story
  about independence and I can make living that way very important to
  Ronnie, Tripp and Roop.
- Is the road back returning to the staring place? A new destination?
  Adjusting to life in the new world? The road back is adjusting to the
  new world.

Act II to Act III Turning Points Here

#+BEGIN_QUOTE
  Are these single moments or a series of moments? Is there an element
  of pursuit or acceleration in these sections? Is there urgency? Ask
  yourself: "Is everything I foreshadowed paid off in the script?" Are
  all of your questions hinted at or answered? Is everything paid off or
  will it be paid off?
#+END_QUOTE

Regarding the Resurrection Step

#+BEGIN_QUOTE
  Are there flaws that have brought your character to where they are?
  What flaws are necessary for your character to continue? What final
  order of death or ordeal does your character go through? What aspect
  of your hero is resurrected? (if at all) Is there a need for physical
  violence at the end of your story?
#+END_QUOTE

Keep Writing Forward

* The Halfway Point
  :PROPERTIES:
  :CUSTOM_ID: the-halfway-point
  :END:

The Writer's Journey confuses me. It makes sense when I am reading it,
but I lose the sense of it when I open this file and try to write. In a
way, it is just a construct and I can easily tell myself I don't need to
focus on it to write a story; however, I selected the course to learn
how to write a better story. As such, it seems important to learn how
this pattern works and how to alter it to my writing needs.

I am having trouble with several aspects of this project:

1. I cannot figure out point of view and narrative sstyle. Mostly, I'm
   seeing this as a movie. Nathan Lowell says he sees his stories as
   movies and just writes down what is happening. I think I have the
   setting figured out by having this movie run, but now how the story
   will be told.
2. I do not have a solid grasp on the plot. This makes writing the later
   scene summaries very hard because I don't know how this story works.
   Perhaps the best thing to do is stop worrying about the course
   questions and write the scene summaries and figure the rest out
   later. On the other hand, the questions have shown me holes and added
   possibilities.
3. I have a number of subplots or plots or whatever they are going.
   Let's see if I can list them here:

   1. Ronnie learns to be a magician.
   2. Ronnie investigates and confirms Grand Master Vesha's suspicion
      that Senior Master Roop is a spy for The People of the Rainbow
      Sky. Ronnie performs magic to stop Roop from doing magic related
      to The People of the Rainbow Sky and the project. Ronnie's magic
      has the unintended consequence of killing Roop. For practicing
      magic beyond her apprenticeship and causing Roop's death, Ronnie
      is put on trial for practicing black magic. In olden times, the
      penalty for such egregious acts was death. In more recent times,
      the death penalty has not been applied. The Tigerfu outside of The
      MAgic Lands disapprove, but the penalty has not been taken off the
      books. Grand Master Awk does not back Ronnie up. However, Tripp
      and Senior Master Gaunt do. Grand Master Vesha rules that Ronnie
      is confined to The Magic Lands. Her reasoning is that Ronnie's
      gift for magic needs to be studied and redirected. Essentially,
      Ronnie is put under house arrest. Senior Master Gaunt will now
      have authority over her.
   3. I haven't sorted out why there is friction between Grand Master
      Vesha and Ronnie, but there is. Grand Master Vesha is not exactly
      a vi villain in this piece, but definitely an antagonist.
   4. Although I think of Grand Master Awk as a kindly old man, he is
      not. He is once powerful wizzard who has lost his touch. His
      short-term memory is failing. He has been called out of retirement
      to help Grand Master Vesha figure out what is wrong at the
      project. (This project needs a name for sure.) He does not stand
      up for Ronnie at her trial. He mixes things up and his testimony
      is filled with inaccuracies which Ronnie cannot refute because its
      her word against his. By doing what she did, Ronnie did not allow
      Grand MAster Awk to solve the problems at the project.
   5. Tripp and Ronnie notice something wrong at the River Walk. Mostly
      the apprentices are kept away from the general populous. Ronnie is
      convinced the wizzards are enslaving the people somehow. She wants
      to get to the bottom of this. How can she do this in this story?
      Perhaps it is just an unresolved piece that can be explored in
      another book or it figures into the trial period somehow.
   6. And there is Tripp's unrequited love for Ronnie. Should this stay
      in the story or should Tripp just be a friend. Should Ronnie be
      attracted to Roop be dropped or should Roop become a female
      magician? I've always thought of Roop as male, but it would be
      easy enough to change that, creating a love triangle. If a love
      triangle, then how do Ronnie and Tripp resolve that after Roop's
      death? Would a spell be necessary to have Ronnie attracted to Roop
      or could that be something Tripp and Ronnie make up later to
      explain why things did not work for them at the beginning? This
      sounds awkward. The less magic the better, I think. An ordinary
      love triangle sounds far more practical.?
   7. Ronnie thinks the story she is being told by the grand masters
      does not add up. What doesn't add up? What are they keeping from
      her? What does she find out? How does this affect what happens
      with Roop and what happens at her trial? This all must hang
      together. What is the secret agenda here?

4. Clearly there are too many subplots, but I think they can be sorted.
   I think I will keep Roop a male. Ronnie is not attracted to him
   because he is male but because she is attracted to the power of his
   magic. Using power wisely is Ronnie's personal test in this story.
5. Neither grand master likes it, but magic is stagnant in The Magic
   Lands. Every magician uses the same spells to achieve the same
   results. They need someone new, someone with news ideas and a new way
   of doing things. Ronnie is that new person. The Tigerfu have many
   gifts, but originality is not one of their strong suits. Ronnie is
   the only example they have of a human being, but the ancient
   literature says their race was extremely creative. When the grand
   masters reached out for a solution, they found Ronnie at the War
   Crimes Investigation School. They were extremely pleased with her
   investigation background and it is an excellent cover for bringing
   her to The Magic Lands. It is also why the initial charges against
   Ronnie are so extreme. They want to keep her. A sense of propriety
   and justice does intervene to make her sentence shorter, but Grand
   Master Vesha wants to keep her forever. Down the road, of course,
   Ronnie will challenge Grand Master Vesha and succeed. But that is
   another story. This also explains the poor conditions on the planet.
   The poor state of magic is reflected in the poor state of the people
   and animals. This is why Grand Master Awk won't tell Ronnie about it.
   He won't admit magic is in trouble in The Magic Lands. His
   presentation of magic to Ronnie is romantic and full of ancient lore.
   This makes Ronnie impatient. She likes facts.

* A New Summary
  :PROPERTIES:
  :CUSTOM_ID: a-new-summary
  :END:

#+BEGIN_QUOTE
  Can I write a summary of this novel in twelve sentences? One sentence
  for a prologue and one sentence for an epilog.
#+END_QUOTE

1.  Prologue: The War of Consolidation continues with The People of the
    Rainbow Sky attempting to reconquer their former colonies and the
    Tigerfu, among others, trying to repulse them.
2.  Ronniea human female, is awaiting her assignment after completing an
    introductory course on War Crimes Investigation for the Tigerfu.
3.  Instead of receiving an assignment, Ronnie is directed to the
    Director's Office where she is told she will be working for Master
    Awk and no other information is available.
4.  Ronnie meets with Master Awk where he tells her he is a wizzard and
    she is his new apprentice as well as she will investigate some
    irregularities in The MAgic Lands.
5.  Ronnie becomes angry and storms out, but quickly discovers she has
    no other options except return to Master Awk.
6.  Ronnie accompanies Master Awk to The MAgic Lands, becoming more
    uneasy at every turn--the sfreighter captain tries to discourage her
    from entering The MAgic Lands, the spaceport appears to be a
    medieval fortress and the city where she meets the Grand Mistress is
    too fairy-like to be believed.
7.  Ronnie and Master Awk take a skyboat to the Musical Mountains,
    meeting Apprentice Tripp and Master Gaunt along the way.
8.  At the Musical Mountains, Ronnie meets Roop, the senior wizzard in
    charge of a energy and material transfer project, and settles in to
    learning her craft and trying to find out if Roop or someone else
    involved with the project is crooked.
9.  Ronnie discovers Roop is working for The People of the Rainbow Sky
    and that he is about to give them information that will disrupt the
    project so she steps in to disrupt Roop's efforts.
10. Ronnie finds herself in Magic City where she learns that she is
    under arrest for the death of Roop and Master Awk and that the
    project has been totally disrupted.
11. At her trial, Ronnie learns her yet uncontrolled abilities to do
    magic caused the disruption in the project which resulted in two
    deaths, but the project disruption has allowed Master Gaunt to
    rebuild it correctly and that her sentence is to stay on in The
    MAgic Lands because the Grand Mistress has determined Ronnie will be
    able to revitalize magic in The MAgic Lands; she puts a magic
    bracelet on Ronnie so she cannot leave.
12. Again Ronnie is horrified, but she sees an opportunity to make the
    life of the common people better so she vows to do her best.
13. Grand Mistress gives Ronnie Master Awk's staff; she must learn to
    use it wisely.
14. Epilog: Ronnnnie goes to the Magic Archives where we last see her,
    studying a book about the ancient history of the galaxy complete
    with pictures of the Tigerfu, The People of the Rainbow Sky, the
    Fungusians, The White Bear Union people, the Fungusians, the Trololu
    and the Pantherans.

Definition of AWK 1 obsolete : turned or done the wrong way 2 obsolete :
perverse 48 words to make in SCRABBLE® with Q and no U » 3 obsolete :
awkward, clumsy

Origin of AWK Middle English awke

2awk adverb Definition of AWK obsolete : in the wrong way Variants of
AWK awk or awkly

* Thoughts on the Sequel
  :PROPERTIES:
  :CUSTOM_ID: thoughts-on-the-sequel
  :END:

*Book 2*

- 

  - Stage One: Ordinary World. Ronnie is in the library studying some ::
    old books. The archivist comes in with some very old books and a
    map. The archivist says the map is old, but there is no label saying
    explaining where it is. When the map is unrolled, Ronnie recognizes
    the place. She asks the archivist if she is right. This is a map of
    Tigerfu Land. Startled, the archivist looks. Ronnie shows him the
    river, the mountains, the high mountain peak. She tells the
    archivist she has been there. There are buildings along the river.

- 

  - Stage Two: Call to Adventure. The archivist has hurried away to ::
    investigate further when Ronnie receives a call from Captain Star
    Runner. The Pantheran is in orbit. Ronnie explains she cannot leave
    because of the constraints of the tribunal that passed judgment on
    her, but STar is welcome to come to the planet. Star complies
    quickly and joins Ronnie. She updates Star and shows Star the map.
    Star explains that the Fungusian Network is very interested in the
    history of Tigerfu Land. They think it may hold cluesthat will help
    in the War of Consolidation. Star wants Ronnie to accompany Star to
    Tigerfu Land which Star continues to call Planet X. The archivist
    returns and Ronnie asks the archivist if magic can be practiced on
    Planet X. The archivist says it falls within The MAgic Lands.

- 

  - Stage Three: Refusal of the Call. Ronnie and Star go to see Grand ::
    Mistress Vesha for Ronnie to seek permission to go to Tigerfu Land.
    At first Vesha objects. Ronnie will be out of direct supervision.
    Ronnie suggests Tripp come with them. Tripp is proficient, reliable
    and likes history. Reluctantly, Vesha agrees.

- Stage Four: Meeting the mentor. The archivist has also been made a
  part of their party. The archivist will act as the mentor, the adult
  in charge. The archivist is very excited that there is new information
  on Tigerfu Land.
- 

  - Stage Five: Crossing the Threshold: This time, the fanikula and the
    :: robots at the hotel prove problematic. They identify Ronnie,
    Tripp and the archivist as wizzards and do not want them to pass.
    However, they figure out to do it and get up the mountain.

Elixir: Ronnie realizes Star (and perhaps all subjugated races) are
under a spell of compulsion to serve The People of the Rainbow Sky and
The White Bear Union. She returns to MAgic City to look up, with the
archivist's help, a way to unbind Star. Ronnie calls a Council of
Wizzards to make the charm for Star. When she puts the charm around
Star's neck, Star and Star's AI report a physiological change. At first,
Star is very sick, but then recovers and all is well. At the end of the
story, Star has passed all this information onto the Fungusian Network.
Neither Ronnie or Star know if the Fungusians are affected by any magic.
Grand Mistress Vesha passes on to the Tigerfu military that magic may be
involved in the War of Consolidation.

The use of magic in warfare will be classified as a war crime.

** An Idea for Chapter Titles
   :PROPERTIES:
   :CUSTOM_ID: an-idea-for-chapter-titles
   :END:

- Chapter One Looking Forward to Finally Getting to Work
- Chapter Two: Why Am I Being Singled Out?
- Chapter Three: Introducing Grand Master Awke, Emeritus
- Chapter Four: There Must Be A Mistake
- Chapter Five: I Face the Inevitable
- Chapter Six: Boarding the Merchant of Venice, UGH!
- Chapter Seven: The Three Laws of Magic
- Chapter Eight: The Captain's Warning
- Chapter Nine: The Spaceport Fortress
- Chapter Ten: Tea with the Grand Mistress
- Chapter Eleven: Traveling Aboard a Sky Boat
- Chapter Twelve: Trouble in River City
- Chapter Thirteen: Playing with Clouds
- Chapter Fourteen: Arrival At the Musical Mountains
- Chapter Fifteen: Senior Master Roop
- Chapter Sixteen: Figuring Out How to Investigate in a Magical Place
- Chapter Seventeen: Asking Questions and Getting Rebuffed (I am trying
  to investigate the way I know how--asking quesstions, but I cannot
  come off as being too dense. Grand Master Awke has told everyone how
  brilliant I will be someday. Besides, I want to impress Senior Master
  Roop with my abilities. I suspect he is interested in me in other
  ways, but I do not find him physically attractive. Not that he is not
  a handsome specimen. I just like girls better. His equipment looks
  painful to a female anyway.)
- Chapter Eighteen: It Is All in the Logs If You Know How to Read Them
  (It is a good thing I went to War Crimes School. It helps. I k now
  quite a bit now about Tigerfu technology and although there is a lot
  of magic around here, even modern wizzards digitize a lot of stuff.
  And it is worse than we thought.)
- Chapter Nineteen: Putting Together the Case to Present to Grand Master
  Awke
- Chapter Twenty: I Must Stop Senior Master Roop right away. (There is
  no time to waste finding Grand MAster Awke. Besides, he usually takes
  a nap at this time.)
- Chapter Twenty-One: Confrontation (Oh, and here is Grand MAster Awke
  coming into the room. No time to explain. Roop is readying something.
  Now, watch this. I can do magic.)
- Chapter Twenty-Two: Deposition in Magic City (I did not think I cared
  so much for Grand Master Awke. I am sorry he is dead. I would have
  expected Grand Mistress Vesha to be pleased I figured things out. She
  is not and I do not know what will happen at the Tribunal. I wish
  Tripp was here. She is a good friend and I did not know that until
  now. I have certainly made a mess of things. I hope I survive and they
  do not change me into a mouse or something. Can they do that? I mean,
  can they do that and if so, are they allowed to do that? Would a law
  or regulation stop them? Grand Mistress Vesha is very angry. She does
  not shout. She just gets colder and colder. That kind of fury is hard
  to take.)
- Chapter Twenty-two: The Tribunal. I cannot believe it. Senior Master
  Gaunt is testifying on my behalf. Tripp is, too. They are making the
  case that I acted to stop Roop from sending out the message and
  therefore my punishment should be lessened. They agree with Grand
  Mistress Vesha that my use of magic was not well thought out, but they
  insist Grand Master Awke's death was an accident. I could not have
  anticipated that he would come into the transmission room. He did
  normally take a nap at that time. Senior Master Gaunt suggests that
  Grand MAster Awke came because he sensed trouble or the inappropriate
  use of magic. Senior Master Gaunt admits he did not realize somehting
  was wrong until our magical fight, but he strongly believes Master
  Awke was far more sensitive. Grand Mistress Vesha cannot help herself.
  She believes it, too.
- Chapter Twenty-Three: The Verdict . I am going to be stuck here. I am
  basically under house arrest though I can travel anywhere in The Magic
  Lands. Senior Master Gaunt and Grand Mistress Vesha are convinced I
  will be a very powerful wizzard some day if I study. I still quite get
  my head around this. Tripp says I should feel very fortunate. Grand
  Mistress Vesha will oversee my training. I'm not so sure.
- Chapter Twenty-Four: The Book in the Library. Grand Mistress Vesha has
  sent me to the archives. It's a very spooky building. I expect the
  gargoils to spring to life at any moment. Shen is the archivist and a
  senior master wizzard in his own right. I ask him why the books have
  not been digitized. He says it is because they may contain magic and
  you cannot digitize magic. I ask if digitizing them will hurt them. He
  says no so I start the process with my studies. In the room where I am
  working, there are maps. They are two-dimensional and I realize they
  are star charts. I ask Archivist Shen about them. He says they are
  quite old and he does not know much else about them except there is
  something magical about them. He goes away and comes back to say they
  will create a three-dimensional picture of space. He shows me how. It
  is quite impressive. I get absorbed in casting the spell, looking at
  the chart and then undoing the spell again. I report to Grand Mistress
  Vesha. She simply reminds me to study my lessons, but she does not
  forbid me from looking at the maps. This is a good thing.
- Chapter Twenty-five: The Star Chart I Can Read (I wander through the
  archives, looking for more maps. There are lots of them. I work out
  their spells and look at more and more charts. None of them are
  familiar. Then I find a very old map. Its spell is very hard. I use
  all the things I have been taught to work it out. I walk around, among
  the stars themselves, and I see it. Here ishe star system where Planet
  X is located. Captain Star Runner and I learned it is not called
  Planet X but Tigerfu Land. It is the Tigerfu original homeland.,
  Tigerfu Land has a special marker attached to it. This marker says it
  is part of The Magic Lands although it is not near where I am. I ask
  Archivist Shen about this. He confirms it. I ask him for more
  information on the planet. I do not tell him I have been there
  recently. He brings me a very old book. Together we work to open it.
  It is closed by very strong magic. Archivist Shen he cannot open it.
- Chapter Twenty-Six: I Open the Book. I explain all this to Grand
  Mistress Vesha. I have learned to read her fairly well. She is both
  surprised and excited though she does not want me to know this. She
  instructs me to discover how to open the book. I object. If the
  archivist cannot open it, why does she think I, a mere apprentice,
  cannot open it. She begrudgingly explains that Archivist Shen has
  already contacted her about the book. It has a special magical lock.
  Only someone with great magical power can open the book... Grand
  Mistress Vesha wants to know if I am such a person. I go back to the
  archives and work on it. In time, I open it. There before me are
  beautiful pictures. I recognize the animals in them. Or should I say
  people. The Pantherans are there along with the Fungusians and the
  Featherote. I also see Tigerfu and what are the White Bear People.
  There are humanoids which must be The Peoploe of the Rainbow Sky and
  those like Samara and Beja. And here are Trololu, too. The script is
  ancient. I cannot decifer it. To read the book I must learn more.
  Archivist Shen documents my ability to open the book. He marvels are
  the pictures, too. I tell him what some of the strange beings are.
  Grand Mistress Vesha comes to look at the book, too. She is not so
  interested in what the book contains but in the fact that I can open
  the book. It confirms Grand Master Awke's assessment that I am will
  become a great wizzard. I don't know if I am happy about this. It
  means I must stay here, probably forever. Well, I wanted a new
  homeland. I just didn't think it would be like this.
