** Main Character Questionnaire 1
:PROPERTIES:
:CUSTOM_ID: main-character-questionnaire-1
:END:
I've started reading the [[https://blog.lettersandlight.org/][The Office
of Letters and Light Blog]] and getting some ideas for writing my 2013
[[https://www.nanowrimo.org/][Nanowrimo]] novel. One of the suggestions
is to fill out a questionnaire for your main character. I'm not sure all
the questions apply, but I thought I would give it a shot and post my
responses here. Later I can turn all the posts into one complete
article.

*** 1. Name
:PROPERTIES:
:CUSTOM_ID: name
:END:
Name: Ronnie Camberwell.

To be exact, it's Veronica Camberwell. As she is named for a
[[https://n.wikipedia.org/wiki/J._S._Fletcher/][J. S. Fletcher]]
character named Ronald Camberwell. I've never thought of a middle name
for her.

*** 2. Age
:PROPERTIES:
:CUSTOM_ID: age
:END:
I've never thought of her age. Let's say she's somewhere between thirty
and thirty-five. I would have to think very carefully about her time
line in the stories I've already written to work out her exact age.

*** 3. Height
:PROPERTIES:
:CUSTOM_ID: height
:END:
Ronnie is tall. Let's say around 5 feet eleven inches. I have no idea
what that would be in meters.

*** 4. Eye Color
:PROPERTIES:
:CUSTOM_ID: eye-color
:END:
I've not really thought about this. Let's say they're green.

*** 5. Physical Appearance
:PROPERTIES:
:CUSTOM_ID: physical-appearance
:END:
Ronnie is tall with dark hair and green eyes. She has large hands. She
is bony and lacks grace when she moves.

*** 6. Strange or Unique Physical Attributes
:PROPERTIES:
:CUSTOM_ID: strange-or-unique-physical-attributes
:END:
Ronnie is physically strong and possesses physical stamina.

*** 7. Favorite clothing style/outfit
:PROPERTIES:
:CUSTOM_ID: favorite-clothing-styleoutfit
:END:
Ronnie wears trousers and a shirt. She has no fashion sense at all. Her
clothing is practical and durable.

*** 8. Where does he or she Live? What is it like there?
:PROPERTIES:
:CUSTOM_ID: where-does-he-or-she-live-what-is-it-like-there
:END:
Ronnie currently lives in Capital City on Marathon. She has a dingy room
in a down-and-out section of the city.

*** 9. Defining gestures/movements (i.e., curling his or her lip when he or she speaks, always keeping his or her eyes on the ground, etc.)
:PROPERTIES:
:CUSTOM_ID: defining-gesturesmovements-i.e.-curling-his-or-her-lip-when-he-or-she-speaks-always-keeping-his-or-her-eyes-on-the-ground-etc.
:END:
Ronnie strides when she walks. She is heavy-footed.

​###10. Things about his or her appearance he or she would most like to
change ###

Ronnie would like to appear more feminine, comfortable in soft fabrics,
swirling skirts and delicate jewelry. She wonders what it would be like
to chatter about unimportant things and basically glide through life as
an airhead.

*** 11. Speaking style (fast, talkative, monotone, etc.)
:PROPERTIES:
:CUSTOM_ID: speaking-style-fast-talkative-monotone-etc.
:END:
Ronnie speaks in a forthright manner. She is uncomfortable with the
sentence, "I don't know."

*** 12. Pet Peeves
:PROPERTIES:
:CUSTOM_ID: pet-peeves
:END:
#+begin_example
1.  People assuming she is heterosexual.
2.  People rejectibelieving all Pantherans are dangerous.
#+end_example

*** 13. Fondest Memory
:PROPERTIES:
:CUSTOM_ID: fondest-memory
:END:
The generalized answer to this one is Ronie's time with Captain Star
Runner. She remembers seeing Star for the first time at Shepheard's
Hotel. She remembers what it is like to make love. She remembers how
happy she was when Star returned from space.

*** 14. Hobbies/interests
:PROPERTIES:
:CUSTOM_ID: hobbiesinterests
:END:
I can't think of any.

​###15. Special skills/abilities ###

Ronnie is a trained police officer and detective. She knows how to
handle a ray gun. She has a rudimentary knowledge of flying an aircraft.

*** 16. Insecurities
:PROPERTIES:
:CUSTOM_ID: insecurities
:END:
Ronnie questions her ability to support herself on Marathon. Her inate
shyness is coming to the fore.
