* Initial Idea
  :PROPERTIES:
  :CUSTOM_ID: initial-idea
  :END:

- The novel is called Mulberry Bend, A Ronnie Camberwell Novel

- It takes place after The Three Laws of Magic

- It takes place in the main the capital city of the Magic Lands.

- To the uninitiated, the city appears to be a medieval city. To Ronnie,
  it is a city with very extremes of well-being.

- In a very poor area called Five Points, there is a winding street
  called Mulberry Bend.

- The mystery centers in this area and on this street.


* Take the idea of a lost girl who ends up here. Tripp and Ronnie set out to find her. Explores the relationship between Tripp and Ronnie and is Ronnie's first trip outside of the wizard compound. Ronnie is restricted to the city. Tripp is still sexually attracted to Ronnie. Ronnie is conflicted, wanting Tripp but also tied to the absent Captain Star Runner. 

Some ideas about the lost girl:

  - a Tigerfu
  - Not from the capital city
  - Grand Mistress Luna is very anxious that the girl be found so the
    wizards reputation does not suffer but she is not invested in the
    girl at all. Ronnie is appalled. Tripp is philosophical.
  - The leader of the field trip is anxious her reputation will suffer
    but she is not really invested in the girl. Ronnie presses her to
    understand. The girl is mute and her guardian merely wants the
    girl off her hands. It seems everyone has this attitutde. With
    four hands, Ronnie can't figure out why the girl cannot sign and
    make herself understood.
  - Tripp explains the Tigerfu in this part of the Confederacy is not
    particularly sympathetic to disabilities. It's a very frontier
    mentality and everyone has to pull their own weight.
  - Ronnie has to rethink her idea about the Tigerfu and their
    openness. Why doesn't this girl get any help. Can her disability
    be mitigated? The Tigerfu are very advanced with surgery and
    psychology. Can the girl speak and chooses not to because of
    trauma or is she physically unable to speak?
  - Ronnie checks the library catalog. Muteness is covered in the
    catalog. From the entry, Ronnie believes the ancient wizards knew
    something about it but she has not delved deeply enough into
    reading the library volumes on these subjects to be fluent enough
    to read the texts easily.
