The Three Laws of Magic

The Magic Lands, Book 1

by Rill Woolnough

November, 2019

* Novel Scenes
 
** Act I

1. Opening (1% 500 words)

   Ronnie and her class of Tigerfoo War Crimes Investigators are taking
   their oath to of office to be War Crimes Investigators. This
   includes loyalty to the Tigerfoo Confederacy.

2. Stage One: Ordinary World (1-10% 500-5000 words)

   Ronnie is in the classroom where everyone is receiving their
   assignment. Ronnie is a human female. All the other participants are
   Tigerfoo. When it comes to Ronnie's turn, she is simply told to report
   to the Director's Office. The instructor does not know any more than
   this. Ronnie is upset. What could she have done wrong? She had
   completed all her assignments successfully. In fact, she is in the
   top three to five in the class. Her only shortcomings are her
   unfamiliarity with all the nuances of Tigerfoo culture and its
   history. Or is it that the Tigerfoo do not want a human involved in
   their war crime investigations? The Tigerfoo think of themselves as
   being a very moral people. Everyone stares after Ronnie as she
   leaves.

   Ronnie gives her back story as she makes her way to the director's
   office.

   #+begin_center
   State the theme
   #+end_center

   Ronnie goes to the director's office to receive her assignment.
   Ronnie is given no information, just that someone named Grand Master
   Awk, Emeritus, will be her new team leader. She is to meet with him
   immediately. The director cannot tell her any more. The director is
   in a hurry to dismiss her. Master Awk's operation is top secret. The
   Director does not have the clearance to discuss it with Ronnie.
   Ronnie has more of a bad feeling about this. What is going on? How
   can she have a higher security clearance than the Director of the War
   Crimes Tribunal?

   The director says: "Ronnie, you have just sworn an oath to defend
   the Tigerfoo Confederacy. Remember your duty and with great power
   comes great responsibility."

3. Stage Two Call to Adventure  (10%) 5000 words

   Ronnie meets Grand Master Awk, Emeritus for the first time. He
   explains that he is a wizzard and she is to be his new apprentice.
   Ronnie storms from the room. Is this a joke?

4. Stage Three Refusal of the Call  (11-20%) 5500-10000 words

   Ronnie goes about the school--the director's office, the instructors'
   offices, meeting up with her classmates and then going back to her
   room.

   1. The director tells her she is the only one for the job.

   2. Her instructor tells her she is well-qualified for whatever
      assignment she is given.

   3. Her friend tells her that she can't just quit and go home. She
      owes the Confederacy the cost of her education. Since Ronnie
      cannot pay, she has little alternative.

   4. returning to her room, she learns she needs to vacate quickly. The
      next class is coming in and will need it.

   5. Ronnie packing and brooding. She goes over in her mind what she has
      learned from Grand Master Awk. There is a lot to be learned. She
      feels very alone and wishes for her friends from Ptolemy City,
      especially Captain Star Runner. We learn more about Ronnie's back
      story here and her misgivings about magic.

   6. With no alternative,
      Ronnie returns to Grand Master Awk reluctantly and with a chip on
      her shoulder.

5. Stage Four: Meeting with the Mentor\ 
      Ronnie returns to Grand Master Awk. She is not well-pleased, but
      assessment of Grand Master Awk is that he is very old and confused.
      He must have been an impressive Tigerfoo once, but age and dementia is
      robbing him of his faculties.

   Act I is 25% of your novel. For Nanowrimo, this is 12,500 words.

** Act II

6. [@6] Stage Five: Crossing the Threshhold 

   1. Ronnie goes aboard the spacecraft. It is clear from the scene at the
      spaceport that their craft is located far from the regular commercial
      traffic. The ship is old and utilitarian. This is not a luxury
      flight. Instead, it is a small freighter. Ronnie and Grand Master Awk
      are the only passengers. The crew is minimal. Ronnie finds the ship
      very claustrophobic. The confinement aboard ship amplifies her fear
      of going to The Magic Lands. This turn of events seems far from her
      aspiration to be a war crimes investigator.

   2. Master Awk instructs Ronnie. Grand Master Awk explains to Ronnie that
      some people have an aptitude for magic. Her profile says she does. In
      The MAgic Lands, magic works and those who practice it belong to an
      organization which oversees their training and their work. Practicing
      magic outside of this organization's oversight is illegal. He tells
      Ronnie that by convention practitioners are called wizzards and they
      call what they do magic. Sorcerers, on the other hand, are people who
      practice sorcery outside of the guild's oversight. It's just words,
      Master Awk stresses, but it might be helpful for Ronnie to
      understand. Her training will be to be able to use her gift and to
      study. Can she read Tigerfoo? Can she read ancient Tigerfoo? When
      Ronnie says she has a functional literacy with modern Tigerfoo but no
      understanding of ancient Tigerfoo or Tigerfoo script, GRand Master Awk
      is disappoiinted. She will have to learn both to study the ancient
      lore. The books cannot be digitized. Part of the instruction is
      learning how to read a magical book, and the books themselves are
      magical. Ronnie will learn much later what a gift she has received
      from Grand Master Awk. Not even Grand Mistress Vesha knows how to
      read these books well. Grand Master Awk is the only surviving wizard
      who does and Ronnie learns her lessons very well. All this talk of
      magic makes Ronnie's head hurt. She is convinced this is an elaborate
      hoax but she doesn't understand what it is covering up.Again
      Grand Master Awk stresses that with great power comes great responsibility.

   3. The captain takes Ronnie aside. He warns her about going to the
      MAgic Lands and offers her any assistance he can give her when
      she decides to leave. He is secretly opposed to the People of
      the Rainbow Sky but cannot openly declare his opposition or his
      ship and his crew would be destroyed.

   4. Arriving in The Magic Lands. The disembarkation point looks ancient,
      made out of stone with narrow corridors and low ceilings.
   5. After passing through this area, they enter Magic City which looks
      like a fairy city with lots of spires. Although the disembarkation
      area looked European medieval, this looks more Victorian.
   6. Grand Master Awk takes Ronnie to meet the current Grand Master,
      Vesha. She reminds Ronnie of a witch with a pointed nose and chin.
      All she needs, Ronnie thinks, is a hat and a broomstick. Grand Master
      Vesha asks Ronnie a few questions, but Ronnie thinks these are
      perfunctory. What the grand master is doing is taking Ronnie's
      measure.
   7. Afterwards, Ronnie is asked to leave so the two elderly grand masters
      can speak together. Grand Master Awk exits the meeting looking
      unhappy.

7. Stage Seven, Tests, Allies and Enemies

   1. Crossing to the Musical Mountains.Ronnie and Grand Master Awk board
      an open vehicle that floats over the countryside low enough so that
      they can see if and even inteeract with its inhabitants. There are
      villages and market towns--lots of farms and animals. Everything
      looks quite low tech. Ronnie wonders how advanced the culture is.
      Grand Master Awk explains that the people of this planet have chosen
      this style of living and much of their lives are made easier by
      magic. Ronnie, looking at Tigerfoo faces and body language is not sure
      Grand Master Awk is telling her the truth. Life appears to be very
      hard and many people she sees look unfed or ill or both. Medical care
      seems lacking as she sees people with untended injuries. She would
      like to stop and speak with them but there is little opportunity as
      their hovercraft continues its glide.

   2. In the River City. The hovercraft finally stops at a city. Grand
      Master Awk and Ronnie disembark and make their way to a small hotel.
      There Ronnie meets Senior Master Gaunt and his Apprentice Tripp. They
      will be joining Ronnie and Grand Master Awk on their journey to the
      Musical Mountains. Ronnie learns Senior Master Gaunt and Apprentice
      Tripp have already been working there but came to meet Grand Master
      Awk and her in this city to escort them to the Musical Mountains.
      Ronnie wonders why an escort is necessary. Apprentice Tripp tells
      Ronnie Senior Master Gaunt wants to talk with Grand Master Awk before
      they get there. This gives the apprentices a time to get to know each
      other.

   3. The wizzards teach the apprentices how to change the shape of the
      clouds. Ronnie thinks of it like making balloon animals.

8. State Eight: Approach to the
   Inmost Cave (literally) /  

   1. They arrive at the Musical Mountains. The mountains are
      breathtaking,complete with snowy peaks and clouds. They do make
      music. Most notably, along with rockycrags, waterfalls, rivers,
      gorges, mountain meadows, forests andsuch, the mountains have
      large areas which are made of glass.These sparkle and there are
      rainbows in prisms. The wizzards andtheir apprentices disembark
      and travel into cave-likestructures, deep inside the mountain.
      Although some corridorsare completely enclosed, many go through
      glass and are brightly    lit. The enclosed, dark corridors
      makes Ronnie nervous. Being enclosed is not the problem for
      her.. Not having a sky is. The enclosed spaces make her think of
      spaceships and space stations. She is not fond of either. She
      can feel the magic all around her. It is ancient and profound.
      With much giving of passwords and bio  scans, they are finally
      at the Project.

      Ronnie starts feeling  much better. She is enjoying her
      friendship with Tripp, is  enjoying the simple magic she is
      learning. She is looking forward to her investigation, believing
      it has othing to do with magic but everything to do with
      identifying the bad guy. She has done this before and is
      confident she can do it again. Things are looking up in the
      Magic Lands. This is not the assignment she wanted, but she is a
      much bigger cheese in this scenario and she is looking forward
      to the accolades she will receive for  solving the case. Then,
      she believes, she will be able to return to War Crimes
      Investigations. This is the midpoint of the story 50% or 25000 words for Nanowrimo.

   2. Grand Master Awk presents Ronnie to Most Senior Master Roop. Roop is
      the wizzard in charge of the project. He must accept Grand Master Awk
      because of his status. Roop does not have to accept Ronnie. The
      interview is frought with tention. Roop is the final threshold
      guardian. Ronnie wonders what will happen to the plan for her to
      investigate if Roop rejects her. Roop, for his part, is terrified by
      Grand Master Awk's arrival. He is uncertain how much magic the old
      Tigerfoo can still perform. There have been rumors of Grand MAster
      Awk's forgetfulness and failing abilities. However, he can probably
      still teach. Ronnie is an unknown quantity and she is an alien. Roop
      is suspicious, but he cannot show his suspicion. The project is in
      trouble and perhaps Grand Master Awk can be pursuaded to actually
      help. Ronnie may be his way to avoid suspicion. Roop immediately sees
      how observant she is. He wonders if she is a spy. But perhaps, with a
      judicious use of magic and charm, he can turn her to his advantage.
      Roop does not know Ronnie is a Lesbian.

   3. Ronnie starts investigating. One of the things she does is look
      through the transfer logs. She notices two things:

      1. The energy is coming from the surface of the planet. This is why
	 the people and the land are so degraded. The transfer machine is
	 literally sucking the life energy out of them. It is supposed to
	 take energy from the core.

      2. There are additional transmissions. Ronnie decodes them and
         learns Roop is communicating with the People of the Rainbow
         Sky. Roop is a traitor, planning the conquest of the Magic
         Lands by the People of the Rainbow Sky. In a weakened
         condition, the planets will be easy pickings. Roop will be
         put in charge.

         There are other transmissions in ancient Tigerfoo which
         Ronnie will need time to decifer completely. Clearly Roop has
         confederates in the MAgic Lands.

   4. Ronnie is on her way to share her findings with Grand Master
      Awk. Quite by accident, she is walking past where Roop is
      sending a message. She realizes it is ancient Tigerfoo, but
      because she has learned this script and this language, she is
      able to decifer the message and more important, learns to whom
      it is addressed. Roop is sending a message to Grand Mistress
      Vesha. It is about Ronnie herself and the need to dispose of her.Without telling anyone, she
      goes to confront Roop herself, believing she is more than
      capable of handling him physically and not taking into account
      his magical abilities. Ronnie strill thinks of magic as parlor
      tricks because that is all she has been taught. The ancient
      script she has learn to read has many spells, but they have
      always seemed fantastical to her.

9. Stage Nine: Ordeal

   1. Ronnie confronts Roop. He is arrogant, confesses but is not
      remorseful. The Tigerfoo are doomed. The People of the Rainbow Sky
      are not only benevalent, but they are further advanced. The Magic
      Lands will benefit from being under the control of the People of
      the Rainow Sky. Can't Ronnie see that? She has seen the people
      working in the fields and knows their despair and dedridation.

      Ronnie shows her hand, accusing Roop of sabataging the transfer
      machine and pulling the energy from the wrong place. "I know who
      your sponsor is, she tells him.

      When Ronnie moves to physically restrain Roop, he sends a powerful
      magical wave toward her, expecting it will knock her down, knock
      her out and likely kill her. It will be easy enough to tell a
      credible story about how she died from something she did to the
      transfer controller. Instinctively, Ronnie blocks the wave but she
      does it without finess. The transfer controller, which does indeed
      have a flaw, explodes, killing Roop and Grand Master Awk who was
      just coming into the room. Ronnie is thrown clear, but knocked
      unconscious. When Tripp and MAster Gaunt rush into the room, they think everyone is dead.

   2. Ronnie awakens to discover she is in Magic City. She feels strange
      and is in pain.     The pain comes from using her magic, albeit
      unintentionally, to defend herself against Roop's magic wave.
      Performing magic always has a cost. Ronnie feels terribly alone
      and comes to the conclusion she is behind some sort of dampening
      field. The guard comes in with her meal and for a short time the field is open.
      Ronnie reaches out to Grand Master Awk, Master Gaunt and Tripp.
      She can't field Awk but she reaches Gaunt and Tripp. She knows
      they will know she is both alive and wanting to talk with them.
      The absence of Grand Master Awk upsets her.. His presence was
      always large and she worries something has happened to him.

   3. Grand Mistress Vesha confirms her fear when she arrives. Further
      she tells Ronnie that the captain of the merchant ship will be
      arriving soon to take her back to the War Crimes Investigation
      School. Vesha says Ronnie's career will be ruined and is quite
      pleased about that. Ronnie keeps her own counsel, knowing Vesha is
      part of the plot to cede the Magic Lands to the People of the
      Rainbow Sky Ronnie wonders what Vesha was offered.

   4. When Vesha leaves, Ronnie has no ideas of what she can do to stop
      Vesha, save the people of the planet and defend herself when she
      is brought back. Will anyone believe her? She is responsible for
      the deaths of two senior wizards and the destruction of a valuable
      piece of equipment.

   5. Guards come to take Ronnie to the spaceport. 

   You are 75% through the novel. 37500 words for Nanowrimo. Possibly you can be 40000 words in if the final act is only 20%, that is, 10000 words.

** Act III

10. [@10] Stage Ten: The Road Back

    1. Outside of the campening field, Ronnie senses Gaunt and Tripp
       are nearby. They make a daring rescue and spirit Ronnie away.

    2. Although both Gaunt and Tripp outrank her, Ronnie takes charge.
       This is my responsibility, she tells them. They must make their
       own decisions whether to stay with her or flee via the captain
       of the spaceship. They want to stay with Ronnie and fight for
       the Magic Lands.

       Gaunt and Tripp are now personas non gratis along with Ronnie. They are in grave danger.

   11. Stage Eleven: Resurrection

   12. Stage Twelve: Return with the Elixir

