* NaNo Prep 101: A Six-Week Workshop and Resource Guide for Writers
* Overview + Table of Contents                                                                          2

So you want to write a novel.

Now, we know that sounds intimidating, but it’s a tried-and-true method that has helped thousands of
writers accomplish their creative dreams. Not sure where to start, or need some extra help? Our
NaNo Prep resources are here to inspire, challenge, and help prepare you to start writing.

Well, you’ve come to the right place! NaNoWriMo (a.k.a. National Novel Writing Month) is a fun,
seat-of-your-pants approach to creative writing. Valuing enthusiasm, determination, and a deadline,
NaNoWriMo is for anyone who has ever thought about writing a novel. We challenge participants to
write a 50,000-word first draft of a novel in one month (traditionally, November).

Here, we’ve collected our favorite tips and resources to help you with your novel prep — and we’ve
divided them into a suggested six-week structure leading up to November 1 (or whenever you start
writing). You can choose to do one section, or all of them. You can do every activity, or skip around.
We’ll be providing additional resources this September and October that complement each session,
so check out our calendar for a schedule of events.

If you’d like to explore the NaNoWriMo community, you can check out our social platforms:

Twitter: https://twitter.com/NaNoWriMo
Facebook: https://www.facebook.com/nanowrimo
Instagram: https://www.instagram.com/nanowrimo/
Forums: https://forums.nanowrimo.org/
YouTube: https://www.youtube.com/user/lettersandlightvideo
Tumblr: https://blog.nanowrimo.org/

We wish you the best of luck with your writing adventures!

— The NaNoWriMo Staff
Overview + Table of Contents                                                  3

                                 Table of Contents

Session 1: Develop a Story Idea You’re Passionate About
(That will take you all the way to 50,000 words) …………………………………….……………………. 4
Session 2: Create Complex, Believable Characters
(Strong enough to shoulder a novel and hold your interest) ……………………………………………. 9

Session 3: Construct a Detailed Plot or Outline
(That will keep you on track with your story) …………………………………………………………….. 19

Session 4: Build a Strong World for Your Characters
(That your readers will want to explore, too) …………………………………………………………….. 37

Session 5: Organize Your Life to Support Your Writing Goals
(And get your community involved) ……………………………………………………...……………….. 42

Session 6: Find, Schedule, and Manage Your Time
(So you can write as much as possible) …………………………………………………………………..48
*      Session 1: Develop a Story Idea You’re Passionate About                                         4

Session 1: Develop a Story Idea You’re Passionate About (That will take you all the way to 50,000 words)

Get started with: 4 Ways to Develop an Idea

1. Borrow a Plot: First, write a summary of 3 books or movies or
   stories you love. Include important characters, major plot turns, and setting. Here’s an example:

   Example: A teenage girl lives in a dystopian world where the USA
   has been divided into 13 Districts, and every year children are
   chosen from each district to fight to the death. The teenage girl
   volunteers to fight in place of her sister. She tries to survive
   while also protesting against the evil Capital and (maybe) falling in love. (Hunger Games).

   Write 3 summaries: Then, choose one of the summaries and start
   changing around different parts - characters, setting, plot turns,
   adjectives, verbs, anything else you like! See where those changes
   take you, and keep writing when you get inspired. Here’s an example:

   Example: A teenage girl lives in a future where the oceans have
   risen and everyone lives on small islands. The water is controlled
   by pirates who demand a sacrifice each year to keep the island
   safe. The girl is chosen, but in a storm, she’s rescued by a
   different kind of pirate ship - one made up of former would-be sacrifices who act as pirates against the pirates. And…

   Okay, so that idea isn’t done yet, but I’m already super into it.
   Also, dibs on that idea. I’m writing it for NaNoWriMo because I liked it so much. You can look for it in hardback in 2021.

   Change around the elements of one or all of your summaries:
2. Borrow a Character: Invent a history or future for someone. Maybe
   it’s a friend you lost touch with after college, a teacher you had,
   a family member you’ve heard stories about, or just someone you’ve
   seen in photos or on the bus. I’d like to write a novel starring my
   great- grandmother someday, inspired by the pictures I’ve seen of
   her (I’ve never really heard anything about her!).

   Who is the person that intrigues you? What was their childhood
   like? What did they dream of? What was their greatest desire? What
   obstacles did they face? What was their greatest triumph?

   Finally (since most novels aren’t someone’s entire life story), you
   have to find the story. What part of that imagined life has the
   most drama, the most ups and downs? A moment of adventure or
   possibility or danger, when things changed? Remember, you’re
   INVENTING this person, so feel free to go wild.

3. News You Can Use: Pick an event from the news. Imagine it from the
   perspective of different people involved with it. So a story about
   a river flooding might include the single mother driving her two
   kids on a camping trip, the park ranger called in to help, the
   farmer who lives down the road. Feel free to use the basics of the
   news story for inspiration, but make up your own details—change the
   place, the time, the specifics of the people involved (age, gender
   identity, personality).

   What news stories have stuck with you?

   What kind of people might be involved? What are their lives like?
   How did they end up in that situation? What will they have to do to
   get out of it? What might have happened years before or what might happen years after?

4. A Whole New World: Scroll through these photos until you find one
   (or more!) that sparks something for you, then pause and write your questions, wonderings, and ideas.

   •    https://www.boredpanda.com/abandoned-places/
   •    https://www.roughguides.com/gallery/20-seriously-weird-places-around-the-world/
   •    https://traveltriangle.com/blog/50-weirdest-places-across-the-world/

   What kind of place is this? How did it get this way? Who might live
   or travel through it? How do they feel? What is it like for them there? What challenges do they face?

* Session 2: Create Complex, Believable Characters (Strong enough to shoulder a novel and keep your interest)

Get started with: Character Development and Questionnaires (adapted from the Young Novelist Workbook)

Most people think that an intriguing plot is what makes a story good,
but the truth is that exciting plots are made up of original and well-developed characters.

Flat Characters vs. Original Characters

  -  Flat character: Steve was a good kid. He got good grades and was never late to class.

  - A better-developed character: Steve Goodhold was a good kid. He
    got good grades and was  never late to class. Little did everyone know that he spent his nights working as an internet hacker for a modern Mafioso who he met through his older cousin, Peter.

    Steve didn’t need much sleep, which was a good thing. He slept maybe two hours a night, and spent the rest of his time stealing identities, wiring funds, and making more money than both his parents combined. He told himself he was saving for college, but the thrill of his secret life of crime was steadily eroding his interest in an Ivy League education.

Not only are characters with hidden depths and secrets more fun to read about, they're also
more fun to write about. Though you'll end up writing about a bunch of different people in your
novel next month, most of them will fall into one of three categories: The protagonist, the
supporting characters, and the antagonist.

The Protagonist

The protagonist is the character with the starring role in your book. In most novels, the
protagonist is on a journey to get what they want more than anything else in the world, whether
it's fame, revenge, reuniting with a long-lost sibling, or something much more elusive, like
overcoming poverty or cancer.

The Supporting Characters

Supporting characters are characters in a novel that have an important role in your protagonist’s
life. Some may be around for the protagonist’s entire journey, some for only part. Supporting
characters can be friends, close relatives, love interests, you name it. These characters also
have dreams of their own, and their adventures will add even more excitement to your novel.

The Physical Antagonist

A physical antagonist is a living, breathing character in a novel that is standing in the way of the
protagonist achieving their goal. This does not mean that all physical antagonists are evil
monsters. Some antagonists stand in the way simply through jealousy, or misunderstanding, or
by having a set of goals that differs from that of the protagonist’s.

If Fernando is your protagonist and he wants to recruit Jill for his dance crew, but Greg asked
her first, this doesn't mean Greg is a “bad guy.” He's just another guy who admires the same
kind of pop-and-lock style.

Then again, there are those antagonists that are just plain evil. It's up to you to decide who's
going to stand in your protagonist's way, and how they are going to do it.

OR

The Abstract Antagonist

Though a lot of antagonists are living, breathing beings, some are not. Some protagonists face
off against illness, or grief, or the powers of a corrupt government. We like to call these kinds of
antagonists abstract antagonists because they don't take actual physical form. If your novel’s
antagonist is not a living person/animal/entity, you have an abstract antagonist.

It may be easier think of it this way: if your protagonist cannot physically kick your antagonist in
the knee, it's probably abstract.

| Physical Antagonist                                                                    | Abstract Antagonist                                                 |
|----------------------------------------------------------------------------------------+---------------------------------------------------------------------|
| A racist or intolerant character                                                       | Racism/intolerance in a community or in general                     |
| A character who is working to make sure your protagonist lives a poverty-stricken life | Poverty or the economy in a community in general                    |
| A character who is forcing your character to struggle against nature                   | Nature as an entity (e.g. a natural disaster or an extreme climate) |
| (e.g. someone who has left your character stranded in Antarctica)                      |                                                                     |
| A character whose beliefs oppress your protagonist                                     | A belief system, religion, or the concept of either                 |
| A government official such as a dictator who has it in for your protagonist            | A corrupt government                                                |
| Your protagonist's evil boss                                                           | A corporation/company                                               |
| A character whose sole mission is to make sure your protagonist becomes ill            | Disease/illness in general                                          |
| (e.g. though poisoning or exposure to a deadly disease)                                |                                                                     |
|----------------------------------------------------------------------------------------+---------------------------------------------------------------------|

It's a great idea for you, the author, to try and get to know your characters before you beginwriting. Enter the character questionnaire!

** Character Questionnaire

Copy the questionnaire below for as many characters as you want to fill it out for, and fill it out
as described below.

*** Section One: All Your Characters

Complete Section One for every character you'd like to. If you have an abstract antagonist, try to answer as many questions as you can from this section for them, then move on to Section Four.

1. Name:

2. Age:

3. Height:

4. Eye color:

5. Physical appearance:

6. Strange or unique physical attributes:

7. Favorite clothing style/outfit:

8. Where do they live? What is it like there?

9. Defining gestures/movements (i.e., curling their lip when they speak, always keeping their
eyes on the ground, etc.):

10. Things about their appearance they would most like to change:

11. Speaking style (fast, talkative, monotone, etc.):

12. Pet peeves:

13. Fondest memory:

14. Hobbies/interests:

15. Special skills/abilities:

16. Insecurities:

17. Quirks/eccentricities:

18. Temperament (easy-going, easily angered, etc.):

19. Negative traits:

20. Things that upset them:

21. Things that embarrass them:

22. This character is highly opinionated about:

23. Any phobias?

24. Things that make them happy:

25. Family (describe):

26. Deepest, darkest secret:

27. Reason they kept this secret for so long:

28. Other people's opinions of this character (What do people like about this character? What
do they dislike about this character?):

29. Favorite bands/songs/type of music:

30. Favorite movies:

31. Favorite TV shows:

32. Favorite books:

33. Favorite foods:

34. Favorite sports/sports teams:

35. Political views:

36. Religion/philosophy of life:

37. Physical health:

38. Dream vacation:

39. Description of their home:

40. Description of where they sleep:

41. Any pets?

42. Best thing that has ever happened to this character:

43. Worst thing that has ever happened to this character:

44. Superstitions:

45. Three words to describe this character:

46. If a song played every time this character walked into the room, what song would it be?


*** Section Two: Questions for Your Supporting Characters

Complete Section Two just for your supporting characters.

1. Relationship to the protagonist:

2. Favorite thing about the protagonist:

3. Similarities to protagonist:

4. Differences from protagonist:

*** Section Three: Questions for a Physical Antagonist

Complete Section Three if you have a physical antagonist.

1. Why are they facing off against the protagonist?

2. Any likeable traits?

3. Weaknesses:

*** Section Four: Questions for an Abstract Antagonist

Complete Section Four if you have an abstract antagonist.

1. What is your abstract antagonist? Is it a disease like cancer, a
   social ill like poverty, or something larger than life, like grief?

2. How is this antagonist affecting the protagonist?

3. Do other characters notice? How does this antagonist affect the
   other people in your novel? And don’t forget: The Three Big
   Character Questions

   1. What does your main character want more than anything in the world?

   2. What do they need to grow as a person (not necessarily the same thing as what they want)?

   3. What major flaws (internal problems) and obstacles (external
      problems) will stand in their way?

Also, just a note: It’s totally normal to not have a sense of who the heck your characters are
until after you finish writing your first draft. So don’t worry if you feel like you don’t have a hold
of your characters yet, or if they start changing on you as you write. That’s part of the process!

** Extra Character Building Resources:
    •    Webcast: Games to Develop Your Characters (with the Society of Young Inklings)
    •    Adoption Society Forum: Hop into any “Adopt a Character” threads to get inspiration
         from other Wrimos
    •    Blog post: 51 Questions You’ve (Probably) Never Asked About Your Characters
    •    New Character Generator
* Session 3: Construct a Detailed Plot or Outline (That will keep you on track with your story)

Get started with: Figuring out which plotting method is right for you.

** Take our plotting method quiz!

What kind of plotting method will work best for you and your story? Take our quiz above to find
out, or explore all five methods we suggest below:

*** Method 1: Stay loose! Jot, Bin, Pants

You’ve got the seed of an idea—a character that calls to you, a world
to discover, maybe a few plot ideas. Now it’s time to explore that
idea, but not on the page… in your head! Okay, that sounded weird.
Here’s what we mean. Instead of writing a whole novel to find out
which twists end up getting you stuck, or to realize that it would’ve
been a more interesting choice for your character to do A instead of B
way back in the beginning, we’re going to do all that story imagining
at the level of scene instead of sentence. (Inspired by Cassandra Lee
Yieng’s blog post).

1. Jot down your scene ideas.

   Get yourself in a creative space, whatever that means for you. For
   me it’s my bed in the morning with a cup of coffee. Use index cards
   or a notebook or the next page. Close your eyes and start imagining
   your way through your novel, as if you were reading it inside your
   head. Jot down every single scene that comes to you using just a
   few words. Take different paths on purpose to see what happens, and
   write down scene ideas even if they contradict each other.

   Examples:

       - Katniss goes hunting.
       - Katniss volunteers.
       - Katniss remembers Peeta giving her bread.
       - Peeta confesses love on TV.

   Do this every day until you’ve thought through and collected around
   50-100 scene ideas (depending on the length of your novel).

2. Sort your ideas by where they should go in your story.

   Time to sort! Spread your index cards on the ground or flip through your notebook or digital doc.
   Group the scenes into beginning, middle, and end piles (or docs, files, bins, etc). Don’t
   throw away any scene ideas yet - add them to a “Maybe Not” group.

3. Organize your scenes.

   Now fine-tune your piles. Look at your beginning pile, figure out what your first few scenes might
   be, and put them in order. Use your instinct to guide you—what makes sense? What feels
   right? If you want more guidance with plot structure, check out our other plotting guides. If you
   realize a scene is missing, add it! Eventually, your goal is to have a list of scenes in the
   order they might happen in your story.

Use your list of scenes as a rough guide to keep you on track and moving forward throughout
the month, but pants your way through all the actual writing. You’ll discover new things about
your characters and world as you write, but the general story structure might not change too
much. Or it might! You can always return to the dreamstorm stage if you realize you need to
imagine your way down a different path.

*** Method 2: Give me the basics: Plot Rollercoaster

You're all about the essentials—nothing too complicated or specific. The Plot Rollercoaster is a
good outlining structure to start with. You might even remember learning about it in school!
Whether you stop here or use it as a starting point for more in-depth planning, it’s a good tool to
have in your writing bag (box? knapsack? treasure chest?).

As you can see, the Plot Rollercoaster consists of six sections:

**** Section 1: Set-Up

Most novels begin by showing a little bit about the characters, the setting, and the conflict before
jumping fully into the action. The set-up of a story is like the start of a rollercoaster: you get
hints of the exciting, scary stuff coming up ahead, but for the most part, you're just looking
around and getting to know the people on the ride with you.

**** Section 2: Inciting Incident

The inciting incident launches your protagonist into the adventure whether they're ready or
not. It can be a pretty exciting moment for your main character. Once it happens, there's no
turning back...

**** Section 3: Rising Action
      Session 3: Construct a Detailed Plot or Outline                                               25

The rising action is the longest section of a novel. It's made up of many events, each of them
building up to the most exciting part of your story: the climax. It's where you develop your
characters, deepen their relationships with one another, and lay out everything that happens to
them before that big finish. Think of the rising action as the biggest hill on the rollercoaster—
the higher you go, the more suspenseful it gets.

**** Section 4: Climax

The climax is the “gasp” moment. It's the moment at the very top of the rollercoaster, right
before the high-speed drop. This moment doesn’t last long, and neither does the climax in your
novel. It can be as short as one paragraph—just enough to make your readers hold their breath
in suspense and ask, “What’s going to happen next?!”

**** Section 5: Falling Action

The falling action is what happens next. It is the fast-paced, action-packed part of your novel.
You’re finally speeding down the tracks of the rollercoaster with your hands in the air! Does the
antagonist get defeated? Do the protagonist’s dreams finally come true? If so, how?

**** Section 6: Resolution

The resolution is how things work out in the very end, after your protagonist gets (or doesn’t
get) what they want. It's also a place to show how your character and their life have changed.
This change happens little by little as your protagonist faces their fears, defeats villains, and
builds relationships with a cast of amazing characters. All these adventures will end up
changing the way your main character sees the world and their place in it. Try to use the final
scenes of your book to highlight those changes.

Now it’s your turn to outline your plot. You don’t have to describe everything that will
happen in your novel—some things you won't discover until you start writing! This is just
to help you get an idea about what will happen in the beginning, middle, and end of your
book

If it helps you structure your plot, you can use the blank "Plot Rollercoaster” on the next page.
To get an idea of how to use the blank rollercoaster, check out the in-depth example in our
Young Novelist Workbook. If you’re feeling really stuck, it might be because you need to spend
more time just dreaming up your idea. In that case, take out a blank sheet of paper or open a
new doc and spend some time freewriting about your story. Try thinking “What if?” or go back to
your character and conflict exercises.

*** Method 3: I <3 Plot! 9-Step Plot Dot

“Beginning, middle, and end” just doesn’t cut it for you - you want more! You’re not making any
100-point outlines, but you do appreciate a well-structured, well-planned plot. Why not try the
elegant yet simple, detailed yet accessible 9-Step Plot Dot (adapted from the Hero’s Journey
model)?

As NaNoWriMo participant Derek Murphy said in his Plot Dot blog post: “Nearly all fiction follows
some version of the classical hero’s journey: a character has an experience, learns something,
and is consequently improved. There are turning points and scenes that need to be included in
your story—if they are missing it won’t connect with readers in an emotionally powerful way.
And it’s a thousand times easier to map them out before you write your book.” We couldn’t have
said it better ourselves. Follow this 9-Step structure to discover the tentpoles of your story, and
read the whole blog post here for more details and guidance.

1. Ordinary World (start with lack) – Show your main character (MC) and their normal life,
   including friends, family, job/school. What flaws do they have? What’s missing from their
   life? What do they want more than anything in the world?

2.     Inciting Incident (call to adventure) – Boom! Something big
   changes. Maybe a stranger moves to town, or a family member dies,
   or there’s an earthquake. Whatever it is, it kicks your story into
   action. What happens? How does your MC react? Do they accept this
   call to adventure right away, or try to ignore/deny what’s
   happening so everything can just go back to normal?

3.      First Plot Point (point of no return) – Your MC may have tried
   to avoid the call, but now things are getting weirder/more intense,
   and they’re forced to make a choice to join the action. Everything
   changes - there’s no going back now! How does the situation
   escalate? What forces your MC to choose? How do they feel about it all?

4.      First Pinch Point (first battle) – Your MC has been exploring
   their new situation - meeting people, learning new things....and
   discovering new dangers and tensions. This all leads to the First
   Pinch Point, which is the first major interaction with the
   antagonist (in some form). What happens? What will happen if your
   MC fails to defeat this challenge at the end of the story (the stakes)?

5.     Midpoint (shift from victim to warrior) – Your MC continues to
   face new challenges, but they’re on the defense - mostly reacting,
   waiting, making things worse. Then, halfway through the novel,
   something happens to shift their perspective and spur them to take
   action, to stop reacting and start winning, no matter what it
   takes. What does your MC try when they’re on the defense? What shifts them into offense? What new plans do they make?

6.     Second Pinch Point (second battle) – Your MC has their second
   confrontation with the antagonist (in some form). Maybe their plans
   lead to this, or maybe it was an attack they had to respond to.
   Either way, this second conflict eventually leads to things being
   much, much worse than they were before… What happens? What does
   your MC try to do? How do things get worse?

7.     Second Plot Point (dark night of the soul) – At this point,
   everything the MC feared could happen, has happened. They’ve lost
   the battle (usually because of their flaw or lack of knowledge) and
   there have been serious consequences. They feel terrible and give
   up all hope… until something forces them to change their mind, to
   have a revelation about themselves and their battle. With this new
   knowledge, they rise up from the ashes. What terrible things have
   happened? What does your MC do? What revelation do they have, and
   what new plans do they make?

8.      Final Battle (triumph-knowledge) – With their new knowledge,
   and maybe a pep talk from a close friend, your MC goes to battle
   with their biggest, baddest enemy (whatever that means in your
   story). Make it dramatic! There’s a back and forth, things seem
   dark, your MC is going to lose, oh no! And then, victory. What will
   that final conflict be? What will be the most exciting, tense, drama-filled part of your story?

9.    Return to Ordinary World – Your MC returns home, changed. They
   see their old life in a new way. How have they changed? What do they do? How do they feel?

** Method 4: More Structure, Please: Save the Cat! 3 Acts / 15 Beats

Some people like to write their way through the wilds of a first draft and then figure out where
the story is later. You are not one of these people! You enjoy figuring out how the pieces of a
story work together, and planning out the specific plot beats of your story ahead of time make
you feel confident and ready to write.

The Save the Cat! Beat Sheet was originally developed by Blake Snyder to help screenwriters
plot movies, but it works just as well with graphic novels and, of course, novels. It breaks down
the three-act structure into small, specific sections (sometimes just one scene long!). Each
section pushes your story forward in its own way. The exact word count/page count of each
section depends on how long your novel is and what type of story you’re telling, but you can use
the colored chart below and the percentages we’ve included in the instructions as a kind of
guide.

Fill in each block below with your ideas for each section. Don’t write you whole novel
here—just jot down general ideas for sections and scenes, like “Javiar’s in elevator when
earthquake hits” and “Molly fights with sister—chases down taxi.”

*** ACT 1

1. Opening Image (0-1%) – Show a “before” snapshot of your protagonist
   and their world. What is life like before the adventure begins?

2.        Set-up (1-10%) – Keep showing that ordinary “before” world.
   Explore your protagonist’s life, including the internal flaws and
   external challenges they’ll have to overcome in order to change for
   the better by the end of the story. Also introduce important
   supporting characters.

3.     Theme Stated (happens during the Set-up) – Somewhere in your
   set-up, include a scene where a character says something that hints
   at what the protagonist’s big life lesson will be - how they’ll
   have to change and grow by the end of the story. The protagonist
   won’t understand the lesson until later, though.

4.      Catalyst (10%) – This is when life-as-they-know-it changes
   forever! There’s no going back to the “before” world from here…
   What is the inciting incident that pushes the protagonist into the next phase of the story?

5.     Debate (11-20%) – But change is scary! Show the protagonist
   questioning themselves and resisting the path ahead - wondering
   whether they have what it takes, or whether or they should just run
   home and hide under the bed. This is their last chance to chicken
   out. “Should I just…?” “I really shouldn’t because…” “But what about…”

*** ACT 2

 @6.      Break Into 2 (20%) – Your protagonist answers the call! They
   make the choice to begin their adventure/transformation/journey/new
   thing. Show your protagonist deciding to plunge into Act 2.

   when the reader thinks “Ah, now we’re getting to the good stuff
   they hinted at on the back cover of this book!” It’s also one of
   the longest sections in your book. Show your protagonist getting
   used to their new world - loving it, hating it, making mistakes or
   doing well, meeting new people (see more below) and keeping the reader entertained.

8.     B Story (happens during The Promise of the Premise) – Introduce
   a new character or characters who will eventually help the
   protagonist learn their life lesson. Friends? Mentors? Love interests? Nemeses (nemesi?)? Who are they? How will they help?

 9.      Midpoint (50%) – This moment is when everything seems “great”
   or everything seems “awful,” depending on your story. Either the
   Fun and Games section has lead to a false victory for your
   protagonist (they think they’ve been doing great so far) or a false
   defeat (they’ve been having a hard time so far). What happens in this moment, halfway between beginning and end?

10.      Bad Guys Close In (51-75%) – Get ready for a bumpy ride. If
    your Midpoint was a false victory, now things start to go wrong
    for your protagonist. If the Midpoint was a false defeat, well,
    things seem to be looking up, but the bad guys are getting closer
    and will have something to say. Note: Bad guys can be actual
    physical enemies, but they can also be emotional enemies, like
    doubt or jealousy or fear. Show the protagonist’s newly-built
    world beginning to unravel. (This will also be one of the longer sections in your novel).

11.      All is Lost (75%) – Oh, dear. This is when something happens
    to make your character hit rock bottom. It’s the absolute lowest
    part of your novel. Maybe someone or something dies (either literally or figuratively). What does this moment look like for your protagonist?

12.    Dark Night of the Soul (76-80%) – Your protagonist now has time
    to react to their “All is lost” moment, to mourn what they lost
    and wallow in hopelessness. Yeah, it’s not pretty. They’re worse off than they were at the beginning of the novel. Show how low things have gotten.

*** ACT 3

13.    Break Into 3 (80%) – The “aha!” moment; the “lift yourself up
    and try again” moment. Show the protagonist realizing what they
    need to do in order to tackle their problems, both external and internal.

14.    Finale (81-99%) – The protagonist does what they decided to do
    in the Break Intro 3 beat, and (because of all the
    learning/growing they’ve done and the support or insight from the
    B Story), their plan works! The Bad Guys are defeated, the world
    is changed for the better. What are the battles? How will the
    protagonist triumph (or not)? This is another longer section, so you’ve got the space to make things dramatic and intense!

15.   Final Image (99-100%) – This is the opposite of the Opening
    Image, the “after” snapshot instead of the “before.” Show the
    reader how the protagonist and their world have changed!

** Method 5: I <3 Outlining SO MUCH: Katytastic’s 3 Act / 9 Block / 27 Chapter
Outline

GIVE ME ALL THE PLANS! GIVE THEM TO ME! For those of us who love spreadsheets, who
enjoy step-by-steps, who like to understand all the nitty, gritty little pieces of how something
works, or who just feel like they could use some detailed and specific support around how to
plot, enjoy! 3 Acts, 9 Blocks, 27 Chapters...one well-structured story.

                              Watch Katytastic’s how-to video.

                                 Fill out the full spreadsheet.
| ACT 1 (Set Up)        | ACT 2 (Conflict)                        | ACT 3 (Resolution)       |
|                       |                                         |                          |
| 1 - Introductions     | 10 - New World                          | 19 - Calm Before Storm   |
| 2 - Inciting Incident | 11 - Fun and Games                      | 20 - Plot Twist!         |
| 3 - Fall Out          | 12 - Old Juxtaposition                  | 21 - Darkest Moment      |
| 4 - Reaction/ Rebel   | 13 - Build Up                           | 22 - Power Within        |
| 5 - Action            | 14 - Midpoint                           | 23 - Action/ Rally       |
| 6 - Consequence       | 15 - Reversal                           | 24 - Converge            |
| 7 - Pressure          | 16 - Consequence                        | 25 - Battle              |
| 8 - Plot Twist!       | 17 - Trials                             | 26 - Climax              |
| 9 - Push              | -->                     18 - Dedication | 27 - Resolution/ The End |


* Session 4: Build a Strong World for Your Characters (That your readers will want to explore, too)

Get started with: Exploring Your Setting

** Part 1: Settings That Create Moods

Now that you have an outline of your plot, it's time to explore some of the settings for your
novel. The setting of a novel is where and when the story takes place. As you know, most
novels have more than one setting. Usually, the author decides to have one large setting (like
Los Angeles in 1995), and then many smaller settings (like the laundromat where the characters
hang out on the weekends, or the classroom where they get in a fight).

Settings do more than serve as a backdrop to the action in your novel. They can also create or
enhance the mood of your novel.

Mood means the feeling of your novel; its emotional quality. You can also think of the mood as
how you want someone to feel while reading your novel.

Examples: playful, serious, mysterious, tense, warm, dangerous, joyous

If you wanted to create a creepy mood for a scene in your novel, you
could start with something like:

"A one-eyed crow blinked from the branch of a dead tree in the yard, while a three-legged dog howled at the moon."

These images remind us of dark, disturbing things, and show the reader that the scene of the
novel is “creepy” without having to tell them directly

Describe the settings that would help create each of the moods listed below. Try to write
two or three sentences for each mood. Include specific details about the sights, sounds,
sensations (and maybe even smells) of the settings you choose!

Creepy (something different than the example we gave on the previous page):

Joyous:

Suspenseful/tense:

Now make up 2-3 of your own moods and describe a setting that would go along with
each one.

Mood #1:

Mood #2:

Mood #3:

The last step is to apply your new skills to your upcoming novel. Think of a scene from
each section of your novel. Then, write or list details to describe a setting that will help create
the right mood for each scene. For example, you might set your climax on the edge of a
crumbling cliff at sunset in the middle of a thunderstorm.

A setting from your beginning:

A setting from the middle:

Another setting from the middle:

A setting from the climax:

A setting from the end:

Bonus setting:

Great! Now you have settings to enhance the different moods that will be in your novel. You
may want to keep this page handy and use it as you write your novel.

** Part 2: Settings That Reinforce Characters

Another advanced writing trick is to show things about your characters just by putting them in
specific settings. If you were writing about a mysterious person, you might place them in a dark
mansion on a hill outside of town; if you were writing about a musician, you might place them in
a messy room filled with instruments, speakers, and microphones.

Here's us just telling you about Jasmine:

Jasmine was having a hard time. She felt sad and lonely. Her older
sister had just left for college and she missed her every day.

And here's us showing all that about Jasmine through the setting we
put her in:

Jasmine used to think her bedroom was small, but ever since her sister
left for college, it felt too big, like she could get lost inside it.
She bounced on the bottom bunk, then climbed the ladder and stretched
out on the top. No one told her to move.

She rolled to her side and looked around. "You're my room now," she
said to nobody in particular, and the sound echoed around the walls.
Her sister had taken the poster of their favorite band with her, and
the space where it had hung looked sad and blank. Everything looked
sad and blank. Her sister's dresser was swept clean: no necklaces or
curling iron or teddy bears cluttered the wood. The closet was half
empty.

"Good," said Jasmine. "I'm glad to finally have my own room. It's
about time." She pulled the blanket up to her chin. It still smelled
like her sister's vanilla perfume. She curled up into a ball and tried
to fall asleep, but the room was too quiet, and it took a long time.

Jasmine doesn't even have to speak for herself; her room speaks for her!

For each of the following characters, try to come up with a setting that will reflect or
reinforce what you imagine about them. As you write, try to be as detailed as possible. Don’t
forget colors, sounds, and even smells. Focus on where the character is.

The shy new kid in town:

A secret scientist superhero:

A character from your novel:

Another character from your novel:

Extra World-Building Resources:
   •    Webcast: Build Your Fictional World with Games! (with the Society of Young Inklings):
        Get out your notebook and follow along to this webcast.
   •    Blog Post: Ready, Set, Novel! A Guide to Grow Your Novel's World
   •    Blog Post: 20 Questions to Ask Yourself When World-Building
   •    Blog Post: 5 Ways to World-Build

* Session 5: Organize Your Life to Support Your Writing Goals (And get your community involved)

Get started with:

                         Pre-NaNoWriMo Non-Noveling Checklist

Everyday chores, tasks, and responsibilities can pile up quickly. While you’ll never be able to
control all the variables, sometimes you may be able to clear a little space in your busy
schedule (and your busy brain!) by taking care of things ahead of time. Here’s a suggested
checklist of things you might want to try to feel prepared for the month ahead. Of course, some
of these may not be possible or apply to you, so feel free to only use what’s useful! We’ve left a
few blank spaces in each section as well in case you want to fill in your own checklist items.

Stock up on writing fuel! Consider planning out your meals by week or by month and buying all your non-perishable groceries in one big trip.

Bookmark a few quick and easy recipes (crock pots are your friend!), or consider
making and freezing meals ahead of time.

If you can, divvy up your chores with other people. Promise to make up the balance
later.

Deep clean the spaces you’re responsible for (whether that’s your house, your room, or
even just your computer files) before the month begins.

If you have any big work/school items due in November, see if you can extend the
deadline or get as much as possible done in October.

Designate a special writing place for yourself. Try not to make it the same place you do
work or chores; but if it is, how can you make it special for writing? (i.e a candle, a
picture, certain music. Whatever helps you feel creative!)

Make a “Do Not Disturb” sign, or choose some other obvious signal (a hat?
headphones?) to let the people around you know they should leave you alone.

Inform your friends and family that you’ll be writing this month. Tell them how important
it is to you and let them know you might have to prioritize writing over socializing.

Ask someone if they’ll be your accountability buddy. They don’t have to read your
writing, but even just a “Hey, have you written yet today?” text can help keep you on
track.

Are there other non-noveling things you’d like to get done to prepare for NaNoWriMo? Add them
here, and look forward to that sweet sensation of crossing them off later…


**** How to Explain NaNoWriMo to the Important People in Your Life

Having the support of your friends, family, or other important people in your life can help you
accomplish your creative goals. But the truth is, sometimes they just don’t get it. They might not
understand why you want to prioritize your writing over other activities this month.

The best way to get people on your side is often by being open and communicative about your
motivations, although we realize it’s not always the easiest thing to do. That’s why we’ve made a
few resources that should help you navigate these conversations:

1. Create a “Do Not Disturb — Writer at Work!” Sign

   Let your friends and family know that you’re in the writing zone!
   Use this sign that we’ve made (here’s one for our YWP writers!), or get creative and make your own.

2. The Care of NaNoWriMo Writers

   We’ve also made this infographic to show writer-adjacent people how
   they can best support the NaNoWriMo writers in their lives.

3. Write a letter

   As a writer, you may find it easiest to communicate through the
   written word. On the next page, we’ve included a letter that you
   can use to tell the people close to you how important your writing is to you:

#+begin_quote
Dear Important Person,

This November, I will be taking part—along with over 300,000 writers around the world—in
National Novel Writing Month (NaNoWriMo). It's a wild, fast-paced creative writing event where
the challenge is to write 50,000 words of the first draft of a novel in just 30 days. That’s 1,667
words (or about 6.5 double-spaced typed pages) a day! For comparison, The Great Gatsby by
F. Scott Fitzgerald is 50,061 words and The Giver by Lois Lowry is 41,905 words.

You might be thinking to yourself, “Why??? Why are you doing this? Won’t it be hard? Won’t
you get frustrated/bored/overwhelmed?” Thank you for your concern, dear Important Person!
NaNoWriMo is an intense event. It’s about committing to a creative project for a month, even if
that means staying up late or waking up early; even if it means the laundry piles up or I don’t get
to spend as much time with family and friends. It’s a month to challenge myself and explore all
the dark, dusty corners of my imagination. So, yes, it’s probably going to be hard, but I hope it
will be energizing and fulfilling, too. And who knows? I might not do anything else with my draft,
but some novels, like Rainbow Rowell's Fangirl, Sara Gruen's Water For Elephants, and Erin
Morgenstern's The Night Circus, began as NaNoWriMo projects!

Besides just being your awesome Important Person self, here are some ways you can support
me during the month:

- Cheer me on, and celebrate with me when I reach milestones!

- Take on some of the chores I’m normally responsible for.

- Feed me! Unlike wild animals, writers love being fed.

- Ask me how my novel is going (but don’t push too hard if I don’t feel like talking about it).

- If I give you something to read, treat it like the gift it is! First drafts are precious, messy, delicate things that mostly need encouragement and praise. Editing (and constructive advice) is for later.

- Be understanding of why I’m spending so much time alone (and maybe unshowered?).

- If I’m writing, try not to interrupt me. You wouldn’t walk in on a surgeon in the middle of surgery! Well, hopefully you wouldn’t. Unless you’re a nurse or another surgeon. But back to the point: please give me space to write without distraction.

- Write with me! NaNoWriMo is more fun with a buddy. You could sign up
  at nanowrimo.org or, if you’re under 18, you can sign up on the Young Writers Program site at ywp.nanowrimo.org.

Thank you, Important Person. I’m glad to have you in my creative corner, and hope I can do the
same for you someday soon!

A Writer
#+end_quote

Extra Organizational Resources:
   •    Public Declarations of Accountability: Share these on social media to rally yourcommunity!
   •    NaNoWriMo Helpful Resources forum
   •    What should I expect at a write-in?
   •    A (Somewhat) Binding, Magical(ish) Writing Contract

* Session 6: Find, Schedule, and Manage Your Time
(So you can write as much as possible)

Get started with: What’s the best NaNoWriMo writing schedule for you?

                       Take our “What’s the best writing schedule for                                   you?” quiz to find out!

Not sure how to build time for NaNoWriMo into your life? We've got you covered. Take our quiz
for suggestions on how to structure your writing time, what kind of writing goals you should set,
and methods to get you writing. Or, explore our suggestions below.

1. If Time Is Your Friend…

   For one reason or another, you're able to dedicate a lot of time to
   your creative writing right now. That's awesome! But fair warning:
   this can be a double-edged sword. Your first step is to structure that time.

   Reserve two blocks of focused writing time during your day: i.e.,
   an hour in the morning and an hour in the evening, or two hours in
   the morning and an hour in the evening. Choose blocks of time
   during which you know it's unlikely for you to be interrupted and
   likely for you to be able to focus.

   If you use a calendar app, block out your proposed writing times
   now. If you don't use a calendar app, set a recurring alarm for the start of both your writing blocks.

   - The Structure: Two blocks of uninterrupted writing time a day.
   - Try This: Use the Pomodoro technique: 25 minutes of writing, followed by a 5-minute break, then repeat.
   - The Goal: 1,667 words a day if you're writing 50,000 words.

2. If Weekends Are for Writing…

   Your weekday hours are claimed by work, school, or related tasks.
   How to make this writing thing work? Find smaller chunks of time to
   write from Monday to Friday, and then stretch into more writing
   time on the weekends. (Did you know that the weekend was only
   formally adopted in the US in 1940? Thanks, unions and the Fair Labor Standards Act of 1938!)

   Fit in a few writing bursts every weekday, then split 6 hours of
   writing over the weekend. Make Saturday an abbreviated writing
   workshop day from 9—3; or structure your Saturdays and Sundays to include 2 3-hour writing sessions, or 3 2-hour sessions.

   If you're used to lazy Sunday mornings, remember that you're only
   sacrificing them for a month so that you can push yourself creatively. You can do this!

   The Structure: 2 40-minute writing sessions every weekday, 6 hours of writing every weekend

   - The Goal: 800 words every weekday, 4,250 words every day of the
     weekend. (If you're shooting for 50,000 words.)
   - Try This: Leave a hook during your Friday writing session. Stop in the middle of a scene, or even a sentence, so that you can dive right into the thick of things when you begin again.

3. If You’re Full Speed Ahead…

It can feel daunting at first to create some room for this creative writing thing. Remember: you're
just asking for one month to push your creativity toward the top of your priorities.

How to make the most of it? You can still write 50,000 words of a novel in 30 days, but you're
going to make a few sacrifices: the most important of which is going to be the idea that your
manuscript is going to be ready for readers at the end of the month. For you, this month is about
spitting out the raw material for a book. You are a words and ideas machine. This month only,
you are viewing every blank page through rose-colored glasses.

You will accomplish more writing than you ever have before. You will end the month with
concrete ideas, scenes, and characters, ready for structure and editing. You will unlock a new
ability to forge through your weakest creative days. Full speed ahead.

   - The Structure: 2 30-minute writing sessions every day.
   - The Preliminary Goal: 840 words for every 30-minute writing session if you're shooting for 50,000 words.
   - Try This: If you're feeling particularly tempted to read back over your writing and are writing on a computer, match your font color to the background color (turn your font white, for example!).
   -  Focus on the goal: a writing habit, and a mound of words and ideas for you to shape at your leisure after this month.

4. If You’re Writing in the Margins…

   You are making things work, even with a boatload of
   responsibilities on your shoulders. And this month, you're planning on doing something for your creative self. We're here to help you do it.

   This month is all about maximizing any time available to you.
   Fifteen of the minutes you have for lunch. The ten minutes while
   the kids are in the bath. Those last fifteen minutes before you
   fall asleep. Now, you may be tempted by the following thoughts:

   "This isn't enough time to write anything." Or "There's no point in
   jotting down two sentences right now." Or even "Anything I write will be too disjointed and slapdash to be of value."

   Don't invest your five minutes in indulging these whispers! Put
   words on paper instead. The goal is 50,000 words in 30 days: not
   50,000 perfect words, not even 50,000 readable words. Fifty
   thousand words of practicing your voice. Some of it will be
   understandably bad. Some of it will be shockingly good. It will be worth doing.

   - The Structure: No amount of time is too small. 15 minutes every night, and then any spare time you can cobble together.
   - The Preliminary Goal: 30 minutes of writing a day. Try This: Get
     a small notebook to carry in your pocket, or if you have a
     capable phone, write using an app. Jot down any stray sentence or
     piece of dialogue as prompts for the next time you have five or ten minutes to write. Focus on progress instead of perfection!

                            Writing Progress Sticker Calendar
If you need a little extra incentive to reach your writing goals, use our handy-dandy sticker
calendar! Plan out your writing goals by day, assign stickers to different goal landmarks, and
keep on track with your writing! Download the full-sized image here.

Extra Time Management Resources:
  •    Webcast: Find the Time to Write
  •    Blog post: Do you rule your habits, or do they rule you?
  •    Blog post: How to create a morning writing routine
  •    NaNoWordSprints on Twitter
                                                                                         52

Congratulations, Writer!

Yay! You did it! You’ve dotted your i’s, crossed your t’s, and completed our NaNo Prep
101 Workshop. We hope you’re feeling ready to start writing your next masterpiece!

Celebrate your official preparedness by downloading this certificate.


