   

    
So into our midst comes the words of a letter written very long ago by
someone who may not be Paul but sees himself as a Paul-like figure
writing to someone who is a Timothy-llike figure. This is important
because this identification is not plagiarism but puts the Apostle
Paul in great essuggest the writer esteems Paul and his potigiege
protege Timothy in great esteem. He, too, has experienced hardship,
arrest and imprisonment for the sake of the Gospel. At the end of his
life, he wants to be certain his own protege   Paul telling Timothy a story I am certain
Timothy knows by heart. "At my first defense..." Surely there have
been others. "At mmy first defense when I wasn't much older than you
are now, when I only had a little experience as you have now." 
* Paul's first defense (when he was Timothy's age)
* Paul reiterating the assurance to Timothy to both follow his example and know the Lord rescues and saved and stands by Timothy when he adheres to the gospel.

* Imagining the story of Paul and TTimothy with different people

Identifying yourself with a historical figure can be seen as a sign of
mental illness. In the Greco-Roman era writing as someone else was
seen as a means of honoring and holding someone high in your
estimation. Recently a friendly tap came to my door. I wondered who it
was since I don't know any of my neighbors. I opened the door and a a
young woman said to me, "Oh, Grandma, I'm sorry. I have the worng
apartment." I was a bit startled. My grandchildren don't call me
"Grandma" and this woman was not my grandchild. But I knew she was
calling me by a name which imferrred great respect and gentleness. 

Our writer today has taken on the persona of Paul to mentor a much
younger person. He has used the Apostle's language to decribe his
experiences and to speak of his death. His retelling here is
passionate and personal.
