Traveling On: A Ronnie Camberwell and Captain Star Runner Adventure

* Chapter 1

We had planned to go back to the Northern Frontier. We had friends
there and we were tired of the war. We were tired of alien cultures we
did not fully understand and we were definitely tired of being pawns
of those cultures and their war. Nevertheless, when the time came to
jump into Mother Space and run toward what we thought of as home, we
hesitated. Going back meant getting into new scrapes and learning what
had changed since we had been there. Communication was slow and we
wondered how out-of-date we were. It really boiled down to this:
Should we stay with the devil we knew or run to the devil we used to
know? We told ourselves we just wanted to poke around a little more
until we went back. We told ourselves this would be quick. It would
satisfy our curiosity and then we would be off. Maybe in the interim
we could get more information so we wouldn't have so much of a culture
shock when we got back to the Northern Frontier. Whatever we told
ourselves, what actually happened was very different than what we
imagined.

I am Ronnie Camberwell. I have been a police detective, a wife, a
private investigator and most recently, I worked for the War Crimes
Investigation Unit of the Tigerfoo Confederacy military. Right now I
am just a human being and citizen of the galaxy. I am traveling with
Captain Star Runner, an independent Pantheran who likes to classify
themself as an independent entrepreneur but is most often a pirate and
a smuggler for hire. This unlikely pairing may sound strange, but we
often make it work. Being ungendered Star lacks any sexual drive but
finds sex fascinating. I self identify as lesbian and I have a roving
eye. Yet when we are at home, we are satisfied with one another. Our
marriage didn't work out, but our partnership, with all its ups and
downs, seems to be enduring.

So that was the state of things when Star finally said, "I need to
tell Ride where we are going."

Written on <2020-01-01 Wed 17:32>
On our last mission we had gone to the home world of the Union of the White Bear. fortunaely or unfortunately, the spacecraft we were using to get through the jump gate triggered an explosion. The spacecraft and the jump gate were destroyed but due to some quick thinking on Star’s part, all the people on board and a robot were saved. When we checked the home world, we found the world abandoned--at least its major cities seemed in poor repair.

"I am thinking," Captain Star Runner as I was eating my breakfast on the command deck of their ride, "that we should go there before we leave this region of space."

"Why?" I asked. "the’s nothing there."

"Ne people there," Star agreed, "but maybe there are artifacts. I think I could get a good price for them."

Star is motivated by profit. This sounds like it would make them money grubbing and quite disagreeable but it turns out to be quite charming most of the time. It also means I never want for anything. The legacy they bestowed on me after our marriage was dissolved was amazing. I don’t think Star any real financial pinch either. I also knew that Star had a hefty portfolio. They always acted as if they were one successful mission away from starvation, but that was certainly not the case.    
"So what are you thinking?" I asked. "We just pop down and grab stuff?"

"Somewhing like that," Star said.

"I can think of a lot of things that could wrong in this scenario," I said. "Can you? I am guessing your AI can, too."

Star is connected to their spacecraft via an artificial intelligence. Basically they share brain space with some of Star’s brain being contained in AI storage and the AI controlling Star’s biobbogical functions. Star is designed, literally, to always be connected to their spacecraft and piot it.

"Well," Star admitted. "There are a number of red flags raised by my
AI."

I doubted this was literally true, but Star prided themself on
learning my vernacular. There was a warning for certain though and
that is what counted.

"So do we go there or not?" I asked.

"We go," Star said. "There is time to discuss all this.

* Chapter 2 

But we didn't discuss it. We talked about everything else and spent
time together. It had been a long time. Perhaps we were more suited to
each other now. Perhaps we had both grown in our ideas of what
compatible was. Perhaps it was just good to be together without a
crisis and without anybody else around. Whatever the reason, we were
in normal space around the White Bear home world before we thought
about making a plan.

Not being a research spacecraft, I wondered what sort of information
Captain Star Runner could gather. They didn't have to. The Fungusians
who had been with us when we jumped into this star system had a
research vessel and several more had joined them. They had salvaged
the Followers of the Stars ship. Their information had been sent to
Star's AI. We didn't learn all this until we arrived. Why? Because
STar hadn't asked the AI. This particular AI kept information rather
close to the vest and Star had not yet worked out how to have a more
open conversation with it.

This actually was a safeguard for Star. A previous AI had been
compromised with very serious results. Since then, the Fungusian
Network who handled all of Star's AI concerns had been very careful in
its constructs to make it very very hard for this to happen again.
Unfortunately, this meant the link between them was less intense in
some ways. I liked it because I didn't always feel I was in a
threesome. The AI pretty much stayed in the background, feeding Star
information and organizing their own memories. At some very deep
level, the AI and Star were one entity since the data storage was
integrated. But at some other very deep level, Star was Star and the
AI was the AI. As I said, I liked it because I was never making love
to the AI.

Written on<2020-01-02 Thu 15:48>


* Chapter 3

It would have been impossible for for the two of us to do what we did
without the Fungusians. Two research vessels were in orbit around the
White Bear Home World. It was only on our last adventure that I had
learned the Fungusians had research vessels. They were supplied by the
Featherote Charm. It was fitting that the Fungusians, Star and their
spacecraft, designed and built by the Featherote Charm, were here.

Many millennia ago the White Bear had taken some intelligent species
and enhanced them for specific purposes. The Featherote made
spaceworthy craft; the Fungusians worked on data networks and amassing
simply enormous amounts of data, correlating it and synthesizing it;
the Pantherans were administrators and biologists. The Trololu made
military hardware and were computer scientists and physicists. The
Trololu were destroyed in a rebellion. Now these "children" of the
White Bear were here, trying to find out what had happened to them.

The Fungusians do not deal with anyone face to face. Their individual
lifespans are far too short for that. Instead they communicate with
data. Star's AI and the contact point for the two Fungusian vessels
kept up a steady stream of data for some time. Finally the AI said to
us--we were curled up together in the ride's lounge--"I have a lot of
data to give each of you, but the Fungusians would like it very much
if we landed on the planet and you two could walk around so they could
get a better look. They have sent for a number of mobile units, but
they have not arrived yet. They were unable to retain the services of
Mr. Robot from the Followers of the Stars because HQ wanted to analyze
the robotics and store the data before any degradation or harm came to
the unit."

"Have the Fungusians determined if it is safe to go down there?" I
asked.

"They have detected no life signs," the AI said.

"Toxic air, unsafe structures, anything growing?" I asked.

Ride was silent.

Star began washing first one paw and then another, their pink tongue
going in and out of their pink mouth. I never knew if Star was
actually washing or whether the activity passed the time or if it was
a nervous or comforting action. I got up and made a cup of tea. The
Fungusians had stocked the ride with my favorite ones. I knew they
knew a lot about me--everything that Star knew about me and then some.
At first I found this extremely creepy, but when it was finding
clothes that fit,, a cabin that was decorated precisely as I would
have done it or would have liked to think I would have done it, and a
myriad other small things, being this well-known had its perks.

"There is life on the planet," Ride finally said. "By life signs I
meant no White Bear or other known sentient race. The Fungusians
cannot attest to the safety of either the fauna or the flora. Air
samples are in acceptable ranges. The presence of the flora and fauna
may introduce pollens and other allergens. They are confident they can
quickly synthesize any antidote you may require. I also have access to
many chemicals which can be combined to produce antidotes."

"Have they suggested a landing site?" Star asked aloud to include me
in the discussion.

"Yes."

Ride displayed a three-dimensional picture in the middle of the
Lounge.

"The Fungusians believe this was a spaceport once. Its proximity to a
city makes an excellent choice for landing. With a hover sled you
could reach the city quickly while also surveying the local area."

"What about weapons?" I asked, "in case something is not pleased by
our arrival."

"There is a suitable armory locked in the cargo deck," Ride said. "We
can discuss what you will need to take."

I was surprised. Star had never carried weapons of any kind before.

"Are you armed, Ride?" I asked.

"Yes, though not extensively," Ride said. "we thought it best since
this region of space has many hostile combatants."

I did not inquire who "we" were. It didn't really matter. How times
had changed!

1789 words
Written on        <2020-01-03 Fri 19:56>
