

* Note From Their Agent
  :PROPERTIES:
  :CUSTOM_ID: note-from-their-agent
  :END:

I represent Detective Ronnie Camberwell and Captain Star Runner as they
endeavor to get their adventures published in the Coalition. Their
friend, the Czarina, has been extremely helpful and has offered to see
if their collected works can be published outside of the Coalition since
I have run into many barriers trying to get them published here. I am
sol-based. Captain Star Runner's writings and any writing which
mentioned them, which is to say all of Ronnie's writings, have run into
legal challenges from the Pantheran government. Since Captain Star
Runner's name remains on the termination list and their termination date
is years past due, that government insists I cannot claim Captain Star
Runner is both alive and in good standing inside of the Coalition. Such
individuals are prohibited by Coalition law to profit from their
publications and as we all know, Captain Star Runner is profit-driven.

I mention all of this since both Captain Star Runner in their works and
Ronnie in hers mention previous adventures which have not yet been
published and so I have adapted and modified their works to give you,
the reader, a better picture of previous events which, especially in
this adventure, play such an important role in the story. Further, I
hope to generate interest in these previous adventures such that a
publisher, even outside of the Coalition, may find a way to make their
story in its entirety available to the Coalition public as well as their
readers on the frontiers and beyond.

* Opening Image One  
  :PROPERTIES:
  :CUSTOM_ID: opening-image
  :END:

I recited the Oath on auto pilot. I had spent the last ten cycles
memorizing it, working on my pronunciation and pacing. Trust me.
Tigerfoo is not easy for a human to articulate. In fact, many emphasis
sounds are impossible. My friends tell me I speak with no inflection at
all. During the oath, I focused on how to place my hands. I had not
practiced this and with only two arms, my placement lacked the
intertwining of paw and fist. I did what I could and came back to real
time just as the final growl exploded around me. No way could I make
that sound so I stood mute. No matter. My tutor had assured me, no, not
assured me, admonished me, that no matter how badly I performed
oath-taking, I was bound by it all the same.

Hey, I am Ronnie Camberwell, a human from the Pharaoh Star System which
is some big huge number of light years from here. Through a lot of
adventures and circumstances too numerous to mention here I found myself
in the Tigerfoo Confederacy in the middle of a space war with the People
of the Rainbow Sky. They are humanoid like me which is a complication
that will come up later in this narrative. Because I have a police and
private investigator background, the Tigrfoo thought that being a War
Crimes Investigator might be a good fit for me. I signed on and took the
class. And here I am, graduating with high honors and going to the
classroom where our instructor and class advisor will hand out our
assignments. The room buzzes with excitement, cheers and squeals of joy
from both the male and female Tigerfoo.

Everyone around me receives their assignment. My friends, all tops in
our class, has received real plums.

Finally our advisor calls for silence. "You have your orders," he says.
"Now get packed and report for your embarcation points. We have a new
class coming in and we need your dens vacated immediately. That is all."

And with that, everyone else dashed out of the room. I was alone with
the class advisor and with no assignment.

"Sir," I said.

What was going on? Very shortly, I would have no place to stay and with
no assignment, I wondered what would happen next.

"Oh, Camberwell," the class advisor said, not looking up from his
tablet. "You are to report to the Director's Office. She's waiting for
you."

And that was it. I was dismissed as if I was some sort of servant, an
after thought, no longer the class advisor's concern.

And in a way, he was right. I was no longer his concern. I was a
graduate. Admittedly, I was a graduate with no assignment and no where
to go except the Director's Office.

I hurried down the corridor. /init.el


1The Middle Wizard rode along the Natchez Trace. It was cold for
October in the south. He had put on an extra cloak, but his feet were
cold in his custom boots. (OK. This is Ruand and he does not have
custom boots. The Tigerfoo do not wear clothes. Get it together!) Yes,
the Tigerfoo was cold. He knew Ruand, the star Child who he had
employed as a servant many years ago was very cold having no fur to
keep him warm. Ruand was bundled up in every piece of clothing he
owned or so it appeared to the Middle Wizard. (The Tigerfoo would not
be riding a horse either.) The Middle Wizard gritted his teeth every
time the wagon jolted in the ruts along the NAtchez Trace. The horses
blew and stamped, making slow progress. Sometimes the Middle Wizard
thought he should not have hired the wagon but should have just walked
the several hundred miles. Another jolt. His head ached. He was
drinking more than ever, more than he should, but there seemed no help
for it. Another jolt. Another pain in his head. He swayed on the seat
and almost pitched over. He had to stop this drinking but how? He
wished someone with a title of wizard could actually perform magic. He
could cure himself of his drinking habit and get his life back on
track. He thoughts about the rumors.

Digging through the stacks, he had come across a box with a lot of
papers in it, papers that were crumbling with age. They seemed to be
notes about spells. He had wanted to take the box, but he knew the
archivist would notice. Instead he carefully went through everything
and there was a flimsy. What was a flimsy doing here in the Middle
Lands, here on Marling far from the European capitals and east coast
cities? He looked at it. There was no telling how old it was. It had
been around. There were creases and crumpled corners. The thing was,
he could not tell what it was about. It was just a string of numbers.

There had been talk. There was always talk that there was buried
treasure in the West. He had asked about it as he and William made
their way across the northern part of the country. The Star Children
had been vague, acknowledging the rumors, each giving a different
answer where the treasure was. They had always sketched some symbols
in the dirt with a branch. The treasure was here.

Now Middle Wizard stared at the flimsy. Those same numbers appear at
the top of the sheet, going from right to left. Each group had given
him a different number. They were jotted down in his notebooks safely
stowed at the family farm back East. He could not recall any of them
with any accuracy, but looking at the numbers going across the flimsy,
he thought he could be certain that these were some of the numbers he
was given.

Carefully, Middle Wizard looked around. The archivist was no longer
nearby. He slipped the flimsy into his pouch. With luck, no one would
suspect or even find his secret compartment. 

He put the box back on the shelf and left the library. It was time for
him to return east with his reports of corruption and his suspicions
and concerns about Wiljam. Wiljam was duplicitous. There was no
question about that. The question was, what to do with him? Proving
wrongdoing in a court of law and convincing others that a war hero was
a spy was a very very tough business.

So Middle Wizard had tied up some loose ends and started down the Big
River. But the drinking had gotten worse and now here he was making
his slow and painful way along the Natchez Trace with Ruand by his
side.

Ruand has seemed very on edge. When questioned, he confessed to seeing
a shadowy figure following them. Middle Wizard was skeptical. The
description Ruand gave him made no sense. This was a dark Star Child. 

Middle Wizard had been all over the continent. He had read widely.
There were no Dark Children in reality. They only appeared in ancient
legends. Admittedly, a kernel of truth was sometimes contained in
these legends, but a Dark Child stalking him sounded fanciful at best.
He suspected Ruand was seeing something, but not a Dark Child. Maybe
someone was following him. Maybe even Wiljam had sent someone to
follow him. A Star Child could present themself as a Dark Child to
spook someone like Ruand. That must be it. It was annoying, perhaps
dangerous, but Middle Wizard was certain he could defend himself.

They stopped for the night at a sorry stand. The food was barely
edible. The bunkhouse was barely heated. Middle Wizard curled up for
the night, hoping he would feel better in the morning. Even the
stand's wife had the worst drink ever. He was sure it might even not
be drink at all it  tasted so foul. 

And then the pains came. He could not lie still. He went outside,
hoping the bracing air would clear his head and settle his stomach. He
called on the woman to give him something hot to drink, to eat,
anything to stop the pounding in his head and the roiling in his
stomach. She ignored him. And then there was another pain in a
different part of his body. His chest was on fire"I have been shot,"
Middle Wizard cried. "Help! I have been shot."

No one came. The forest around him was quiet. And then another shot
but Middle Wizard did not cry out. He could not. He was nearly dead.
    
* Opening Image Two
* Theme Stated
  :PROPERTIES:
  :CUSTOM_ID: theme-stated
  :END:

"You Are late," the receptionist said. He did not even look away from his
screen.

"I just got word the Director wanted to see me," I said a bit
defensively. "The class advisor just told me after everyone else
received their assignments and were dismissed." Yes, I just threw the
class advisor under the transport, but then he was not my advisor
anymore and his behavior toward me was certainly dismissive.

"Go inCome here, Ronnie," the Director called from her office. "You were
supposed to be told before the assignments were handed out. I am sorry.
It means we will have to hurry. Your ship is due to blast off in less
than an hour."

Surprised, but relieved to know I had somewhere to go, I hurried through
the doorway.

The Director was standing behind her desk. I stoood, too. Besides, the
chairs did not fit me. Tigerfoo are taller, wider and differently shaped
from humans. Sitting on their chairs required balance and is more like
sitting on a giant's chair than a comfortable, relaxing experience.

The Director is an old Tigerfoo with many scars. She is frail and of
small stature. Nvertheless, she invokes fear in us all.

"Please close the door," she said.

Her manner was not imperious. It was gentle. I had never seen her this
way and the use of my given name surprised me. Although she had made
some concessions toward my humanity, I sensed it was more because she
had to rather than that she wanted to. I always thought she tolerated me
more than embraced me. What was going on here? She had almost apologized
for my class advisor's slight and my abbreviated time table. I was not
worried about the time. I was already packed. I did not have much and
being prepared had seemed the right thing. Besides, Tigerfoo partying
the night before gave me time. Their drinks and dancing did not appeal
to me in the least. I had beeen invited, of course, but that was only
for form's sake. The highlight of the evening would have been sexual and
public in nature. The Tigerfoo lacked any taboos in this area and
coupling in this way was as natural as dancing or eating. I preferred my
sexual encouners to be more meaningful and definitely private. To set
the record straight, I am not an alienafobe. I have coupled with aliens
before--one alien--but I have a relationship with them. But I digress
fom my meeting with the Director which was how this whole adventure
began.

I closed the door and stood before her.

"You have been assigned to find a treasure map," the Director said with
a straight face. Her ears remained still. Her wiskers did not tremble.

"What?" I asked flexively. "I do not understand."

"You are to find a document, or set up documents, or holograms or
whatever they are which lead to a treasure of some sort. I do not know
the nature of this treasure, but you are to find it." The Director said.
Was her tone ironic or dismissive or was she just trying to say this
with a straight face? Was this a joke?

"You are kidding me, right?" I said. Being blunt was one of my
trademarks. Right now seemed a good time to employ it.

"No, not at all. You have been assigned to Grand Master Awk of the Magic
Lands. You are to travel there. It Is a long way from here and your ship
leaves--" she consulted a wrist unit. "In as much time as it will take
for you to get to the spaceport. Your things are already on board."

"But," I began to protest.

"You have your orders, Ronnie. Here is all the information I have." She
handed me a secure memory card. "Remember, this is your assignment. You
took an oath to serve the Tigerfoo Confederacy. I expect you to carry
out your orders and to perform your duty with courage and honor. Now
run."

And that was it. I was dismissed and still with no idea where I was
going and why.

Nevertheless, I ran. Because I had sworn and oath and I was determined
to carry out my orders with courage and honor.

(I keep thinking of this as a movie which is not a bad thing but it will
never get made so it is better to write this as a novel. If it were a
movie, I think it would be stronger for Ronnie's links to pick up the
message to the Director's office before any assignments are given out
and then be dismissed by the receptionist as she picks up the secure
memory card. There can be a holo message from the Director about her
duty, etc. Putting Ronnie at arm's length will both puzzle and confuse
her. The next scene is her going through the spaceport and the
transports becoming less desireable. Finally she will arrive at the
commercial section and then finally to the farthest laarea wHere the
Prosperous Merchant is preparing for blast off. She will not only be out
of breath, but she will have to climb the ladder into the ship itself.
This will be arduous and she will collapse on the deck just as the door
closes. OK. I can do. I just don't know how to write a script. And why
not write it as a script? We read Shakespeare? That Is not a novel but a
play. Of course, I will not bother to do this rewrite right now it is just a
thought for the future.)

* Setup
  :PROPERTIES:
  :CUSTOM_ID: setup
  :END:

My linx directed me through the spaceport or else I would have never
made it. They are a complex set of wet ware which get updated by the
Fungusian Network. Don't ask me h. I am many light years away from them
but periodically I am notified of an update and security enhancements
and that is that. Later, when I had time, I wondered what they would
think of my assignment. And then I decided that was silly. The Fungusian
Network would be absolutely thrilled. Their mission was to collect
information and when I went some place new or some place no one had been
for a while, their databases were updated. What confidential data they
collected they held in confidence within the network. As their name
implies, they are a fungus. Individual life spans are only a few days.
You cannot interrogate individuals. You can communicate with the network
as a whole though your communiques often are signed with an individual
name. I am certain that is only for my benefit, for me to think I am
speaking with an individual.

In any event, I followed the map laid out for me in virtual reality.

First I passed the passenger liners, then the personal yachts. This was
followed by commercial freighters from a variety of freight companies.
Finally I came to the low rent district of the spaceport. I needed to
pay attention to the ground over which I was running. It was not very
well maintained. Although the Tigerfoo pride themselves on top of the
line facilities, even they have financial and interest limits. I was
flying a commercial vessel all right, but nothing at all fancy. If I had
had time then, I would have wondered about this. I am, after all,
military personnel. I was not traveling on a military transport. Someone
had bought me the cheapest ticket possible.

Finally, thfreighter came into view. If I hadn't had to run so far, now
I was gasping for breath and my legs ached though I was in good shape, I
would have been frightened. It was what anyone might refer to as a rust
bucket. It didn't even have a ramp up to its hatch. It had a ladder.
Fortunately, the rungs were not so far apart that I couldn't reach.
Clearly this was not a Tigerfoo freighter. When I finally pulled myself
through the hatch, it clanged shut behind me. I collapsed onto the deck,
barely looking around me.

"Prepare for blast off."

I lifted my head. I had no idea where to go to strap in. I just wanted
to stretch out on the deck and catch my breath, maybe even take a nap.

Fortunately, a cargo handler pulled me onto my feet and half dragged me
to a blast chair. They strapped me in and we were climbing through the
atmosphere before I could make any sense of my environment.

The cargo handler was nearby. I saw immediately that they were a Rabbit
Person. That made sense. The Rabbit People are known for their
commercial enterprises throughout this sector of space. They are also
known for having spaceworthy freighters that lack any amenities. I had a
barebones voyage ahead of me.

Various announcements came over the loudspeaker system onboard. They
were routine. We were traveling to our jump point. Obviously this
freighter did not have any capability of its own. I wondered how long
our journey would be.

My links immediately gave me the answer. I was both startled and a
little frightened.

I don't like space travel. I like to be on a planet. Even though I grew
up on a world with a toxic atmosphere, I had complete confidence in it.
By contrast, traveling in what amounts to a small tin can in the vacuum
of space unnerves me. Furthermore, we would jump into hyperspace, a bend
in the space-time continuum that would bring us far from our entry point
in normal space. If something went wrong there, you were just lost and
no one would ever find you. You would just die. Yet people jumped in and
out of hyperspace every day with little thought of the consequences of
failure. Failures, to be honest, are rare. I traveled for some time with
a star runner, a specially engineered Pantheran who knew instinctively,
there is no other word for it, how to get in in out of hyperspace. They
called it Mother Space and spoke of entry points and exit points the way
I speak of doors. To them, there is no difference between a door and a
point into or out of Mother Space. They don't need jump gates.

But the Rabbit People do and so I was traveling away from the planet
toward a jump gate far out in the star system.

When the all clear sounded, I got myself up and off the couch. I could
feel the engines thrum underneath my feet. I looked around. The cargo
handler who had helped me was nowhere to be seen. But another literal
ladder was visible which only went up. I figured that was where the
handler had gone and where I needed to go. I was just grateful there had
been a couch and someone who could quickly strap me in right near the
door. I didn't look in the direction of the door. There lay madness. I
hoped I would not have to visit this part of the ship until I arrived at
my destination, where ever that was.

Several ladders later I finally found the command station. I know fancy
passenger spaceships call it the bridge, but there was nothing majestic
about this area. It was just a lot of screens and a few people stuffed
into chairs looking at them.

"Hello," I said, sticking with Tigerfoo. I figured someone here must
know that language if they were in a Tigerfoo star system.

Someone did, not the captain, but someone.

"I'll get the captain," this one said and hopped away.

I forget what the Rabbit People call themselves. It's the name Captain
Star Runner uses and that is good enough for me. It's their ears and
teeth mostly and, yes, the way they walk. I've never seen a real rabbit,
just read about them in books. Mrs. Parge was fond of a book called
Peter Rabbit. It was a very old story with funny clothes and something
called a farm though I have never seen one. Why animals were wearing
clothing always struck me as peculiar. The Tigerfoo wore no cloting and
neither did the Rabbit People or Captain Star Runner, the only Pantheran
I knew personally. I wear clothes, but then my skin does not provide any
useful warmth and in some environments can lead to serious burning or
freezing. Besides, it's a convention aI am used to. The Tigerfoo
contented themselves with being amused when I asked about a uniform.
They don't have them.

Ever practical, they have a vest in which they carry all necessary
items. I was wearing one right now. Where they had procured it was a
mystery to me. Where I would procure another is another mystery right
now.

But that was all I came up with before the Rabbit People captain came
into the command center and welcomed me aboard.

"Your cabin is prepared," they told me. "You will be summoned for meals.
Follow all my directions."

And that was it. I was shown to yet another ladder and up I went several
levels more until I saw a door which had a sign in several languages.
"Guest accomorodations."

I opened the door hesitantly. I would be in this space a very long time.

It could have been worse. It could have been much worse, but as it was,
it was very sparse and sort of clean.

There was a blast off couch which doubled as a bed and a sofa. There was
a spaceship lavatory which could accomodate me more or less and there
was a shelf which functioned as a desk. It had a screen. There was a
closet I could lock for my valuables or clothes or whatever else I
wanted to put into it. My trunk took up most of the floor space.

I opened it. All my things appeared to be there along with a few
others.. These had been placed there by the Director's order a note
said.

(I have no idea what this might be but in case I need to have something
here I have the place to insert them. Maybe a weapon?)

Happily, the desk unit had a secure reader. That looked new. I wondered
if the School for the Investigation of War Crimes had inserted it. The
Tigerfoo military could come aboard all spaceships. When I inserted my
card, I was certain. Their logo popped up and proclaimed the reader safe
for use. My links comfirmed this as well. My links also connected
themselves to the Prosperous Merchant's systems and performed a secure
dump which was transmitted to the Fungusian Network.. The Prosperous
Merchant would never know this had happened.

After my card was inserted, the unit released it. It no longer carried
my orders or anything else the Director' had included. My links updated
and now I could peroose the information I was given at my leisure.

And leisure it would be. Transit time to my destination was many weeks
out.

Little changed during my transit. The days fell into a perdictable
pattern. I exercised and researched. The card had a lot of data on it
and the spaceship itself had a very detailed and comprehensive library.
My links confirmed that the information seemed credible and that I
should have a high degree of confidence it was correct. It did not
contradict any previously known data. That gave me some confidence and I
set about learning as much as I could about the place I was going and
what I would be doing there.

** My Background
   :PROPERTIES:
   :CUSTOM_ID: my-background
   :END:

OK. I have put it off as long as I can. You'll need to know a bit about
my background for this story to make sense. I've tried to make it a
little dramatic to keep you reading to this point and there really isn't
any way else to fill you in except flatter myself that you will find
this monolog interesting.

I was a police detective in Ptolamy City. My father was the chief and I
solved crimes there in a free-wheeling city wich included the League of
Hypatian Pirates. Along the way, I met the aforementioned Captain Star
Runner, an independent contractor. I fell in love, married and then
disolved the marriage contract. Star loves space. It is their natural
habitat. I don't. I like the ground, thank you. When I returned to
Ptolemy City after one of our adventures, I took up private
investigations. This led to an unfortunate encounter, sort of, with the
Pantheran government which caused us to leave, us being Captain Star
Runner, myself and a few of our friends. Eventually, Star and I ended up
on a space station populated by a variety of aliens far from home,
beyond the reach of the Pantherans and everybody else we knew. I found
work. Star and I patched up our relationship. It worked, more or less
until it didn't.

That all fell apart when I took on an assignment to Planet X and became
involved with someone else. Star was compromised by some alien software
which inhabited their mind and separately we both found ourselves in the
Tigerfoo Confederacy in the middle of a space war. Star's software
problems got sorted and now they are working with the Tigerfoo military
against the people who subverted their software. I found myself at lose
ends, unable to go anywhere else because of the war and not wanting to
turn my back on Captain Star Runner. We may never be a monogomous pair,
but we hold each other dear though neither of us can totally fulfill the
other. Star is non-binary creature with no physiological sex, engineered
specifically to pilot spaceships. They are dependent on the AI of the
spaceship to maintain all their biological functions including
temperature, biochemical balance, and especially memory. What Star
thinks the AI interacts with. Star can converse mentally with the AI and
gain information. Thus any intimacy we have is stored in computer
databases.

Being a woman with a strong attraction to other females, I have found
life exclusively with Captain Star Runner limiting and unsatisfying both
physically and emotionally, but truth to tell, no woman has or can, I
think, take Star's place. For whatever reason, I love Captain Star
Runner and nothing and no one has ever changed that. I first saw them
prancing across the lobby of Shepheard's Hotel in Ptolemy City many
years ago. Their only clothing was a filmy scarf and they took my breath
away. That has never changed.

** My Orders
   :PROPERTIES:
   :CUSTOM_ID: my-orders
   :END:

As the Director had said, I was to find a treasure map, but now I read
that this wasn't some silly treasure map made by pirates on some long
ago island in a distant sea. A wizard--I couldn't believe I was reading
that word--a wizard was traveling along a wilderness road called the
Devil's Backbone to bring some documents back to The Tribunal of
Wizards. (I hoped I would soon learn why there was such fantastical
mumbo jumbo in these pages.) Along this road were inns referred to as
stands. They were rough frontier sorts of places lacking any modern
accomodations. At one of these stands the wizard had met his death.
Reports were conflicting about the circumstances. My orders were not to
investigate the death. I frowned at this. If it was murder or any sort
of foul play, didn't the authorities want to know? Apparently, local
authorities were very thin on the ground. Some reports suggested it was
probably suicide. The wizard had been acting strangely during the past
few months and was known to have a history of mental illness. No, I was
called in to help find the documents. The pouch in which the wizard
carried these documents was missing. The authorities did not want these
documents to fall into the wrong hands.

I sat back in my chair at the little desk, looking away from my screen.
I was reading the documents sequentially in a traditional manner.
Already my links had copied the data and was correlating it. I could
summon a miriad of reports when this task was finished. I had also seen
an icon in my lower right eye which said all the data was being
processed for the Fungusian Network dump that would occur shortly.

This may seem like an extreme breach of security. Perhaps it is. But
over the years I have come to value the work of the Network. On the
other side of hyperspace, I would receive a data download of anything
the Fungusians knew about and could share with me concerning this new
part of space. Usually their background material provided a great deal
of help in resolving the situation. The Fungusians could see patterns
and bring data together in interesting ways.

But why, I wondered, was I being sent to help in this matter. It still
made no sense and I continued to think I was being sidetracked from more
important investigations.

There was a video from the Director marked very secret and one-time
viewing. I made sure my links could record everything and played the
recording. That was against regulations, but I wanted to be certain I
would be able to go back and re-listen to the Director. My reason,
officially, would be that my understanding of Tigerfoo was incomplete.
Unofficially, of course, were my nagging doubts about this assignment.

I played the message. The Director stood in her office and looked
straightat the camera. No frils here, just the Director talking.

"By this time, Ronnie, I am sure you have many questions, most of all,
how does this assignment fit into your War Crimes Investigation
education. By this time, too, I am certain you are recording this and
although I cannot condone this behavior, I understand it. Tigerfoo is
such a difficult language for you." The Director smiled just a little.
She didn't believe that and it is not true at all. Nevertheless, she was
giving me cover and understood why whether she liked it or not. Now that
we had our stories straight, the Director continued, "Talk of a treasure
map on a backward planet must seem very far removed from what you are
trained for. But it is not. The treasure map reports to describe a
prison where victims of war crimes are being held. We want you to find
that map so we can release the prisoners and do our investigations. You
are the best person for this job. First of all, you have experience in
investigating crimes having to do with theft and possible murder. Anyone
else I have available is not trained in police work. Further, and this
is the important thing, you are humanoid. Yes, there are Tigerfoo on the
planet, but we believe the humanoid residents are the indiginous people
of this planet. The history of Marling is lost in the mists of time, but
you will fit in better with the locals and may be able to gain their
trust. There is a lot going on here. Some have even suggested the locals
are sympathetic to the People of the Rainbow Sky though Marling have
been in the Tigerfoo Confederacy for several milenia. You are being
assisted by Master Gaunt and his apprentice Tripp. These are both
Tigerfoo. Gaunt has the complete confidence of Grand Master Awk. Tripp
is from Marling."

Here the Director paused. In human circles, her gesture would have
conveyed squaring her shoulders and proceeding to say something
difficult. I waited. Here is comes, I thought. This is the crux of the
situation.

"We call this area of space the Magic Lands for a reason," the Director
said. "There have always been rumors that magic exists, or existed, on
these planets. As you know, magic is often a word substituted for
science we do not understand. The Tribunal of Wizards, officially,
insists magic is real and that they can perform it. I don't know if this
is true. If it is, it is a very low intensity magic. We, of course, have
children's stories about wizards and magic, but we think it is just
that, a story. Officially, we tolerate the view that magic is real in
this part of space, but unofficially, we just think it is bunk.

"I've arranged a meeting for you with Grand Master Awk. He's the chief
government official for this part of space. He is quite old and there
are rumors some of the younger wizards, a nobility of sorts, want to
replace him. Senior Master Roop is the leader of that group.. We don't
know a lot about him and we would appreciate your input.

"I have arranged for you to be dropped off at the La Grange Point
nearest Magic City. A shuttle will be waiting for you. You will have an
audience," another Tigerfoo shrug, "with Grand Master Awk and his
associates. Don't take any guff from him. You are regular Tigerfoo
military now on special assignment. He has ceeded authority to you in
the matter of the Treasure Map Inquiry. Don't ever forget that. At the
same time, on't exceed your authority. You are no longer an independent
actor here, Ronnie, you represent the Confederacy and all of us. Find
that map so you can get back here and go to work properly.

"And, Ronnie, successful completion of this mission will not affect your
promotion track. In fact, it mayh enhance it."

The video ended and the security card popped out of the secure
reader.Much background material remained, but that was all.

Okay then. I wasn't losing time by going to the Magic Lands. But I had
no backup. The Director had not said it. She didn't have to. I was going
to be far far away from any military installation. I had already checked
the charts. The war was nowhere near where I was going. The MAgic Lands
were a back water of the Confederacy. From the looks of my transport,
very few spaceships ever went there. The sector was fairly
self-contained.

I wondered idly that they had not capitalized on their name. Maybe in
another place and another time they could have been a tourist attraction
with fairy castles and wizards in pointy hats leaning over caldrens. Of
course, that was my notion of magic. Maybe the Tigerfoo's ideas were
totally different. Did I need to check? Probably not. There was no way
any magic was involved in running down some missing documents. My only
worry was that I was incredibly late to the game. I wondered what steps
had been taken to recover the documents. Maybe they would already be in
Grand Master Awk's possession and I could make the long journey back. I
wondered why I had been sent for and why the delay in my getting there
didn't matter. I had best start writing down my questions and organizing
them. I would have several lists, of course, about the crime, about the
MAgic Lands, about why I had been summoned. None of this made any sense
especially since these star systems were so far away from the action and
the Director had made no reference to any strategic importance for the
sector.I would have to look up where the nearest military installation
was. I suspected it was a long long way from the Magic Lands. The war
effort was spreading the Tigerfoo military very thin. That was not
widely known among the Tigerfoo populous, but we had been briefed. The
People of the Rainbow Sky had so much more resources than we did.

I sighed. Reviewing the documents left to read on the security card
after I popped it back into its reader I realized there would be little
time for me to get anything else done. I considered. Then I decided this
long space journey might be well spent reading all the material and
being well-briefed. The MAgic Lands already sounded like something I had
never encountered before. Information always helped an investigation.
Knowing what information was key and what wasn't made the difference
between a brilliant investigator and a poor one.

** At Dinner with the Captain
   :PROPERTIES:
   :CUSTOM_ID: at-dinner-with-the-captain
   :END:

I always took my meals with the crew. Only larger vessels, I would have
sat at the captain's table, but there were only a handful of Rabbit
People to run the ship. They used temp workers at every spaceport to
help with loading and unloading cargo. Having a passenger on board just
meant a little extra money. I could basically eat what they ate with
some supplements. As you would expect, their diet was all fruits and
vegetables.

One evening the captain asked me to stay after the rest of the crew had
left. He dismissed the crew member responsible for the meal and said he
would clean up our hot drink mugs.

"Your business in the Magic Lands is no business of mine," the captain
said, getting directly to the point. "I know who you are. Word travels
fast among my kind."

I didn't know if he was speaking of spaceship captains, freighter folk
or Rabbit People. Maybe it made no difference.

"You are along way from home and without friends out here. Be careful.
There are always rumors.. I sometimes think the space lanes could not
operate at all except for rumors. But in any event, there are rumors
about the Magic Lands. I run this route because not a lot of spacefaring
folk are willing to do it.. There are too many unexplained events aboard
ship, too many lost ships, too many strange things that happen for no
reason at all. People say that area of space is haunted."

"And what do you say?" I asked. I was certainly familiar with the
superstitions of spacefaring folk. Captain Star Runner loved hearing
about them. I did not. But then, I don't like spooky stories and they
do.

"Just be careful," the captain said. "Salim and his wife are mortified
about what happened to Captain Star Runner. They had no idea they were
being used as mules to pass on that virus. They have made it known that
if there is any way to help you or them, any Rabbit Person is to do so."

He passed along his personal hyperspace contact info.

"If you need assistance and I can help, I will for the sake of the
hutch," he said.

When Captain Star Runner and I had been together on their ship, Star's
AI was infected by a virus. It caused them to act in accordance with the
wishes of the People of the Rainbow Sky. Eventually, the Tigerfoo were
able to purge the infection but not without destroying the sophisticated
AI Star was dependent on. Star had to go to the Fungusian Network to
have their situation rectified. Although I occasionally got short notes
from Star, I realy didn't know what they were doing or where they were.
I suspected Tigerfoo Intelligence and my friend Janker knew, but
otherwise I was in the dark.

I thanked the captain for his apology and for his offer of assistance.
Who knew. I might need it should things turn ugly in the Magic Lands.
Practically speaking though, the captain and his aged ship would
probably be light years away and unable to help me. Whether Salim and
his wife were unwilling patsies was still open for debate. I had been
very careful to secure all my data when I came aboard. I did not know if
the Director knew about the incident or whether I was on this particular
ship because it was just going my way. Perhaps the captain would be
notifying the People of the Rainbow Sky about it. It was just one more
thing I had to be aware of in this mission.

As I went back to my cabin, I wondered again if I was the right person
to send on this mission.

** Magic Point
   :PROPERTIES:
   :CUSTOM_ID: magic-point
   :END:

Magic Point? I culdn't believe the name of the transfer station. Nor
could I believe the condition of the station. I said farewell to the
crew of the Prosperous Merchant and made my way through grimy stone
tubes until I reach my dock. The station smelled of damp and decay. That
was probably why I developed a raging headache. Who knew what was
growing on the walls and what lurked in the puddles along my inorddantly
long trek from one dock to another. How big was this station anyway? I
should have asked. My links took a long time to reconfigure to the local
environment but when they did, they informed me that I had simply walked
from one dock to the next. They gave no explanation why it took me more
than thirty minutes to do so. I set them working on the problem and then
shivered some more. Spaceports are always cold when they are not on a
world. Too much heat always escapes into the vacuum of space. When I
thought I could no longer withstand the cold, when stamping my feet and
blowing on my hands had stopped working to keep me warm, I was finally
called to the shuttle. I was the only one embarking.

"Sorry for the delay," the pilot and only crew member said. "We got a
late start coming up to meet you."

I didn't know who "we" were, but I acknowledged his apology and strapped
myself in. I had already stowed my gear.

"That everything?" the Tigerfoo asked.

"That Is everything." I said.

"Allowances get smaller and smaller," it commented as it went through
its preflight checklist.

I affirmed its statement. I had no idea if the pilot was male or female.
In its flight suit, I couldn't observe its sexual characteristics. A
flight suit was waiting for me and I had put it on, wondering where it
cxame from. When I ran the diagnostics, they checked out. So it was
either totally fraudulent or it was a working suit.

"Off we go," the pilot said and we began the long flight toward Magic
City.

** Magic City
   :PROPERTIES:
   :CUSTOM_ID: magic-city
   :END:

The whole planet is called Magic City. This is odd since it is mostly
cultivated land and wild places. The city itself--the only city--is
called MAgic City, too. I guess you just get used to which one is which.
I never have.

* Catalyst
  :PROPERTIES:
  :CUSTOM_ID: catalyst
  :END:

My headache grew worse as we traveled toward Magic City. I found myself
pressing my hands against my face, trying to relieve the pressure I most
keenly felt in my eyes and temples. My links displayed warning messages
against my eyelids. I could not concentrate on what all the symbols
meant but clearly something was wrong. If only this trip in the shuttle
would end. The closer we came to the planet, the more pain I felt until
it totally overwhelmed me.

The next thing I knew I was laying down and the pain was gone. My links
advised me I was in a hospital bed in a hospital on Magic City. It bore
the uninspired name MAgic City General Hospital. I felt very tired and I
just wanted to lay there and listen to the quiet sound of medical
machines running. I didn't care about the introvenus drips. I just cared
that I was no longer in pain.

"I see you are awake," a voice with a definite quaver said.

I did not open my eyes. I did not respond. I did not know who this was
and what they wanted.

"I am Grand Master Awk," the voice said. "I have been closely monitoring
your condition.."

I did not respond. I was to report to Grand Master Awk and here he was.
I felt in no way able to respond appropriately.

"It seems you are a sensitive," Grand Master Awk continued. "In fact,
you have the highest sensitivity rating we have. That is very very
rare."

I did not know what this meant.

"We have you in a room with a sensitivity barrier. That is why you no
longer feel any pain. Are you able to open your eyes?" I tried that. It
worked.

"Can you speak? There is whater if you need it."

I sucked a bit on the provided straw. I said, "Junior Investigator
Ronnie Camberwell reporting for duty, Grand Master Awk." I did not feel
I could do much more.

"Very good," Grand MAster Awk said. I tried turning my head to look at
him but realized I was immobilized.

"Lie still," he said. "Your body is still recovering. We observed you
have some sort of internal link system which is helping you as much as
it can. We are not familiar with your specific humanoid configuration,
but we have some experience with humanoids as they populate seeral
habitable planets in our sector. With rest we expect you to make a full
recovery. In the meantime, I will leave you for now and come again
tomorrow to tell you about your assignment. We expect that on Marling,
you will not be so sensitive."

"Sensitive to what, sir?" I asked. Maybe it was the headache, but I did
not understand.

Grand Master Awk made a sound which I interpreted as a sigh. "You know
this area of space is called the MAgic Lands. We believe that a long
time ago there were powerful magicians living here who wove powerful
spells. We are not sure what sort of magic was practiced or what the
spells do. We do know that certain individuals are sensitive to the
magic. They can feel it. That is what we think is going on with your
system. You can feel the magic very strongly and it is upsetting your
system. We can shield you from the magic in this room. We are currently
making sure we can transport you back to the shuttle and get you to your
puddle jumper in order to get you to Marling safely."

Shortly afterwards, Grand Master Awk left the room to leave me with all
my questions.

I know the old saying about magic and science. It's magic until you
understand it. The Tigerfoo are very accomplished scientists so I
wondered what was going on. I also wondered at my links. What were they
doing?

I formed a general query and hope for a coherent response. The Fungusian
Network had developed a very detailed profile of my biological system
and could suggest remedies and problems readily.

I must have drifted off for a good while. When I awoke, I was still
alone but my links had been working on my query. Their results were
surprising and yes, very troubling.

** Background
   :PROPERTIES:
   :CUSTOM_ID: background
   :END:

Anyway, the information the Fungusian Network provided me was
astonishing.

I should tell you at this point that Star and I had visited Planet X.
Yes, I know how silly that sounds but it is true. I had received a very
lucrative contract to be a body guard for two students going to Planet X
for some archeological research. While there, we found evidence of an
ancient but mysterious civilization which predated the Tigerfoo. The
Tigerfoo claim this planet as their planet of origin, but it is
off-limits to everyone for obscure reasons which have been difficult for
the Tigerfoo to articulate. They end up saying the planet is cursed
which makes no sense at all. We were able to stay at the hotel and had
robot staff to look after us. It was creepy, of course, but we did not
have any ill effects afterwards--at least neither Star nor I had. As
Transfer Station 17 in the Turkish Empire was destroyed, I can't tell
you anything about my client since I presume she was killed in the
explosion.

1. I had been exposed to technology consistent with that known to the
   Fungusian Network which belonged to the Followers of the Stars.

2. ** As I suspected, the "magic" was most likely some sort of advanced
science my links could not identify.

2. My links were able to make some kind of measurements and when this
   information could be transmitted, it would be.

3. In the meantime, my links would try to mitigate the effects of the
   "magic" so that I might not be as incompassitated as I had been. As
   my biological system could not provide the materials, chemicals and
   such, that the links would otherwise need, their mitigation would be
   limited. Having no idea what medical supplies would be available to
   me, correctives would be limited. The links suggested a fully
   integrated system should be considered in the future. No thanks. I
   did not want to be integrated in the way Captain Star Runner was. I
   liked my biological independence

4. Finally, the biological profile of the Followers of the Stars and
   mine, although similar, varied in some important ways which could
   account for my physiological response. Beyond that, the links were
   not able to make any further determinations.

5. Finally, my links revealed the most astonishing fact. The Magic Lands
   included Planet X.

I wondered why I had not been ill on that planet. The only information,
and it was more of a supposition, was that the "magic" was not present
there. Any further thought in that direction was simply speculation.

I spent my time sleeping and thinking while I regained my strength. I
remembered that Janker, who rescued me from Transfer Station 17, had
wanted to know what I learned on Planet X for some military purpose but
I never learned what that purpose was. As a result, I decided to keep my
visit to Planet X a secret because I did not know if the Tigerfoo
military, of which I was now a part, considered that information
classified.

* Debate
  :PROPERTIES:
  :CUSTOM_ID: debate
  :END:

Grand MAster Awk returned.

"Now that you are feeling better," he said, "I want to brief you on your
assignment before you leave.

"You will be going with Master Gaunt and his apprentice, Tripp. They
will be your guides and help you interface with the civil government on
Marling. THey do not have the ratings to get all the classified material
you have. You are to follow Master Gaunt's lead while you ascertain
where the documents are and retrieve them. Although I was saddened by
the death of my colleague, I know he was suffering from depression and
had exhibited signs of addiction. His death has been classified a
suicide. Your mission is not to evaluate his death, only to find the
documents.

"And these documents," I asked. "They have been described to me as a
treasure map."

"That is what the locals call it," Grand Master Awk explained. "They
believe it will lead them to a buried treasure which would be quite
lucrative should it be recovered."

"I get the impression you don't think it is that sort of treasure," I
said.

Grand MAster Awk folded his four upper paws in a complex configuration.
He was deciding something important. He unfolded them and said, "No,
they do not lead to a conventional treasure. We believe, however, that
these documents are a map that lead to a facility. The location and
purpose of this facility has been lost and from the little information
transmitted to us, we believe this facility could be used against us if
our enemies were to take posession of it."

"Sir, you are not speaking plainly," I said. "I do not understand.
Perhaps it is my unfamiliarity with the nuances of Tigerfoo in this
sector, but you seem to imply more than you are saying."

Grand MAster Awk did that sigh gesture again., "The Director told me you
are both direct and smart," he said. "Yes, there is more to this
facility than I am saying. We believe it is technology from a lost
civilization, powerful technology, and we do not want it to fall into the
hands of the People of the Rainbow Sky. As yoou know, they are one of
the ancient races and we are afraid they will know how to use this
technology and will use it against us if they find it."

"And are they actively looking for it?" I asked. "We are a long way from
the front."

"We have heard some whispers," Grand Master Awk said. "Nothing really
specific. We are not sure how we would be able to identify a Rainboww
Sky spy."

I frowned and tried to concentrate. None of this made any sense to me.

"Grand Master Awk, I like to think I am an intelligent individual, but I
still do not see why you reached out to the War Crimes Investigation
School to have me travel all this way. The crime scene is no longer
fresh and the documents may have even gone off world by now. What is the
point of having me, who has no familiarity with your region of space,
your history and the planet of Marling to come here and to try to
investigate. I have been a police officer, home grown on a world outside
of government authorities. I have done some private investigation work
both here and far away in my home region. I am certainly not the most
qualified person to find your so-called treasure map. Maybe it is the
sensitivity you speak of, but none of this is making any sense to me at
all."

"But, Junior Investigator Ronnie Camberwell, you have been to Planet X.
You have followed the thread of evidence from the Landscape of Thorns
through to the ancient civilization of the Union of the White Bear. You
have traveled many light years with the fuchsia-colored Pantheran. That
is what qualifies you for this mission."

Despite myself, I stared open-mouthed at Grand Master Awk. "How did you
know all of that and in such detail?" I asked. "My official record does
not list any of that."

Grand Master Awk smiled at me. It was not an unfriendly smile, but I
sensed for the first time the power of this Tigerfoo. He was, after all,
the authority in this region of space. I was only a junior investigator
even though I had done all the things he had listed. I was not sure any
of them mattered much for this assignment.

"The treasure map is very ancient," Grand MAster Awk said. "Perhaps it
is more ancient than Tigerfoo itself. We do not know many of the details
of that history, just a name or a place, like Planet X and the Followers
of the Stars. But this war we are fighting is not just about modern day
aggression of one race against another. It is about that ancient history
and the destiny of many races. The Followers of the Stars were powerful
wizards. Whether their magic was real or their science was far beyond
our understanding I do not know, but I am convinced, along with the
Tribunal of Wizards, that they controlled a vast amount of power. Their
secrets have been hidden for many thousands of years. The treasure map
leads to their library and their library will hold the key for all the
races in this part of space. I want the Tigerfoo to control that
library. I want you to find it and bring its location bback to me."

In that moment I understood that Grand Master Awk wanted all that power
for himself. I did not think he was some maniacal creature. He was not a
power hungry monster. He was a very shrewd and wily operator who did not
want these ancient secrets to be shared amongst the races. Perhaps he
did not even want to share them with the rest of the Tigerfoo
Confederacy.

The old warning came to mind. Perhaps it was the Fungusian Network
itself that reached out to me:

With great power comes great responsibility.

Did Grand Master Awk have the wisdom to control the great secrets of the
Followers of the Stars? Were their secrets something these younger races
should possesss?

I thought back to that adventure from the Landscape of Thorns. A master
race had developed a number of enslaved peoples:

= the Pantherans

- the Featherote

- The Thorolu

- The Fungusians

and if I was not mistaken, the Tigerfu as well.jjjjjjjjjjjjjjjjjj I
would have to review Star's notes on their discoveries on Planet X.

Besides, the Followers of the STars had faded from history. The People
of the Rainbow Sky were making a resurgance. The Union of the White Bear
had retreated into itself and no longer interacted with the rest of the
galaxy. Distances were vast in this galaxy and even vaster between
galaxies. Hyperspace itself was vast. My journey here was a testament to
the slowness of space travel.

What I also realized is that I could not refuse to go on this quixoti
quest. I had no authority to refuse. I had no way to leave.

And then the horror of what I was being asked to do hit me. Unless I
returned with the treasure map, I could never leave. My assignment was
to find the map. Until I did, I would be always looking for it. And even
when I found it, I could not leave because I would know the location of
the treasure, whatever it might be. And knowing that, I would have to be
held close, maybe inside the library itself.

I would not be executed like I was some organized crime operative. My
imprisonment would be benign. But it would be imprisonment all the same.

And I wondered, too, if the Director knew that. Had the Tigerfoo
simplarranged for me to be shunted out of the way?

"You seem troubled," the grand master observed. "The map was found--at
least that is what our wizard on the ground said--and it must not fall
into the wrong hands. The war effort depends on that. The war effort
depends on you, Ronnie."

And he left me then. Was it as simple as that? Did the war effort depend
on me and my ability to find ancient treasure?

* Next Section whatever it is

We met our guides Ananeth and Diluca. AnIt surprised me to find that
they were brother and sister and both indigenous people. It also
surprised me how fair they were with almost white blonde hair and
watery blue eyes. They looked me over carefully.

Their Tigerfoo was passable, but I very quickly began picking up their
own language. I realized my links were compiling a database. When I
inquired, I learned I had a rudamentary dictionary already in place
from an old database the Fungusians had. The AI was quickly updating
definitions and cross referencing. Either the old database was
woefully incorrect or word meanings and pronunciations had drifted
over many thousands of years. The AI was pretty confident Anaseth and
Diluca were speaking jjjjjjjjjjjjjjjjjjjjjjjjjjjjjja language which
had evolved from that spoken by the Folloowers of the Stars. That
pleased me. Maybe the Followers hadn't altogether disappeared and more
important, maybe the documents we were looking for, if they were
written in ancient Followers of the Stars language, could be decifered
and used.

"Where do you come from?" Asaneth asked me. Her inflection was
challenging. I remained calm and did not rise to snapping back at her.
Perhaps I was misinterpreting her tone of voice.

"I call myself human," I said, knowing this was a weak response. Many
races called themselves that. "I come from a place many light years
away from here, a place which does not know of the Magic Lands, the
Tigerfoo Confederacy or the People of the Rainbow Sky."

"We do not call this place that." Asaneth spoke under her breath, but
my links translated effectively.

I wasn't confident enough to speak her language, but I did say to her,
"Then what shall I call this place?" Perhaps I gave away an advantage,
but then again, maybe I was not.


"We call this place," and here she substituted her own language,
"home. We call ourselves Star Children." Again she put it in her local
language.

"Thank you," I said. "That is helpful. I will try to learn how to
pronounce it properly."

And I did after a fashion.

Our trip included a stop at a space station, traveling to a different
continent which Tripp told us was a very sophisticated place and a
solar-powered air vehicle which transported us across a large body of
water. We had arrived in a city on the eastern seaboard of Tripp's
continent, but not her home city and took a sailing ship down a river,
ported across a mountain range on sturdy four-legged animals and then
took another boat until we arrived at a much small settlement. It was
here that we met our guides. Along the way I read as many pamflets and
fuides as I could find. I learn my understanding of wizard was all
wrong. The easiest way to explain it is to say they were regional
rulers of some sort. Our dead wizard had ruled the middle region of
the continent, much of which was unsettled by the Tigerfoo but was
populated by different groups of the Star Children. The wizards might
or might not be beholdent to a higher authority. In this case, the
eastern seaboard government had appointed our wizard to rule over this
interrior section in the hope of settling a large portion of the
Tigerfoo and extending its reach across the continent. Other forces
were trying to do the same. It was a dizzying amount of names and
geographical locations. Maps were hard to come by and they all made
different proposals for what was where. I wondered why a satelite
survey had not been used, but Gaunt explained that the local
populations, both Star Children and Tigerfoo, did not want satelites
because they considered it surveilance by more advanced planets.

So in the end here we were ready to set out on our wilderness trek to
find the place where the middle wizard died.

-----
OK. I'm describing Earth here. The folks landed in Europe and came to
North America. The Star Children are the indigenous people and more or
less the Tigerfoo are Europeans. I need to work on a variety of place
names and distinguish the settlers. As this is typically hard for me,
and I want some more exotic reasons for what is happening, I will have
to handle that in the rewrite if one happens.
-----

We set out one gray day riding with several pack animals. By now I was
used to this method of transportation and no longer felt sore. I could
ride with Anaseth and Diluca. Being different in shape, Gaunt and
Tripp found riding difficult and although their ancestors could have
run on all fours, evolution had changed that, too. They rode on the
seat of a wagon and Gaunt held the reigns. He had some experience in
this saying he had driven different animals on his home world in this
way but that they were racing stock. Tripp wanted him to show her how
that would have worked, but he said he did not have a wagon loaded
with supplies and being fair to the animals was crucial. If they
became injured or too weak they would not be able to pull the wagon.
Tripp was disappointed and found sitting on the wagon seat
uncomfortable. She often made Gaunt stop and trotted alongside the
wagon until she tired.

Dilucca showed me how to handle a pack animal and I held its lead
while I rode, taking in my surroundings and wondering at all the
people who put themselves through all this travel.

One thing I had noticed was how I was perceived by many Star Children.
They did not look me in the eye. They might be abbrasive but I sensed
a real reluctance to engage me. Anaseth and Diluca were sometimes like
that, too. I called them on it and their response surprised me.

"We have stories," Anaseth said. "They are mostly told to children to
frighten them."

"But we all know them," Diluca added.

"you look like the bad creature in those stories," Anaseth said.

"Not that my sister or I think you are one of the bad creatures,"
Diluca hastened to tell me.

The word they used for the bad creature was in the Fungusian Network's
database. It was the name the Followers of the Stars used for
themselves. So, I thought, they were dark while all of the Star
Children were light. Had the dark people enslaved the light people?
Were they two different races? The database couldn't tell me but I
wondered. That made me think I was looking for documents written by
the oagers of this planet. I didn't know why they were oagers. I just
knew they were now. I also knew how silly it would be to tell our
guides wwe were looking for oagers and their treasure. I encouraged
Anaseth and Diluca to tell us some of the stories. Gaunt thought I was
ridiculous but I took him aside and explained it would help us
understand the local culture. Tripp just turned her nose up at the
Star Children in general. She took me aside to tell me not to get too
friendly with them.

"They steal and they lie," she told me. "You can't trust any of them."

I didn't think it would be wise for me to tell her some of my best
friends were pirates. I am certain she would not understand.

It would be extremely boring for me to recount our journey to the
Grinder's Stand. I could tell you about bad creek crossings, rainy
days and stormy mights, about being hungry because we culd not start a
fire, cold because we were soaked through and on edge because we were
always loooking out for thieves. At last we reached the site of the
Middle Wizard's death.

* Break into Two
  :PROPERTIES:
  :CUSTOM_ID:`> break-into-two
  :END:

I was soon able to be strapped in aboard the shuttle back to the
Lagrange Point. I was still feeling an inordinate amount of dread. I
could not see a good outcome to my situation nor could I imagine what
life here in the Magic Lands could be like. I felt cut off from everyone
and I missed Captain Star Runner. They had a ship--Star called it their
ride--and no matter what happened to us, we could just leave. Now I
could not leave.

If you are wondering why I did not contact the Director to advise her of
these strange events, I did review the material she sent me carefully.
Grand Master Awk was my designated commander even though he was not
military but a civilian. In checking through Tigerfoo regulations, this
assignment was regular for military personnel assigned to distant
commands. Communication channels ran through hyperspace and although
faster than spaceships, they still were not quick. I could file a report
but I still had to carry out Awk's orders until they were countermanded.
I dutifully sent the Director my report since she had not given me any
other military commander to report to. I explained about my sensitivity
and Awk's argument that I would be best suited for the job. I also
outlined how I thought my assignment would be never ending. I did not
know what sort of a report it was or how it would be received. In any
event, I sent it, confirming that I had indeed arrived in the Magic
Lands and was attempting to carry out my orders. It was the best I culd
do under the circumstances.

The closer we got to the Lagrange Point, the better I felt. Clearly
there was something on Magic City that had not agreed with me. If it was
ancient magic I was not sure except that whatever it was it had a
debilitating effect on me.

When I disembarked, a young Tigerfoo was in the arrivals lounge. She
popped up as soon as she saw me and came bouncing--yes, I said
bouncing--over to me. She reminded me of that old old story Mrs. Parge
had read to me as a child. The character was called Tigger and Tigger
bounced all over the place.

"Hi, I am Tripp. You must be Junior Investigator Ronnie Camberwell."

No, not Tigger. A puppy. I almost expected Tripp to start panting like
one.

"I am pleased to meet you, Tripp." I folded my hands in a vague
simulation of a Tigerfoo greeting.

"I am so excited to have you on this mission," Tripp said. "It is my first
mission. Oh, I have been studying with Master Gaunt--Master Gaunt, he is so
wonderful--you will love him--but we have not had an actual assignment
since I became his apprentice. And to think, our assignment is on my
home planet of Marling. We will not be staying anywhere near where I
live--where my family lives--but it will be just so good to be there.
I have really missed Marling. Do you miss your home planet?"

I hoped Tripp did not talk like this all the time. Her exuberance could
get very wearing very quickly.

"Yes, I do miss my home city," I said. "But it is very far away from here
and I have gotten used to the idea I won hat be going back."

That was probably more information than I needed to give out but Tripp
struck me as one of those people who keeps asking--to be polite, of
course--wanting to know everything about you and not realizing how
invasive and nosy they are being. I am a private person and I do not like
it when people invade my privacy.

"Oh, and where would that be?" Tripp asked, leading the way out of the
arrivals lounge.

"Apprentice Tripp," I said firmly, coming to a stop and making her walk
back toward me.

"Yes, Junior Investigator," Tripp said, trying to look very serious and
failing because she looked like a puppy trying to be serious;

"I do not appreciate your inquiries and my private life is just that,
private. Until it becomes relevant to our mission," I cringed at this
formulation but Tripp was excited about our mission, "you are not to ask
personal questions."

Tripp looked abashed and then brightened. "Oh, Junior Investigator, I am
sorry. I meant no disrespect. Of course I will respect your privacy.
It's just that, well, we're both females and most of the wizards are
males and well, I just thought we could get to know each other better
because we will be on this mission together and well--"

I cut her off. "Are not we supposed to be catching our interstellar
flight soon?"

"Oh, yes, it is leaving kind of soon. I guess we had better hurry. Master
Gaunt said I should tell you to hurry so we do not miss our departure
window."

Tripp scampered off and I hurried to catch her up. This was going to be
a very long assignment even if I could wrap it up quickly and leave this
wretched region of space. Already I had concluded I did not like it.
There was the sensitivity and the events on Planet X and now there was
Tripp and her endless chatter. I had been with her less than five
minutes and I could not stand her. Perhaps there was a magic spell to
quiet chatterers. Maybe fantisizing about that would give me a better
perspective on the possibility of magic.

What was I thinking? MAgic did not exist. Advanced science did. Suppose
the Followers of the Stars had left some of their science behind when
they went wherever they went and the Tigerfoo had mis-characterized it
as magic.

I could not ponder this more becuse I needed to keep pace with my guide
who darted through the space station. Being bigger and less agile and
having luggage as well, I almost lost her in the crowds. I would
definitely have to speak with Gaunt about this. He was my commander on
this mission since Awk had officially given him that transferred
respnsibilitybut he was civilian and I was military so I was, according
to my orders, semi-independent of him and therefore somewhat equal.

"Here she is!" Tripp squealed as she stopped bouncing in front of a tall
think Tigerfoo.

"Apprentice, you have not looked behind you," Master Gaunt said. Your
responsibility was to escort Junior Investigator Ronnie Camberwell to me
and the shuttle. She is just coming onto the dock now and struggling
with her luggage. Go help her and stay close to her. We are about to
leave and unless we are all aboard, none of us can leave. It will be
another two weeks until there is another ship. Now hurry."

I saw Tripp speaking to a tall thin Tigerfoo and then come bouncing
toward me, snatching some of my luggage away from me and then bounding
away with the words, "Hurry. Master Gaunt says so."

How was I ever going to survive even the trip to Marling much less every
day thereafter.

Out of breath and certain discheveled, I arrived at the main hatch.
Gaunt did not even introcude himself but helped to get my luggage aboard
and checked in with one of the onboard stewards. The hatch was secured
and we hastily made our way to our excelleration couches. A steward
assisted me, quickly reconfiguring my straps and waste reclamation tubes
for my humanoid body. Very quickly we pulled away from the Lagrange
Point station and began boosting toward the jump gate. My links
immediately integrated with the onboard system. Yes, there was a
substantial update awaiting me and yes my updates would be sent to the
Fungusian Network. I settled back to enjoy the ride. That is a joke. I
let the update flow, knowing this part of the journey made it necessary
for me to stay strapped in. I was far enough away from Tripp that she
could not take advantage of a literally captive audience. Instead she
prattled away at Master Gaunt on one side until he shut her down. When
she tried to engage the Tigerfoo on her other side, that individual said
something quite loud and quite rude to her. Gaunt silenced them both and
our area of the spaceship became quiet. I could hear the repetative
sounds of a spaceship at work. I remembered Captain Star Runner thought
of these as a ride's lullaby. For the first time, I thought they could
be right about that.

My update process had a soothing component. I wondered how mere bytes
could do that. The answer came when I read through my release notes. I
didn't use to do this, but over time I found out I was able to monitor
the kinds of information I was being given.

For example, this update had a routine to engage my brain and stimulate
calming thoughts while under a normal pattern of stress due to spaceship
excelleration from a spaceport or blast off from a surface spaceport.
The routine could be disabled if I did not like it in a setting. It also
had a lengthy set of criteria so that it would not set\\ into effect
when I was under stress and needed my adrenolin to get me through theat
particular situation.

The Fungusians thanked me for providing them new information about the
MAgic Lands. They apologized for not having an extensive entry about
that region of space for me to review and said they had updated and
expanded my knowledge base.

The release notes concluded as usual: Bug fixes and security updates are
included.

Finally, there was a note congratulating me on my new assignment and
rank. More information about civilian supervision of military personnel
was also included.

For a space voyage, our journey to Marling would be a quick one so I
started reading about it and the Magic Lands. The regulations would have
to come later. My mind was still recovering from its ordeal and Tripp's
chatter had not helped me to find an even kihl. If her chattering ways
persisted, I would have to speak to Master Gaunt and at least threaten a
formal complaint. I definitely need my thinking time. I definitely am a
loner and all this community which the Tigerfoo so promote can get a
little wearing on me.

So what did the Fungusians know or thought they knew?

6. This was the area of space thought to be ruled, managed or otherwise
   controlled by the Followers of the Stars in ancient time.

7. The Followers of the Stars were humanoid and were genetically similar
   to Sol-based humans like me. In fact, should I want to, I could
   probably have a human-Follower child and it would grow up with no
   genetic anomalies. I could not imagine doing such a thing, but the
   Fungusians just wanted me to know how close Followers and humans
   were.

- The distinguishing difference between Followers and humans was not
  genetic, it was cultural. The Followers believed in a very
  hierarchical system of government and were class-based. Your class
  could never change. You were expected to carry out roles within the
  society. This worked because the Followers supported members at all
  levels and tested their populations regularly to make sure you were in
  the right class. If you were gifted as a space engineer but born to a
  farmer family, you were reassigned.

8.  The Fungusians speculated that the Followers of the Stars lost their
    competativeness with the other races in this part of space. They
    were being pressed by both the People of the Rainbow Sky and the
    Union of the White Bear. There may have been other races, too, but
    the Fungusians had no direct data on these people., As a result, the
    Followers moved their base of operations out of the Magic Lands. If
    Grand Master Awk's idea that I was sensitive to ancient magic held,
    it meant the Followers had abandoned the Magic Lands percipitously
    before decommissioning their magical hold on Magic City and perhaps
    other planets as well. I needed to be careful. Or the Followers
    intended that their departure was temporary and they would return
    relatively quickly. They did not so the magic remained.

9.  As for the belief in magic, the Fungusians described that as a
    belief in a different way to manipulate matter and energy which they
    thought might be possible. (Ever the expansionate thinkers those
    Fungusians.)

10. If the Followers of the Stars left in a disorderly manner or under
    some kind of pressure, the Fungusians thought, the idea of a
    treasure map made sense. They could not take everything with them
    but devised a storage facility to hold their important goods and
    knowledge. They left pointers to this treasure trove so it could be
    found again.

11. The Fungusian Network wanted to get its hands (Fungusians do not have
    hands) on the map itself both to decifer it and to understand how it
    worked. They thought it was not a document per se but an objectd
    different than a document. Documents would need to be translated. No
    one knew what sort of language the Followers of the Stars wrote in
    or spoke in or in general communicated in.

Then the Fungusians floored me. This was in a strongly worded warning to
be very careful when traveling on Marling.

Our data about the Magic Lands is limited because our historical scope
of data collection has not previously included these particular planets.
We believe they were controlled by the Followers of the Stars. Whether
this meant they had some sort of religious or astrological connection to
the stars we do not know. We do know that this group of biologically
similar beings were players on the larger space stage. We give you this
picture which Captain Star Runner found on Planet X as our final
warning. We do not think these people are benevelent rulers but rather
are imperialists. Why they are no longer active in this region of space
we do not know currently but hope to know in the future.

The picture was of a wall inside one of the buildings along the
pedestrian walk at the riverside on Planet X. It showed a long line of
beings which were clearly either enslaved or prisoners of war being
paraded past a reviewing stand occupied by very human-looking people.
They had hard faces. The beings in the line were Tigerfoo, Pantheran,
Trololu and Featherote and some I did not recognize. All were in
chains--I kid you not--and looked very dejected. As this was a mural and
not a live video, I did not know if it commemorated a real event or was
a fantasy. It chilled me to the bone. I also realized Captain Star
Runner had been there while I was with Samara and neither of us had
known they were around. The image was taken from Star Runner's memory
database no doubt.

That the Fungusians had taken the extrodinary step to show me an image I
and label it as part of Captain Star Runner's image database meant they
were concerned enough for my safety to violate Star's privacy. I was
sure there was a clause in their contract allowing the Fungusian Network
to do this. It was probably in my contract, too, but to share it with me
seemed out of the normal flow of their business model. They were clearly
trying to scare me and make me aware how dangerous the Followers of the
Stars had been and what messing around with their stuff could entail. I
made up my mind to heed their warning knowing also that there might be
an inherit bias in their data collection. The network was set up by the
Union of the White Bear thousands of years ago. If that was taken into
account, it might well be that this warning represented the white bear's
distrust of the Followers. Who knew and who knew what difference that
made now. These were dead or almost dead civilations. I was dealing with
the resurgance of one of these civilizations, the People of the Rainbow
Sky and its impact on the Tigerfoo Confederacy. Was there an implicit
warning or concern here that the other ancient races might now take
interest? Something to keep in the back of my mind.

The intersellar ship I was on was no luxury vessel. Our couches were our
own, but they were crowded together with only naarrow walkways between
them. Meals were cafatearia style and were reconstituted and heated,
sort of. The menu was limited as well as the portions. We were
encouraged to eat quickly so that we could give our seats to waiting
passengers. We were also encouraged to walk the exercise track for long
periods of time to strengthen our bodies duringg the long flight time
between systems. The gravity pull on our bodies was limited although our
boost was high. I suspected the passengers were in the lightest gravity
areas of the ship.

Master Gaunt held a meeting while we trotted along the exercise track.
It meant we were all gasping as we talked and we could not stop and take
notes.

"Ronnie, welcome to our team," Gaunt said. "I know you had a rough time
going to Magic City. That is unfortunate since I know the Tribunal of
Wizards wanted to meet you and show you their city. I was briefed by
Grand Master Awk. I do not expect that you will find a similar
environment on Marling."

"Not at all," Tripp piped up. "There is hardly any magic at all on
Marling."

It seemed odd to me that she would have interrupted her master's
briefing. It also seemed odd that she would say there was no magic. We
were, after all, looking for a document presumably created by the
Followers of the Stars that would lead to a Followers facility. Magic
seemed quite likely. I was beginning to wonder if the wizard's death
could have been caused by magic if the document blew him away like I was
incompasitated. I was only feeling the effects of the magic at a
distance and most likely the buildings of the MAgic City and the
Lagrange Point space station, These looked like stone but Grand Master
Awk had assured me that they were conventional building materials. No
one would build a space station out of stone. I had wondered how old
that station was if it was cloaked in a spell. It also explained why my
walk from one dock to another dock had seemed to take so long. It was an
effect of the magic, too. What would I uncover on Marling and how could
I protect myself?

"We are going to start by visiting the stand where Wizard Takar died,"
Gaunt continued after giving Tripp a fatherly slap. (Tigerfoo parents
slap their children. I understand it does not hurt them but is a hold
over from their past. They calll them slaps but they are administered
more as taps..)

"After that, we are going to retrace his steps in reverse order to see
what we can learn unless other leads present themselves." "And we are
gooing to have so much fun," Tripp chirrupped. "I cannot wait to show
both of you how wonderful Marling can really be."

"I am afraid we are not going to the "fun" parts of Marling," Gaunt said.
"We will be traveling along the Devil's Background and finding our way
through Under the Hill before hoing up river. You come from the eastern
seaboard which is much more urban and developed. We are going to the
frontier and perhaps beyond in our search. I am planning on a long
journey rather than a quick in and out look see. To be honest, I am far
more pesamistic than some of the other wizards. We are essentially
looking for a needle in a haystack. Those documents could be a long way
from the Grinder's Stand where the wizard died."

"From an investigatory point of view," I said, "we are very late to the
"crime" scene. I hope we might be able to turn some helpful clues up,
but I am not holding out much hope. We may need to figure out who might
have stolen the documents rather than finding them directly."

"So do you think we will have a chance at recovery?" Gaunt asked.

"It is possible," I said. "From what I understand, the documents we are
looking for are valuable. This means whoever has them is probably not
going to destroy them. So we need to find that person or persons and
then figure out how to obtain the documents. Are we authorized to pay
for them or do we have some way of proving ownership?"

Gaunt did not answer me right away. As we were walking at a fast pace
for me, it took me a few seconds to turn to look at him. Hi forehands
were twisted together, a sure sign of some sort of stress or concern.

"I had not considered either possibility," Gaunt finally said. "Some how
I was imagining just finding them."

"Like they were in a cupboard or hidden under a rock?" I asked, trying
to keep the sarcasm out of my voice.

"Now that you put it that way, it does sound ridiculous," Gaunt
admitted. "I guess that is why you are along. You think like an
investigator."

"I am an investigator," I said, wanting to establish myself. Tripp was
an apprentice. I might be traveling with Gaunt and perhaps he thought of
me as an apprentice, too, since I was unfamiliar with the Magic Lands,
but I was detached to this investigation as a matter of confederacy
security.

"Do you think going to the stand is the right place to start?" Gaunt
asked.

"Yes, I think your plan as you have outlined is a reasonable one. At
this point, physical clues may be hard to find. We will have to
interview people, create a time line, try to figure out who the
wixard--does this person have a name?--who the wizard talked to and who
might have been following him or meeting him. What do we already know?"

"Let us find a quiet corner, if one exists on this ship, and sit down and
talk this through. I am to put together a list of items we need
planetside and they will be waiting for us when we get down there."

There was a sort of passenger lounge. It was not particularly private but
we were able to sit close together with some sort of hot drink which the
locals found acceptable. It was drinkable, but I would not call it my
favorite. I wondered why tea had never made it to this part of the
galaxy. You would think brewing leaves would be universal, but I ahave
discovered it is not.

Anyway, once we were settled with our mugs Gaunt began to explain:

"We do not have a name for this wizard," he said. "We have always just
called him the Wizard of Marling. He contacted the Tribunal many years
ago to say he was the governor of a region of one of the continents of
the planet. He wanted standing in our Tribunal. He said he knew there
had been a representative from Marling in the past. The archivist agreed
and we accepted his application."

"Sight unseen?" I asked. "I thought the tribunal was a
governmentalbody."

"It is," Gaunt said, "but Marling, especially the middle of the northern
continent, is wilderness--at least, for the Tigerfoo. We are expanding
into the area, but typically Marling has been populated by the humanoid
culture. They are in small groups, bigger than family groups, but still
rather primitive. The Tigerfoo are looking to settle the region with
farms and the beginnings of industrialization. With all due respect to
Tripp, we on Magic City think of Marling as pretty backwards. For some
reason, the indigienous people did not choose to develop past this
tribal stage. In the area we are going to, there are villages and the
people hunt, fish and gather as well as farm. Further west they are more
nomadic.

"And how are we to progress through this very primitive environment?" I
asked, realizing my creature comforts would be gone. What Gaunt
described sounded like a survival nightmare. It was going to be bad
enough to be outdoors, but there might not be any real inside.

I come from a domed city with al the latest amenities. Traveling in
Star's ride I had all the latest amenities starship travel could offer.
I was in the modern cities of the Confederacy before coming here. What
would I find?

"The Tribunal has contacted the government and they are providing a
guide for us who knows the lay of the land. The guide will be
responsible for getting us the necessary supplies and means of monitary
exchange," Gaunt explained.

I was horrified. Even with little exposure to human body language, Gaunt
knew I was very dismayed.

"Is there a problem, Junior Investigator?" he asked. "We thought this
would be the most efficient way of handling our introduction to the
frontier."

"I have two concerns," I said, trying to be as diplomatic as possible.
"First, the guide's loyalty is to the government, not us. We are
foreigners and report to two different governmental authorities. Second,
we do not know anything about this guide. They may have been with the
wizard of Marling. They may spy against us. I am very uncomfortqble with
an outsider being privy to our discussions, our movements and our
thinking about the crime." I leaned forward to be nose to muzzle with
Master Gaunt. "Make no mistake, Master Gaunt. At least one crime has
been committed here, that of theft. There may be others. Perhaps
Marling's death was orchestrated in some way. I have read the materials.
His death is being called a suicide. Perhaps it was. Perhaps it was
accidental. Or perhaps it was planned. If so, our so-called guide might
be involved."

"You have a devious mind." Tripp indicated by her gestures that she was
very disstressed. "You don't think well of anyone on Marling. People on
Marling are very nice."

Thankfully, Gaunt intervened.

"Apprentice Tripp." He spoke to her quite sternly, his gestures added to
the import of what he was saying. "Junior Investigator Ronnie Camberwell
is making some very good points, points the Tribunal should have
considered before going ahead with its plans. We are walking into a very
fraught situation where one person is already dead. It may have been
suicide as the locals say, but suppose it was not. We have to be open to
all possibilities."

"Oh, no," Tripp said. I can only describe her gestures as ringing her
hands. "I do not want to believe anyone would want to harm the wizard. We
thought he was a good man and had our best interests at heart."

"Did you know him?" I asked.

"No. But we all approved of what he was doing on the frontier," Tripp
assured us.

"By we do you mean the Tigerfoo on the eastern seaboard?" I asked.

"Yes, of course." Tripp said. She thought my question was peculiar.

"What about the Tigerfoo on the frontier or the indigenous people? What
about his rivals?" I asked, trying to think quickly of all the people
who could have had it in for Marling.

"Oh, I do not know about them," Tripp said a bit haughtily. "No one
counts the indigenous people and the Tigerfoo on the frontier are very
rude people."

Gaunt and I shared a look which Tripp did not see. This was going to be
interesting.

"We will probably have to stick with our plans for the foreseeable
future until we become better acquainted with the situation on the
ground," Gaunt decided. "I think it would be foolhearty to just strike
out on our own. I understand the frontier is a dangerous place. There
are dangerous animals, poisonous plants and local customs we know
nothing about."

Gaunt turned to Tripp.

"You and I will need to have a conversation," he said, "about conduct on
this assignment." Gaunt was in pure master mode. I excused myself. I was
not responsibile for Tripp and her naivete. I needed Gaunt. He at least
had a plan for tackling the frontier. I had not taken into account the
primitive character of the area and the obstacles to my investigation.

Why had the Director sent me on this mission? Surely there was someone
else who was familiar with backwater planets like Marling. I would not
call myself sophisticated by any means, but I had been around the block
once or twice and I knew bad guys could be around every corner. I had
such a bad feeling about this. How was I ever going to find this
treasure map even if it existed. And what were the odds of it existing
at all? How many thousand of years had it been lost and why did this
obscure wizard, whatever that meant, suddenly come up with it? Talk
about the Followers of the STars seemed so bizare.

Other than that, I could not be sure of anything.

When we reached the star system for Marling my links were again updated
and my links sent off another transmission with the advisory that I
would be out of touch for an extended length of time.

The Fungusians had done a great deal of analysis. Their tentitive
conclusions surprised me.

We have observed the impact of Magic City on your biological systems.
These are consistent with the few records we have which describe
conditions created by the Followers of the Stars. These conditions have
been classified as magic in our databases. Until we receive more data,
we can only say that you are sensitive to magic associated with the
Followers of the Stars. Being sensitive means that you can both detect
the presence of this magic and that it has a dilaterious effect on you.
Until you can ascertain how to protect yourself from these effects, we
recommend that you avoid exposure to it. We await anxiously any further
data you can give us to expand our knowledge.

P.S. We have forwarded your location to Captain Star Runner in case they
can provide any assistance to you. Your links are passive, but Captain
Star Runner's AI might be able to assist you in devising a defense
against the Followers' magic. As Captain Star Runner is quite distant
from both the Network and your ultimate destinationm, we think it is
unlikely that they will be able to intervene on your behalf.
NEvertheless we thought it was prudent to alert them in case their plans
could include a rendezvous with your party.

I doubted the cavalry would come over the hill in the nick of time, but
I thanked the Fungusians for their thoughtfulness. What else culd I have
done?

The space station at the Lagrange Point was old and shabby. It reminded
me of the stories STar told me about Dirty World Station. There was only
enough maintenace to make it spaceworthy and only enough amenities to
meet the needs of spacers. Spacers are the same all over the galaxy. A
bar. A brothal. A good repair dock and a chandlery. That is all a space
station needed. I could tell Gaunt was uneasy at what he saw.

"This is typical of a small space station," I said. It is not for
passengers. It is for the journeyfolk spacers. All the luxury goods and
high end restaurants you may find in a spaceport only come when you have
high-paying cruiseships and fast packets coming through."

"It seems so," he sought for the right words, "it seems so utilitarian
and not so well kept.."

"It is spaceworthy," I said. "It would would not do anybody any good if it broke
up, lost air or even moved from its expected location."

"So it is safe?" he asked.

"Safe?" I asked. "It is probably filled with pickpockets and con folk.
Watch yourself and especially watch Tripp. She is gullible and might be
kidnapped."

Gaunt stared at me.

"Why?" he stammered, his forehands failing the air.

"She would be a prize at a certain kind of brothel," I said. I smiled at
him. "That would be my experience as a police detective coming out.
Ptolemy City had a lot of very wealthy people in it and very few laws.
They enjoyed their pleasures and often their pleasures went to making
life miserable for the vulnerable and the unrpotected."

Gaunt took a deep breath. "Thank you for warning me. Apprentice Tripp
trusts everyone. She does not have a skepticism meter. I will not let
her out of my sight."

And, thankfully, nothing happened while we were there but I already knew
Tripp's impulsive behavior was going to be a problem. I knew nothing
about the frontier we were going to. I only knew that many desperate
people moved to the frontier. The People of the Northern Frontier back
home could speak proudly of their desire to be free, free from the
Coalition and all of its rules, but I also knew that many moved there to
avoid regulations and to bury their illegal pasts. Was Not Captain Star
Runner on the Northern Frontier initially to avoid the Pantheran
termination decree against them? I was trying to prepare my party for
brighans and bandits and all sorts of desperate people. I just hoped
there was someone who could help me adapt to the riggors of frontier
living.

1. I believed documents had been stolen.

2. I believed the wizard of Marling was dead.

3. I believed the circumstances of his death led to questions about it.

4. I believed my companions for this inquiry were totally inadequate and
   might be more of a hindrance than a help.But knowing all this might
   not prepare me for what was going to happen next.

Our hopper to Marling was non-descript. We were the only people on
the intrasystem ship. I had seen a group of grubby individuals,
Tigerfoo and clearly contract workers, get off the ship onto the
space station. From the little I overheard, they were miners. Marling
has rich deposits of precious metals and gems. They were assuring
each other they would stay in touch and talking about how they were
going to spend their money. I had been in an environment where we
talked endlessly of the war effort. The minors were a good reminder
that the rest of the Confederacy was going about its business with
little concern or even interest about the war. They would only become
interested if they were inducted into the military or if the war came
into their star system. Otherwise it was just another tax they
grumbled out when they looked at their pay statements.

Is your family involved in the mining business? I asked Tripp.

Okay then. You do not directly mine the gems. That's a dirty business,
but you take them afterwards and sell them to the highest bidders.
Coming from Hypatia, I thought of the League of Hypatian Pirates.
They would have been certain to get involved in such a lucrative
trade. Precious gems were hard to trace. I knew that from my policing
days. They could be used for trade and often that trade was for arms
and drugs. How clean were Tripp's family hands? I could not help
smiling to myself. Captain Star Runner would have liked to be
involved even if the dealing was shady.

Precious gems especially the Marling diamond.

What's so ffunny? Tripp aske.

Oh, I was thinking of my friend Star. They like to get involved in
lucrative businesses like precious gems, I said. They would like to
transport such items off world to lucrative markets.

You should have them get in touch with my family, Tripp said. We are the most reputable brokers in the whole world.

Oh, no, she said. My family brokers

And now I had to think of smugglers and how the Marling diamonds and
all the other precious gems could be used as monitary exchange. My
head was beginning to hurt.

For the first time, I realized what sort of a person Master Gaunt was.
I kept thinking of the wizards as some sort of characteratures rather
than real people with real responsibilities. Gaunt could not keep the
look of disdain off his face and his forepaws still as he surveyed the
seating on the hopper. It was old though no doubt spaceworthy. The
coverings on the boost couches were stained and worn if not cracked in
places. They reminded me of the booths at some of the diners I loved
to frequent in Ptolemy City. And when I strapped myself in, I felt the
all the places where other space travelers had rested their bodies
just like the diners.

Gaunt was an aristocract, born of the aristocracy, groomed from an
early age to be one of the lords of the realm. The image came to me
all at once. That was what the wixards were, not some characture of a
magician with a pointed hat, but nobility, acustomed to their rank and
privledges who had the responsibility of governing the worlds in this
sector of space. I did not understand it all yet, but a picture was
emerging. This mission for Gaunt might have seen like a chance to make
his name and promote itself.. On the other hand, it might have been a
way of sidelining him and sending him away to failure and disgrace.
Maybe he was experiencing the same doubts and confusion I was. Maybe,
but maybe he was one of those people who had reached middle age and
knew he was no longer going to be the Grand Master but was content
with a lesser portfolio because it gave him time to pursue his own
interests while maintaining his position in society. If he ended up in
a higher position by taking on this assignment, all well and good. So
long as it did not diminish his position he would be fine. After all,
he could dine out for years with stories of going into interrior of
the northern continent on Marling and spending some time on the
frontier. There would be exaggerated stories of his daring do and no
one else would be the wiser. Perhaps Tripp was his intern, his
secretery, his plaything. I did not know but I needed to find out. I
had been so oblivious to their relationship and the true set up. I was
so focused on actually doing my job.

Well, my career depended on doing my job. I was getting older and I no
longer could fool around. The war was real. I could not go back home
or even back to Half Moon Bay Space Station. I had heard it had fallen
to the People of the Rainbow Sky or was it the Golden Sun? In either
case, I hope Jack and the other people I had worked with their were
doing okay. Jack handled security and he could handle it again if he
had not been imprisoned or worse killed. Thinking about that would do
me no good. I had to keep focused on this planet and this problem.



* Death at the Grinder's Stand
I am throwing up my hands with naming things and trying to describe
people and places and make it just a little different to disguise that
I am talking about Meriweather Lewis and his death on the Natchez
Trace in the early 1800's. Instead, I will just use the names I have
and the real places. If I should ever rewrite this narrative, and that
will depend on how it turns out, I will consider how to fix this. I am
reminded that James Patrick Kelly wrote a novel based on Egypt and had
a river and a pyramid I think and such. I think I used that idea in
another of these novels. It is a good one and I think I will use it
again. Anyway, back to the story.

We at last arrived iat the Grinder's Stand. How long ago had it been
that Middle Wizzard had died here? This would not be the kind of
investigation I was used to. I had no tools except my own brain and
possibly interviewing some people. I wondered if anyone would actually
tell me the truth. I wondered if anyone actually knew the truth.

The stand itself consists of two buildings made of logs felled from
the trees which used to cover the ground. Nearby is a creek with no
name. I suppose it will have a name sooner or later. The creek is just
useful for water. Judging by the way water is used in these parts I
was glad I had every innoculation known to the Tigerfoo and that some
of my previous innoculations were probably still good. I shuddered to
think what sort of pathogens I might be ingesting. I pretty much stuck
to the bitter coffee people drank. It was pretty disgusting but at
least they boiled the water to make it.

The buildings were not well cared for. They would be very cold since I
literally could see through the chinks between the logs into the
interrior of the buildings. A sort of covered area was between them, a
breezeway of sorts. In the back was a place for our horses. Anaseth
and Dilucca would both tend to them, our gear and sleep there. They
also arranged for us to stay in one of the buildings. That was a sort
of guest house with some rude bunks. Skimpy blankets dirty blankets
and a very limited supply of wood was the some total of the amenities
provided. There was not even a wash basin. Gaunt scowled. I thought
Tripp was going to cry. She had become silent at this point, barely
responding when spoken to and hardly expressing interest in anything.
I was becoming concerned. Tigerfoo are not typically as bubbly as
Tripp had been when I first met her, but they could be pretty stoic
when needed. I was wondering if Tripp would be able to recover from
the trauma of this journey.

The other building also was one room and functioned as the
owner's home.

When we arrived, only the woman was there. She said her husband was
off hunting. Perhaps. I had heard at an earlier stand that her husband
was a drunkard and would go off for days at a time. I was not
interested in him. He had been away when Middle Wizard died.

After a scanty meal and Anaseth and Duluca had gone back to the
stable, I said in what was now my credible spoken Star Children
language, "Do you remember the Tigerfoo who died here some time ago?"

(I really need to work out the elapsed time of everything. It must be
at least a year.)

"Oh yes," she said. "He came through here last spring. The weather was
cold. There was still ice in the creek."

"I would like to ask you some questions," I said. "I am trying to
understand what happened. His death was so unexpected."

"Wel," Mrs. Grinder said, "I am not surprised he died."

She was a non-descript Tigerfoo with a long muzzle and dull fur. If
she had been a Star Child, I would have called her appearance unkempt.
She did not tend to her personal hygene with much diligence. Her nails
were worn down, the pads on her paws were cracked. I could see life on
the Trace had been hard on her. No doubt she had the full care of the
stand with her husband awway. It was easy enough to criticize her
innkeeping, but she did everything herself. I even saw her with an axe
going out to the forest to fell a tree.

"Why do you say that?" I asked.

"Oh, he had that wild look in his eyes the way men do when they have
had too much to drink," she said, turning back to the hearth. "He was
yelling from his bunk. I went in there to see what was the trouble. I
do not hold with my guuests hollaring like that. He said he was in
pain and wanted something to drink. I brought him a gord full of water
and he drank that down. Then he got up, and I thought for a moment he
was going to hit me or even kiill me. But no, he charged past me out
into the yard. He shouted for his servant. That Star Child was in the
hayloft. He must have been sleeping real hard because I never saw him
until the next day. I went back in here and that Tigerfoo kept
hollering. Then I heard the shot.

"Help me," he calls out. "I have been shot and the pain is so
terrible.

"So I went out there and he was bleeding from his stomach and I said,
"I cannot carry you."

"Then I'll die right here," he said.

"I went back into the house it being real cold like and in the
morning, I heard that Star Child screaming. Really gave me a turn, you
know. I went running out of the house and that Star Child was standing
over him holding his gun and I said, "You killed him, did not you?"

"And that Star Child said, "No, I did not. I found him here with his
gun and all the bullets in it."

"His servant said all the bullets were in the gun," I said.

"That is what he said," the woman said. "But I do not know if it is
true. I think he killed him. I think he fired both shots."

"There were two shots," I said.

"Yes, two shots." she said.

"And then what happened?"

"Nothing," she said. 

"What happened to his body?"

"Oh, the Star Child buried him on the other side of the road under
that big tree. Then he packed up his stuff and left."

"He took everything?" I asked.

"Sure did."

"And which way did he go?" I asked.

"He went back along the trace."

"Back to Natchez?" I asked.

"Rightly so," she said. "I guess he would need to find work and all
and there is more work there than in nashville."

"Wouldn't he have his master's money?" I asked.

The woman snorted. "That Tigerfoo had all nice clothes and a fancy
horse and all but he did not have any money. Anyway, none to speak of.
He barely had the coin to pay me and he caused me that trouble,
yelling and then dying that way. You are not the first to ask me about
that."

"Who else asked you?"

"Some Tigerfoo from Natchez came out here."

"Do you know who?"

"Why do I care?" she said. "He was dead and that was that."

And with that, she made it clear we should retire.

"What do you think of her story?" I asked Gaunt when we were in the
guesthouse.

"She is pretty indifferent to other people," Gaunt said. 

Tripp had curled up in the bunk. She had her face to the wall. I
wondered if she had heard anything of what was said.

"I did not know about the servant," I said.

"Neither did I, but I am not surprised. Most of the Tigerfoo on the
trace have Star Children with them. We do."

"And although I am often looked at ascance because of my color," I
said, "People just accept me as a Star Child and probably because I
ride with Anaseth and Diluca."

"You ride extremely well," Gaunt said. "I would not have known you had
never done it before."

"Thank you," I said. 

"Did we learn anything useful?" Gaunt asked.

"A few things," I said. I ticked them off on my fingers:

1. Middle Wizard is buried across the road under that conifer. We
   could have him exumed if we felt the need or had the facilities to
   do so.
2. Someone came from Natchez asking questions. Who? and why?
3. Middle Wizard had a servant with him. We do not know who he is or
   where he went. He took everything with him and yet we are told the
   documents are missing.
4. The servant said he did not kill Middle Wizard.
5. He said the gun had not been fired.

"I think that is quite a bit of new information."

"I can answer one thing," Gaunt said. "The Tigerfoo who came out here
is the same Tigerfoo who notified Washington Middle Wizard was dead.
We can talk to him when we get to Natchez."

"Good," I said. "That will be a start and maybe someone in Natchez
knows who Middle Wizard's servant was."

"The Tigerfoo will also have what remains of Middle Wizard's
possessions. Maybe something there will help us." Gaunt sighed. "This
seemed like such a sttraight forward business back on Magic City. Now
it seems too big a task to undertake."

"I admit it is daunting," I said. "But perhaps our contact in Natchez
can point us to the next individual to talk to. Police work is like
that. You talk to one person and then another and then another.
Sometimes you have to go back to someone several times, but eventually
you get enough information to put the pieces together. Right now I am
wondering why the Tigerfoo told you it was suicide. If the gun was not
fired, that would be impossible."

"It does make you wonder," Gaunt said. He yawned. "I will be so glad
when we get to Natchez."
* Natchez

We came into Natchez weary and demoralized. We were filthy, hungry and
tired. Diluca took over care of our horses, the wagon and our few
remaining supplies. Anaseth found a hotel with accommodations. The
hotelier balked at giving me my own room on the same floor at the
Tigerfu members of our party. A Star Child himself he was
uncomfortable with my dark appearance but in a whispered conversation,
Anaseth persuaded him otherwise.

"What did you tell him," I asked later.

"That you could put a hex on him," she said. "I do not know if you can
put a hex on him, but it was enough to get you your room."commodious 
   
I fished out a small coin out of my purse and handed it to her. "So
long as I do not have to perform any hexes, I am completely behind you
using that reasoning," I said.

There is an old saying. "When in Rome do as the Romans do." I once
looked it up and learned there was an empire once by that name on the
origin planet of the human race. The saying seemed to apply here. If
people thought I was some sort of sinister character, why not embrace
it.

After a hot bath I put on the hotel's threadbare robe while all my
clothes had been sent to the laundry. My room had been hastily
reconfigured for a Star Child with suitable furniture. I rested
happily on a real bed albeit with moth-eaten duvet. To be back in some
sort of civilization. Why people loved the out-of-doors still
mystified me. There was a gentle tap at my door. Upon opening it, I
found Gaunt in more or less the ame condition I was--clean and tired
looking.

"Will you join me for dinner?" he asked.

I looked down at my robe. "I do not have the clothes for it," I said,
"otherwise I would say yes."

"Apologies," he said, folding his hands accordingly. "I should have
said dinner in my room. I want to speak with you privately."

"Sure," I said.

He consulted his very elaborate wrist unit. "Shall we say in an hour?"

Later I joined him. Gaunt must have had the best room in the house. It
was a corner room, with windows overlooking the street on one side and
an unassuming building next to the hotel. My room overlooked the
building on the other side which was a bit disreputable. I could see
the street a little.

"First of all," Gaunt said, "What did Anaseth say to the hotelier?"

"She told him I would put a hex on him if he did not give me a regular
room," I said and smiled. "I told Anaseth she could say that about me
any time so long as I did not have to actually put a hex on someone."

"So they think you are a magician?" Gaunt asked. This was a totally
different word than wizard in his gestures. Magicians were somehow
shady or not benevolent.

"I do not think it is anything as complex as that," I said, thinking
of spells and wards. "Anaseth told me that I looked like an ogre. In
common parlents I am more a malevolent character in a story than a
magical being. Basically, I gather it just is a way of talking about
someone who cannot be trusted."

"A buggyman," Gaunt said.

"I think so," I said, turning the Tigerfoo word over in my mind.

"It is an old memory," I said. "I think there once were rulers here
with dark skins and dark hair. Somehow, they are gone now."

"The Followers of the Stars?" Gaunt suggested.

"Perhaps," I said. I did not know how much Gaunt knew about the
Followers of the Stars or what he thought about them. I decided to
keep what I knew from him. If he needed to know more, I would tell him
more.

"They are a people mostly of legends," Gaunt continued. "Perhaps these
ancient rulersgot confused in the local mind with these legendary
figures." He gestured a shrug. "No matter. Heroes and villains from
the past mythology of a place have no business in our business. We
will just have to work around local superstition as best we can."

I was surprised as Gaunt's summation. Were not we on a mission to
recover documents that told of a Followers of the Stars treasure and
where to find it? Then I realized, Gaunt did not know what the
documents contained. He only knew that we were looking for a
diplomatic pouch which important records in it. For all he knew, these
records could be payroll stubs or committee minutes. I wished someone
had told me this earlier. I resolved not to show my hand. I would have
to review my own orders from the Director and my instructions from
Grand MAster Awk. I was under the impression aI was to find the
location the treasure map pointed to. But maybe I was not to do this
on Marling?

Our dinner arrived and I was pleasantly surprised. Although the hotel
gave the impression of being run down, its food was quite tasty. At
least, mine was. Gaunt ate some of his and then sighed. "I have not
had a good meal yet on this wretched planet," he said. "I suppose our
meals would be better if we had stayed in one of the capitals of
Europe."

"Mine is quite good," I said. "I suspect a Star Child cooked it."

"No doubt. As you are seemed to be an ogre of sorts, we Tigerfoo are
also looked at with suspicion as we are coming to dominate more and
more of this area," Gaunt said.

"Where do we go from here?" I asked as I was finishing my meal."

"I have set up a meeting with the Tigerfoo agent in the morning,"
Gaunt said. "We can visit him together."

Should I ask about Tripp? She was not my responsibility but she was a
member of our group.

"And Tripp?" I asked.

"I have sent for a doctor," Gaunt said. "She examined her. She
prescribed some medicine and a lot of rest. If there was a way to send
her somewhere safe, I would do that."

"Back home?" I asked.

"It is too far. She certainly cannot travel alone. First of all, the
travel is dangerous. Second, Tripp is not equipped to make all the
necessary decisions travel would entail. She is a clever girl and will
do well under my tutelage on MAgic City, but bringing her out here was
a mistake. She is ill-equipped to manage such a harsh environment. She
is too naive and has not previously encountered any adversity."

"So we have to keep her close while exposing her to more adversity," I
said. "Our plan is to retrace the Middle Wizard's journey south and
that means going up river which I understand is no easy task."

"I have Diluca detailed to check out how we might proceed," Gaunt
said.

"Good," I said, yawning and stretching. "If you have nothing else, I
am going to try to get a good night's sleep."

"That sounds like an excellent idea," Gaunt said.

And with that, we said our good nights and I returned to my room.
     
* Meeting with the Tigerfoo Agent

The next morning dawned cold and clammy. The sky was overcast. Rain
was expeced later in the day. I awoke to clean clothes neatly folded
in my wardrobe and a new jacket hanging on a peg by the door. I was
grateful for everything. I dressed quickly and went down to breakfast.
Neither Tripp nor Gaunt were in the dining room. I knew Anaseth and
Diluca  would be eating in the kitchen. When I entered the room, all
conversation ceased. Everyone stared at me. I stared back. Working at
a police detective had its benefits. I was good at the cold stare and
quickly all the Tigerfoo dropped their eyes and went back to their own
business. The sound in the dining room was much quieter. They were
still not at ease with my presence. Good. Maybe something would come
of it.

In looking around for a seat, I noticed a small table in the bay
window set for one. As the configuration was for a Star Child, I went
to it and sat down, happy to look out the window at the comings and
goings on the street. A rather skiddish Star Child brought me my
breakfast. There was no menu and no ordering. My breakfast was a large
bowl of hot grain librally sprinkled with nuts and seeds. As I ate, I
identified the local honey. I also had hot biscuits, butter, a local
jam and a pot of hot coffee. Again, when in Rome.

I had not realized how hungry I was. Days on the Natchez Trace with
its both bad and meager rations meant I had been in a constant state
of hunger. I worried that over eating would make me sick, but it never
did. My body was so attuned to this food. I realized how difficult
Tigerfoo food was to eat and digest. I must remember that when I
returned to Tigerfoo society, if I ever returned. I somehow sensed I
would be a long time on Marling. It was certainly backward, but a
person could get used to it I decided. It would mean I would need to
schedule regular trips to the Lagrange Point Space Station. I wondered
how expensive that would be. It was an odd thought.

As I was lingering over my coffee, staring out the window I heard a
low growl behind me. It was not a threatening sound. It was more like
a human cough in its desire to grab my attention.

I turned to see Gaunt behind me.

"May I join you?" he asked. "Or were you leaving soon?"

"Oh, certainly, if you dare to sit with a notorious Star Child like
me," I said. "Can you manage this table?"

"I think so," he said, pulling up a Tigerfoo chair. "I am still not
adjusted to the local fare so I am eating lightly."

The serving Star Child brought Gaunt a light Tigerfoo breakfast and
refreshed our pot of coffee.

"Foul stuff," Gaunt said as he watched me pour another mugful.

"Oh," I said, "I think I am actually getting used to it and this from
a person who never drank this stuff in my own culture."

"You have this?" he asked, quite surprised.

"More or less," I said. "Different planet. Different growing
conditions but similar, I think. You would have to do a chemical
analysis I suppose, but I suspect taste buds cannot decipher when the
range of taste is close enough. Your brain just tells you it is a
different variety of bean and you either like it or you do not."

Gaunt shuddered.

"I always thought of myself as a Tigerfoo of discernment and a wide
variety of taste," he said, nibbling at what I supposed we might call
a scone. "But this trip has shown me what a snob and aristocrat I am.
I would not say I describe myself as picky, but I know now I have my
limits."

"This is all very foreign to me," I said, "but I think I could get
used to it if I were able to visit the space station every now and
then."

"That horrible place?" Gaunt shivered with remembered horror.

"It had the benefits of more modern civilization," I said. "Of course,
we did not get to spend any time in Europe. Perhaps they have some
more modern conveniences."

"PPerhaps," Gaunt said, but I rather doubt it. The pioneering life is
definitely not for me."

"Speaking of not enjoying the pioneer life, how is Tripp this
morning?"

"Better, but stil under the doctor's care. I think it will be some
time before she can rejoin us. I am engaging a nurse to look after her
while we pursue our investigations. The doctor seems competent so I
engaged someone he recommended."

"Good," I said.

"Anaseth will guide us to the Tigerfoo agent," Gaunt went on. "Diluca
has some concerns for one or two of the horses and wants to get some
of our tact mended."

Gaunt was assuming his natural leadership style. That was encouraging.
He had largely left that task to me along the NAtchez Trace since I
could more easily converse with Anaseth and Diluca as well as the
other Star Children we met. Although they were suspicious of me, they
accepted me more readily than the Tigerfoo. I was becoming aware of
the tension between the two groups.

Note to self: Mrs. Grinder is a Star Child. Although in Lewis's story,
she was a white woman, I think it works better for her to be a  Star
Child in this narrative. It also makes sense since Ronnie addressed
her in the STar Child language.

We finished breakfast and after returning to our rooms to freshen up
and retrieve our cloaks, we met ANaseth outside in the street.

"It will be easier to walk," she said and set out at a brisk pace.

I was glad of my boots as we walked along. There was not a sidewalk to
speak of and the streets were quite dirty and poorly graded. We went
up several steep hills. Gaunt with his Tigerfoo slippers--he was after
all in town--had some difficulty but both Anaseth and I managed all
right. After the last difficult descent, we arrived at a building that
looked more like a warehouse than an office.

I commented on this to Anaseth.

"It is," she said. "The boats dock Under the Hill and then the goods
are transferred here. That way the Tigerfoo," she sniffed to show her
distaste, "do not have to mingle with the riffraff along the docks."

I could here the quotation marks around riffraff. Anaseth did not
think the Star Children who worked the river were any such thing. I
reserved judgment having not seen the place. It did not have a good
reputation. It was frequented by cheating business folk and the river
pirates themselves. Brothels and gambling establishments dotted the
streets of the lower town. I had overheard some Tigerfoo at breakfast
discussing a clandestine visit there later that evening. I felt sad
for the Star Children who were forced to make a living servicing those
Tigerfoo. From a human perspective, they liked their sex rough and I
felt certain the Star Children needed miedical attention after each
encounter. I hoped they got it. Our skin is not designed to repel a
Tigerfoo bite nor are human orafaces designed to be penetrated by
Tigerfoo penises. Well, it was not something I could do anything
about.

We entered the office of the Tigerfoo agent who had supplied the
wizard with goods for a Natchez Trace journey.

"So you are the mysterious Dark Child," the Tigerfoo agent said to me
when Gaunt introduced me. "Word is spreading through the city about
you."

I was tempted to ask what sort of word, but Gaunt dismissed the
agent's remark and got down to business. I let him interrogate the
agent. His questions were the ones I would have asked. None of the
Tigerfoo's answers were surprising.

"Do you have any questions to ask, Junior Investigator Camberwell,"
Gaunt asked, finally turning to me. I noted his use of my title
conveying respect and legitimacy to me. I thanked him for that
internally. Let that word spread about me, too.

"Yes," I said. "Do you have any information about Middle Wizard's
servant? We understand he had one."

"Ah yes, the Star Child Ruand," the Tigerfoo agent said. Aha! The
servant had a name. "Ruand returned here with many of the supplies
Middle Wizard purchased from me. He was looking to trade them. As the
unfortunate news of Middle Wizard's suicide had already reached us, I
did not think it would be amiss to make the trade."

"Do you have a list of what he traded and what you gave him?" I asked.
"It would be ever so helpful."

With some hesitation and some monitary encouragement from Gaunt, we
received the lists. There was no need to take them. The agent might
still need them for his records. Nothing on what was traded in was
unusual. They were all good Middle Wizard and a servant would need on
such a journey. The good, however, that the servant Ruand received in
exchange were suggestive.

"Do you know where Ruand went?" I asked.

"He told me he needed to be outfitted for the suthern territory," the
agent said. I assume he went there."

"What is that?" Gaunt asked.

"That is the territory held by the Spanish. We call it the Southern
Territory and they call it the Spanish territory. According to the
treaty signed a few years ago, it is our territory but many of the
Spanish settlers are reluctant and even openly hostile to our take
over," the agent said.

"And how would we follow Ruand into that territory?" I asked. It was
imperative for us to speak with Ruand.

"There is a general route settlers take," the agent said. His
vagueness suggested he wanted more money for his information. Before
Gaunt could reach for his purse, I turned to Anaseth who was standing
just outside the door. "Can you find out about this trail?" I asked.

She smiled. She had picked up what the agent was doing. "Of course,"
she said. "I have a cousin who has been there and I can speak with
her."

Anaseth had a cousin for everything. And if she did not, Diluca seemed
to have someone to ask. We left the warehouse without spending any
more money at that juncture.

"We can get you a better deal if you want to travel to the Spanish
territory," Anaseth said.

"Can you take us there?" I asked.

Anaseth shook her head. "We cannot go there."

"Because," I prompted.

"We cannot cross that line," Anaseth said.

"Some legal problems there?" I asked.

"Some misunderstandings," Anaseth corrected.

"I see. Your cousin?"

"Or someone she knows," Anaseth said. "Diluca and I will take care of
that."

I translated for Gaunt.

"Do you think the new guide will be reliable?" Gaunt asked.

"That depends," I said. "We will have to see. I suggest you retain
ANaseth and Diluca to serve as our guides when we return. We will have
to get bback to Charleston one way or another.

"Good idea," Gaunt said. "A small retainer now with the promise of
more later."

"Yes," I said, "and with a stern reminder to look in on Tripp. I do
not tink she will be ready to join us. We may be gone a long time. The
Spanish Territory is vast and we are very late in trying to track this
Star Child down. He is very much in the wind and the fact that he has
gone over the border suggests he may have something to hide from the
local authorities. You might check with them if there are any
outstanding warrants or convictions."

"I noticed no mention of a pouch," Gaunt said. "Do you think that is
curious."

"No," I said. "Ruand may still have it. As I understand the briefing I
received from Grand Master Awk, the pouch would have contained money,
too, and perhaps Ruand thought the sealed part of the pouch contained
even more money, not documents."

"Your mind is devious," Gaunt pronounced.

"I am a detective and an investigator," I reminded him. "I need to
think like the crooks and perpetrators all the time to do my job."

"Agreed," Gaunt said. "That was not meant negatively."

"I am glad," I said. "I would not want you to think badly of me."

"I do not," Gaunt said.

* On the Trail of Ruand    

I looked in on Tripp before we left. She was sleeping. The nurse said
she was making a slow but steady recovery.

The cousin that would lead us into the southern terrritory was Nanc.
When I saw her, she took my breath away. She was so fair, so
exquisitely formed with long pale hair and watery blue eyes. She was
clothed in loosely fitted tunic and panteloons tied around her think
ankles. I wondered thashe did not wear boots, but on the trail, she
wore them and chaps also.

I saw a haunted look in her eyes. What secrets lay behind those
haunted eyes. I wondered if I would ever know. When she spoke, her
voice was as whispery as a summer breeze. Can you tell I was smitten?

Nanc looked me over critically and I saw the hard frontierswoman
behind her delicate looks.

"You will be both a problem and a weapon," she announced. "Anaseth
says you are smart, fair and strong. I hope I can depend on you to
have my back."

"If you play straight with me I will play straight with you," I said.
"If I think you are selling me short, lying to me or selling me out,
you will find out what a force I can be. I am handy with weapons and I
will use them when necessary."

Nanc nodded, more to herself than me I think.

"You speak our language well," she continued, "which will also mean
most people will think you are a native even though you are dark."

And she looked at me again. I quivered and I thought for a moment she,
too, felt the attraction I was feeling, but I could not be sure.
Although Tigerfoo, as I have said earlier, had no attachments to their
sexual behavior, I was uncertain what the Star Children thought. My
sexual relationships in the past had always been fantastic at first
and then became problematic with breakups being painful. My most
consistent lover was Captain STar Runner but even they could cause me
pain and I them. But Star was off on their own mission and it might be
many years before I saw them again and who knew for how long. The war
continued to impact us. We could not find some quiet corner of the
galaxy to settle down in and figure out how to be a couple again. I
knew at some deep level we were a couple and would always be a couple.
Star kept very quiet about a Pantheran's longevity. I suspected it was
not as long as mine. I wondered in that moment what I would do if they
were gone, move from one relationship to another? Never mind that, I
told myself sternly. You have a job to do.

And so we set out, Nanc, Gaunt and me. Gaunt drove our wagon with
supplies and Nanc and I rode. We did not take any pack animals with
us. Nanc said there would be sufficient pasture for the horses or inns
where we could stable them. We had some camping gear in the wagon for
days on the trail.

"I think Ruand would have headed for a city," Nanc said, "where he
could find some runaways to live with. Many live in the wilder
country, but Ruand himself came from one of the cities up river."

At first, we were able to stop at inns, but as we progressed south and
west, the inns became farther apart. We asked about Ruand at every
stop, but all the innkeepers could tell us was that many Star Children
came through alone or in small groups, looking for a better life or a
relative that had gone before them. The innkeepers were less sanguine
to have Gaunt at their establishment. Money helped, but I could see
the suspicion he garnered wore on him. The fact that he traveled in
the company of a dark Star Child did not help.

One evening while we were sitting over our ubiquitous coffee, a Star
Child challenged me.

"What are you doing here, Dark Child?" he asked. "You think you are so
smart with your dark ways and your charms." By this I was certain he
was referring to bad magic. "I bet you would think differently if I
showed you Star Child ways."

And he reached for me. I sensed rather than knew he intended to rape
me. Perhaps right in that room. A couple other Star Children stood up,
not to cheer him on but to help. There were six or seven of them. I
knew I could not fight them all, but I knew I could defend myself at
least for a while.

My knife was at his throat in a moment. Nanc knocked him down. Gaunt
threw himself into the fray, slashing with his paws and sinking his
teeth into more than one of them. My knife slashed again and again.

When the brawl was over, several of the Star Children were dead and
all the others wounded. We gathered up our things and saddled our
horses. We were back on the trail quickly.

"There isn't a lot of law out here," Nanc said, "but sometimes they
can be a problem. We are very identifyable."

"And we have to come back this way," I said.

"Not necessarily," nanc said.

Several hours later, Nanc found a place where we could camp a good
ways from the main trail in a secluded spot. We tended to the animals
and then bedded down.

We heard Gaunt's snores and his paws restlessly moving. Nanc slilpped
in beside me.

"You are very exciting when you fight," she said. "You know if we had
lost they all would have had you and you would not have survived
that."

"I do," I said. "I am glad you were there with me."

"All the way," she said. "I cannot stand them."

By which I decided she meant men. They were not my first choice or
even second choice for lovers. Nanc and I spent a good deal of time
eexploring each other's bodies in the pale moonlight as we listened
for potential trouble. We had not set a guard. Nanc and I were the
guards along with the animals. When the sun started getting warm,
Gaunt arose and we put him in charge of the animals and the watch
while we grabbed some needed sleep. It was late in the afternoon
before we got on our way again. Nanc chose a different route as we
moved south and west. After several more days, she announced we were
out of that trouble zone and nearing our destination. Every evening
Nanc came to my bed and every evening we explored the wonders of
female sex. Gaunt said nothing to either of us about it. I was certain
he understood what we were doing. I suppose what humanoids did with
their bodies did not interest him. I would later learn, in no
relationship to this adventure, that Gaunt preferred the company of
male Tigerfoo and that his orientation did not sit well with his
family or with the Tribunal. He therefore kept his own counsel about
such matters.

When we finally entered New Orleans, Nanc settled us in a modest hotel
while she began scouting for news of Ruand. She returned in several
days, days when Gaunt and I again reacquainted ourselves with
civilization and its perks. 

"I have news of him," Nanc said. "He is north of here several days
ride. Are you ready to go."

And we were, packing ourselves up again and getting on the road.
Wherever Nanc had been and whoever Nanc was with, she did not come to
me anymore and to be truthful, I was not sorry. Our separation in New
Orleans had allowed each of us to put that episode behind us and
resume our previous roles. No hard words were exchanged. No lingering
resentments or longings remained. In fact, I no longer saw Nanc with
the same eyes. She was alluring, but she no longer excited me. I was
back on track to get the diplomatic pouch and be on my way home.

Home. Now there was a strange word. I had no home anymore, but the
MAgic Lands were certainly not home to me.

When we found Ruand, he was tending horses at a rental station. He had
been, he told us, an ostler for most of his working life. It had
seemed natural for him to pick it up again when he had gone to the
Southern Territory.

"I cannot tell you much about the Middle Wizard," he said. "He hired
me and I went with him along the Natchez Trace."

'When did he hire you?" I asked.

"I cannot say for certain," Ruand said. "I worked for him for many
years. He always said he would give me a good pension, but I got
nothing when he died."

"So you traded in what you could and came out here," I said. "No
judgment. I am just asking."

"That would be about right," Ruand said. "I needed some seed money to
get going and there was his stuff and he certainly did not need it
anymore."

"And what about his death?" I asked.

"I found him dead. People say he committed suicide but that gun of his
was not fired. I am sure of that."

"And what about his pouch," I asked. "Do you have it."

Here Ruand hesitated, but I knew he had it. More import,ant, Ruand
knew I knew.

He began to speak, to try to justify why he had it.

"Please just bring it to me," I said.

He did.

I examined it under Gaunt's watchful eye. There were still a few coins
of some value in it. I scooped these out and handed them to Ruand.
Once I did that, I felt the pouch inside and out. Yes, there were
still document inside.

"And you just took the money," I said, "nothing else."

"Oh, I know there is something more in that pouch," Ruand said,
understanding finally that we were not interested in the money. "But I
could never figure out how to open it. You cannot cut it with a knife
and I did not know how else to open it."

"I am glad you did not," I said.

"So how do you think Middle Wizard died?" Gaunt asked.

"Someone killed him." Ruand said this with no emotion at all.

"Who do you think did it?" I asked.

"Cannot say for sure," Ruand said. "It was not the wife there at the
stand and I do not think it was the husband neither. He was always too
drunk to shoot straight."

"Then who?" Gaunt asked.

Ruand shuffled his feet and looked away then back at us.

"Begging your pardon, ma'am," he said. "I think it was a Dark Child."

His revelation surprised me. I recovered quickly enough to say, "A
real person or a spirit?"

Ruand laughed. "You think I think a ghost killed him? How stupid do
you think I am?"

"I am just asking so I can rule out any superstitious ideas," I said.
"I have heard a lot of strange stories."

"You and me both," Ruand said. "But what I mean is that I think
someone was following us, keeping to the shadows like and not getting
too close."

"Why do you think that?" Gaunt asked.

"Because I would hear things in the night," Ruand said. "A twig
breaking. Some rustling. Some disturbed bird or animal."

"And you think they were trailing you?" I asked.

"Yes, I do."

"For how long? FRom what point?"

"From up river at the capital for sure," Ruand said. 

"And before that?" I asked.

"I think for a while before we left," Ruand said.

"And you do not know who this person was?"

"No. I think I only saw him once and not very clearly, a long time
back."

"Before you got ready to leave," I said.

"That is correct. He was standing outside one of the clerk's offices.
He was dark like you but he was in the shadows like during the winter
when it gets dark early."

"But you did not say anything to anyone about this."

"I just thought he had on dark clothing and that made me think he was
a Dark Child. At least, that is what I told myself because I did not
want to think Dark Children were real anymore."

"And which office was this?"

"I do not remember," Ruand said. "They are all in a row and I was just
looking down the hall."

"Near you or far away?" I asked.

"More far than close," he said.

I knew I was not going to get any more out of him. We had the pouch
and that was what we came for. I thanked him and we left him to go
back to his horses.

Note to self: This conversation is entirely betwen Ruand and Ronnie.
Gaunt does not speak the language and does not understand it very
well.

"What did he say?" Gaunt asked. We had gone over the questions before
the interview.

"That the Middle Wizard promised him a pension which was why he took
his stuff and converted what he could to cash."

"And that is why you gave him the money out of the pouch?"

"I had no idea whose money it was," I said. "We were not here to
recover stolen property except the pouch and we have it. The document
compartment has not been open."

"So we have them," Gaunt said.

"If no one else has opened it," I said.

"You said Ruand did not know how," Gaunt said.

"But Ruand also said they were being followed since the capital and
maybe beforehand. He thinks they were followed by a Dark Child and
that a dark child killed Middle Wizard."

"And you believe him?" Gaunt was astonished. "I thought Dark Children
were only the stuff of fairy tales."

I considered what to tell Gaunt as we sat in his hotel room.

"I think they might be real," I said, "at least at one time they were
real and perhaps someone is impersonating a dark child to throw
everyone off."

"Like who?" Gaunt asked.

Well, it was now or never. We had the pouch, but I had more specific
instructions.

"Perhaps one of our enemies," I said. It was vague but Gaunt took my
meaning.

"Why would they be here?" he asked.

"Depends on what we find in the pouch," I said.

"You are going to open it? I am just supposed to bring it to the
Tribunal."

"And I hope you will," I said. "But my orders are to open it and look
inside to see what is there and then decide what to do. And if I am
not mistaken, your orders say you are to assist me in any way
possible."

I hated to pull rank on Gaunt. He was a good Tigerfoo and had not
gotten in my way.

"Agreed," he said, "but Middle Wizard was bringing the documents to
us."

"And neither of us know what would have happened if he did," I said."

We waited until the middle of the night. We checked our door and
windows. We were alone as much as we could tel. Nanc was in the stable
with the animals. We turned on a lamp and kept the flame low as we set
about opening the pouch.

It was pass code protested of course, but the Fungusians had embedded
protocols in my links which I could use to bypass the codes and then
reset them.

As expected, there were accounts and reports. I skimmed them. They
were not what I was looking for. Gaunt examined them and made some
growling sounds of displeasure. I would ask him about that when I was
done.

And finally I pulled out the document I was looking for. It was not
paper. It was a flimsy of sorts. It did not have writing on it. It had
numbers--a lot of numbers.

"This," I think," I said, "is what I came for."

"What is it?" Gaunt asked. He did not expect me to answer him.

"I do not know," I said. "I think it is in code, but I am pretty
certain it is what I came for."

"Middle Wizard had discovered a lot of corruption." Gaunt explained.
"He was going to report that and make a lot of people's lives very
uncomfortable."

"Anything significant?" I asked.

"Perhaps," Gaunt said. "A certain general was playing both sides,
swapping information for information and cleaning up very nicely."

'General?" I asked. "Anything to do with the war effort?"

"I do not think so," Gaunt said. "Just local territory stuff."

"Land?" I questioned.

"Yes, how did you know?"

"What land?" I asked.

"Some place north and west of here I think, along one of those
intermidable rivers."

"Maybe you and Nanc can pinpoint it on a map." I said.

"Do you think it is important?" Gaunt asked.

"I do," I said, "but I am not yet sure how."

I put the pouch under my clothes. It was valuable, but I had made sure
my links had recorded each document in full. If they became lost or
stolen, I still had the information. I was nervous I did not have an
uplink to store the data, but that was beyond my power to do anything
about.

"I hoped this would be the end," Gaunt said, "But I see it is not."

"Sadly, no," I said. "I wish it were over, too."

         
* Return to Natchez
Middle Wizard's documents on corruption were straight forward. A man
named Wiljam was spying for both the Spanish government and for Middle
Wizard's government. He had been a decorated war hero but always on
the shady side. Middle Wizard sited an an incident that was over 30 years
old. The information passed was not always important. The game seemed
to be more about income for Wiljam than any serious attempt to
undermine either government. Middle Marling was concerned that this
passing of information--illegal as all get out--had the effect of
undermining Tigerfoo spread and thus control of the continent. The
Tigerfoo government in Washington did not control the whole continent
by any means, but it did control a lot of it since its land deal with
the French several years before. Middle Wizard himself had gone to the
west coast to see if there was a water course that could move goods
and Tigerfoo across the country and back. There was not, but even so,
the trip has been worthwhile. Middle Marling was very interested in
all the flora and fauna he saw and had an extensive catalog. He had
also learned that many of the Star Children were violent towards his
party and towards each other. He recommended a campaign of
pacification that horrified me. Middle Wizard had no respect for the
Star Children. He saw himself as superior to them. I wondered if this
was a general attitude or if it was more unique to him. My only guides
to their general attitudes were limited. There had been the hotelier
in Natchez and the Tigerfoo agent. Tripp and Gaunt seemed all right
with Anaseth and Diluca. Gaunt seemed fine with Nanc. For that matter,
Gaunt and Tripp accepted me--or at least I thought they did. Middle
Wizard's writing upset me I realized. I had always thought of the
Tigerfoo as open-minded. He was definitely not.
The rest of his reporting indicated that his governmental
responsibilities were going well and that the corruption he
encountered was pretty run-of-the-mill. He was intent on opening up
the West and was concerned that Wiljam's information passing would
strengthen the Spanish and therefore border troubles might flare up.
He also wanted to have total control of the river that went past
Natchez into the sea. He believed that river was crucial to control
for the success of the Tigerfoo experiment on this continent.

That sounded like local politics to me and not part of the war effort
so I set all that information aside.

My links still had not made sense of the flimsy and its numbers and
could not confirm it was the treasure map I had been sent to find. It
either was the treasure map or the treasure map had been stolen. I was
betting on the numbers being some sort of cipher. My links were
proceeding on that idea, too, but it was not a cipher that they knew
so they needed to figure it out. The computing power within my links
was sufficient for most things, but deciphering a code that was
advanced as this one would take a long time. I figured this was all
right since we had to get back to Natchez to check in on Tripp.
Besides, we needed to get out of the Spanish countryside where we might
be wanted in the deaths of those bar going Star Children.

Another complication awaited us when we awoke to find both Nanc and
Ruand dead.

We were questioned, of course. As they had both been killed by having
their throats cut, the sheriff was working under the assumption that
the same killer had done it. I would have come to that conclusion
myself. As we were strangers in these parts and as Nanc was our only
connection to our way back to Natchez, we were ruled out. I had to
show the sheriff my knife, and although he admired its blade and
craftsmanship, he was certain it was not the murder weapon.

Gaunt and I were shaken. We did tell the sheriff what Ruand had said
about the shadowy figure, but he dismissed it as superstition. I was
not so sure. Gaunt did not know what to think.

"I cannot figure out what is so important that it results in murder,"
he complained to me. "I feel so out of my depth here. When I was given
this assignment, I thought it was a bit of a lark to tell the truth,
roughing it on a backwater planet for a few weeks, getting away from
the politics of Magic City and coming back with a few tales and maybe
even getting a commendation. I thought it would look good on my
resume, you know. I would have experience outside of the usual
aristocratic circles. But now, I am scared and I am scared for Tripp,
too. Do you have any idea of how we can get back to her?"

I had been wondering the same thing. I knew I could not retrace our
steps even if I had wanted to. Every trail and road had looked more or
less the same to me. I can find my way through a city and now through
a space station for that matter, but not this open landscape with all
this open sky. Winter was coming and I knew, if only from my reading,
that travel would not be easy.

Thankfully, our animals and gear was safe. We gathered up Nanc's few
possessions to return to her relatives and made our way out of town.
We were directed to a river town. There we might still be able to get
a flat boat headed toward the big river and get to Natchez that way.
The river would not freeze for a number of weeks and so navigation was
still possible.

Thankfully our coin was still good there and in a few days we were
floating down river.

I will not trouble to tell you about our river excursions. For the
most part they were uneventful. There were a few tense moments with
rapids and some long portages, but eventually Gaunt and I arrived at
the docks of Under the Hill.

     
* Bad Stuff Happens

I had the very sad task of informing Anaseth and Diluca about Nanc's
death. 

"You really are a Dark Child!" Anaseth eclaimed. "If Nanc had not gone
with you, she would not have been killed. I told her not to go! Now
she is dead. I will make sure none of the Star Children will ever help
you again. You are so wicked." In
tears, she ran from the stable yard where I had found her and Diluca.
I could understand her anguish, but not her casting me in the role of
the villain. We had been set upon at the inn by Star Children. Maybe
even Star Children had killed both Nanc and Ruand.

"They were not just cousins," Diluca commented.

Then I realized Anaseth and Nanc had been lovers. Nanc had pulled back
from me and now I knew why. It was a fling, something attracted us and
then it was over. I was glad Anaseth did not know. I would never speak
of it to anyone so that she would never find out.

"It is bad," Diluca continued. "Nanc was very well liked. There is a
network and now word will spread through it."

"And what about you?" I asked. "You are part of the network."

Diluca shrugged. "I will keep an eye on the horses and gear," he said.
"But that is all. I cannot afford to have any close association with
you. You and the Tigerfoo have been fair employers--more than fair
really, but I do not want anyone to think I work for a Dark Child."

"That is fair," I said. "I will make sure Gaunt always is the one to
be seen with you. Thank you for being so candid with me."

And with that, I left the stable yard to check in with Gaunt and
Tripp.

They were in the dining room. Tripp's appetite had returned. For a
Tigerfoo, she was still lacking brightness in her black eyes and her
skin still hung loosely on her body. She had lost a lot of weight and
her bounce was gone. I wondered if she would ever get it fully back.
Perhaps if she stayed in populated places.

"We have lost the services of the Star Children," I said very quietly.
"Anaseth is spreading the rumor that I either had something to do with
Nanc's death or just the fact of being called a Dark Child makes me
dangerous or implicated in Nanc's death somehow. Diluca will look
after the animals and gear, but he will do that on the quiet until we
leave Natchez."
"And we are going to leave Natchez soon?" Tripp asked.

""I think so," I said.

"I thought we would be returning to Magic City," Gaunt said. "We have
the documents we wanted to find."

"You have the documents you wanted to find," I said. "My orders are to
find the treasure map."

"And did not you find it?" Gaunt asked.

"I am still uncertain about that," I said. "I have a document, but
thus far it makes no sense to me. It has to make sense to me."

"We could study it in Magic City," Tripp offered. Maybe her bounce was
starting to come back after all.

"No, I need to stay here," I said."

Note to self: Did Grand Master Awk know about the map or not? I think
he did or he should. Why else would he have Ronnie involved. Why do
not Gaunt and Tripp know this.

"You are right about the map," Gaunt said. "It looks nothing like a
map so we need more information. Where do you propose we look for that
information?"

"Back in Saint Louis," I said. "I doubt the Middle Wizard came upon
this map in his travels down river and along the natchez Trace. I
think he must have found it there."

"Or on his previous journey of investigation," Gaunt said
thoughtfully. "It is clearly not something he wrote."

"Agreed," I said.

"So we go up river?" Tripp asked. She was not at all enthusiastic.No
bounce here.

"Yes," I said. "I am not certain how, but we must endeavor to find out
how. Gaunt, I am afraid you are going to have to arrange that. I will
not be welcome Under the Hill."

Gaunt looked surprised, then understanding. His paws moved through the
gestures. "You are, , of course, right," he said. I will start
immediately after our meal. Ronnie, do we need the horses?"

"Check with Diluca," I said. "He may know if there is a trail north or
if we should find passage. I do not want to retrace our steps along
the NAtchez Trace."

"Neither do I," Tripp said. She trembled all over. "That was
horrible."

"I will see about things," Gaunt said. "Perhaps the Tigerfoo agent
would be helpful."

"Make sure he does not cheat you," I said. "I supect Tigerfoo to
Tigerfoo you can be quite effective."

Gaunt smiled and gave a pleased gesture. "You are quite right,"
Ronnie," he said. "Just because I come from the higher classes does
not mean I cannot drive a hard bargain."

Tripp and I retired to her room. Gaunt had paid off her nurse who
assured Gaunt Tripp no longer needed her services.

"I do not know how we are going to get to Saint Louis," Tripp
confided. "The usual way things work is that people hire a boat and go
down the Big River to Natchez. When they want to go north again, they
take the Natchez Trace. We have done everything backwards."

I thought she had a point. There was a way in which I thought this
whole idea was backward. I had the flimsy which I thought might be the
treasure map, but I had no idea of its provenance nor did I know how
to read it. Furthermore, I did not know how the Middle Wizard died and
why. Ruand claimed a Dark Child had been following them. And both
Ruand and Nanc had been brutally murdered. Neither of them had the
documents. Gaunt and I had not been molested. Was there a Dark Child
involved, or several Dark Children? Were they following us? Were we in
danger now that we had the documents? Now that I had the documents?
Were we being watched? Now that Anaseth was making sure all the Star
Children would boycott us, what did any of that mean? Anaseth had not
threatened our lives, but would someone else threaten them? Was this a
local matter or would word spread up and down the river that we were
to be avoided? Was Diluca's reaction a positive one or was he the one
who was watching us?

"You are becoming paranoid," I scolded myself. Then again, sometimes
paranoia had its justifications. OH how I wished I could contact
someone. Frontier planets might have their attractions, but being out
of communication with the rest of the Confederacy was not one of them
as far as I was concerned.

And I had a nagging thought that was just now coming to the surface.
Was it possible that the People of the Rainbow Sky were dogging our
trail? They were a colorful people, but  could they produce a skin
color that would trick someone into thinking they looked like Dark
Children? If so ...

I stopped myself from going down that rabbit hole. It would be so much
easier for the People of the Rainbow Sky to integrate themselves to be
a Star Child. They could pass in society and would not have to keep
in the shadows.

"Do you know anything about the Star Children legends?" I asked Tripp.
She was, after all, from this planet and even from this continent.

"You mean fairy tales?" Tripp asked. She moved her paws in a dubious
fashion. I could not tell if she meant she was dubious about fairy
tales in general or those of the Star Children.

"Yes," I said, hoping this was the right answer to elicit some
information. "I am wondering about any stories about treasure or Dark
Children or anyone with special powers."

"I was becoming convinced that the Dark Children were the Followers of
the Stars. We did not have any pictures of them except what was in the
Fungusian databases and they were not helpful in that regard. The
images were fuzzy and grainy. We could tell they were humanoid, but
that was about it.

"Superheroes?" Tripp asked. She was quite confused.

OH, well, I thought, she does not seem to be able to help me. Then
Tripp not only surprised me, she took me to task.

 "What are you getting at, Junior Investigator Camberwell?" Her body
 language screamed outrage. "Why are you asking me about fairty tales
 and superheroes? Why cannot either you or Gaunt understand that I am
 a full member of this mission? If you could give me some background,
 maybe I could help you. I am, after all, from this planet and this
 continent. I believe in the great experiment we are undertaking for
 this continent. That is why I went to Magic City, to train and to
 become a part of the Tribunal of Wizards. I know everyone thinks I am
 a pretty tail. I was assigned to Master Gaunt to protect me from all
 the prowlers out there. They knew he would not assault me. I know the
 Natchez Trace was very hard on me both emotionally and physically.
 Nothing I have ever done in my life prepared me for that kind of
 degridation and hardship. But I have come through it and I am
 stronger now. Why cannot either of you trust me with any
 information?"

I was stunned, but I immediately realized Tripp was right. I closed my
mouth. I was going to deny her accusations, but in them I could hear
my own voice as I shouted at Colonel Gyllian Romeres Lujo, Emily
Dickinson, and especially Captain STar Runner and the now compromised
artificial intelligence Kristabel. \

"Let us make sure we will not be overheard," I said, "and I will do
what I can to bring you up to speed. Your local knowledge may be very
helpful to us, especially when we get to Saint Louis."

We were alone. I even knocked on doors all over the floor. Tripp
smelled everywhere. No one was around that we could tell.

"All right," I said, settling down to talk. I was sitting among
bed clothes. It was the best we could do for a suitable chair for me.
"We came to Marling to retrieve the pouch Middle Wizard was carrying."

"Right." Tripp said. "And you and Gaunt did that while I was
recovering."

"Yes, but that is not all of that part of the story," I said. "During
our journey, I was attacked by some Star Children at an inn. It was a
very ugly fight and we killed some of them. Nanc and I did that. It
meant we had to travel differently, but eventually we found Ruand. He
had the pouch and he gave it to us. He also claimed that someone was
following him and Middle Wizard. He suggested that the follower killed
Middle Wizard. (I used the word follower intentionally to see if Tripp
reacted to that word in any way. She did not.) He described that
individual as a Dark Child. You know people keep referring to me as a
Dark Child."

"I do not understand that," Tripp said. "You do not look anything like
a Dark Child."

"And what do Dark Children look like?" I asked, hoping for some new
insight.

"They are ugly," Tripp said. "They are like monsters. At least, that
is what my books said."

"What sort of books?" I asked.

"Fairy tale books," she promptly said, "like you asked.

"Did they look real to you, I mean, real to you as an adult?" I asked.

"Not at all. They were cartoons, you know, scary but stupid."

"Okay," I said. "That is probably not what real Dark Children looked
like."

"You think they are real?" Tripp was astounded.

"I think they were at least real a long long time ago," I said. "I
think they lived here and were very advanced. I do not know this for
sure. They lived here and then they left. I think they were the
original wizards."

Tripp thought about this for a while, her paws moving in what looked
to be aimless patterns but which I thought were more likely part of
her thinking process.

"That could make some kind of sense," she finally said. "In the
library at Magic City there is this portrait, a picture on the wall, a
two-dimensional picture--you know what I am talking about?"

"Yes," I said. "I know about portraits."

"There is this portrait of a wizard, with a hat on his head, a hat
that comes to a point. He has a staff, too. He is humanoid, like you,
with a fancy cloak. He is pointing at something with his staff.
Because of his hat, you cannot see his hair, but his hand holding the
staff is dark in the same way your hand is dark. He has a large ring
on his finger. Master Gaunt told me it is his signet ring that says he
is the chief wizard like Grand Master Awk is our chief wizard. I asked
Master Gaunt about the ring, but he said it was lost which was too bad
because it helped with the wizard's magic."

Bingo! I had my connection.

"That is very important, Tripp," I said. "I did not know about that
portrait. I suspect Master Gaunt has not connected the figure in the
portrait with Dark Children as you have. Perhaps he was not as good a
student of fairy tales as you are."

"Or he forgot about them or he thinks they are stupid," Tripp said.
There was bitterness in her voice. "Master Gaunt thinks I am stupid."

I hoped she was not right about that. I thought that maybe Gaunt did
not know how to interact with Tripp. He thought he was more of a
caretaker than an educator. Maybe I could help fix that.

"So let us imagine that Dark Children were real at some point," I
said. "We do not know what happened to them. After all, you probably
have a long line of Grand Masters that are Tigerfoo and not like the
wizard in the portrait."

Tripp gestured in the affirmative.

"Let us further suppose," I said, "that at least one person, and
perhaps more people, are here on Marling pretending to be Dark
Children. They are either like the wizard in the portrait which does
not seem very likely to me or they are pretending to be Dark Children.
I cause a stir wherever I go. People seem almost innately afraid or
distrustful of me. Let us assume Ruand was telling the truth. Someone
did follow him and Middle Wizard. That person killed Middle Wizard and
either followed Ruand or is following me. Either way, they came to
where we found Ruand. I think they killed him and Nanc as either a
warning to us or because they would not tell them something."

"So you think they followed you back here." Tripp said. Her gestures
were just a little jerky. She was trying hard to be brave and not
scared.

"That is quite possible," I said. "We were not interfered with on our
journey back here. The trouble we are having with the Star Children
here are not directly caused by the Dark Children. That will be
Anaseth's doing and I understand it. She is upset that her lover was
murdered and she blames me."

"That is not fair," Tripp said with belligerence. Her paws were
emphatic. "You did not kill her."

"But Anaseth is combining her fear of the Dark Children with me and
her grief at losing Nanc. I get it. It is just very unfortunate for us
and is counterproductive. Nanc was a very good woman. I would have
liked to know her better."

And what she could do in a bedroll was amazing, but I did not tell
Tripp that.

I must have betrayed my thoughts or emotions because Tripp said, "You
found her very attractive, did not you?"

"I did," I said.

"You had sex with her," Tripp said.

"I did for a time on our trip," I said. "We did not continue it. In
her own way,, she was loyal to Anaseth. It was our fight with the Star
Children in the inn that brought us together and later that passion
burnt itself out."

Tripp made a gesture I was uncertain how to read. Finally she said,
"We could have sex together. Gaunt will not have sex with me and he
will not mind if I have sex with you."

Having Gaunt in the middle of this conversation was a little strange,
but Tripp's matter-of-factness and the privacy she was offering me was
getting my attention.

"It would just be sex," I said.

"Of course," Tripp said. "My family would not like it if I did not
mate with a suitable Tigerfoo male."

"Okay," I said. "Lead the way."

And Tripp did with surprising tenderness and care. I had only seen
male and female coupling before. Tripp showed me how less violent
Tigerfoo sex could be. I suspect if she was male it would have been an
entirely different experience, but Tripp herself was cuddly and
altogether female in her desire. She did not roar when her climax
came. When I asked her about that she explained that the roaring came
from the contact with male ejaculation.

"When females do it, it is quiet like this," she said.

Her fur against my naked body reminded me so much of Captain STar
Runner. Her tongue was rough like theirs. I would have to them how
Tripp touched my body with her paws. I did not know paws could be that
arousing and Star Runner had done quite a lot of arousal.

Tigerfoo smell different from Pantherans. Her fur was not as soft, as
thick or as long. I could not grab handfuls of it as Tripp licked me.
Nor do Pantherans have forehands like Tigerfoo have. Tripp's fingers
played across me like I was a musical instrument. Tripp was no
shrinking violet. She had done this often. Is this what young Tigerfoo
females did?

Tripp said, "I like touching you. It is different from touching
Tigerfoo females, but there is no question you are female. I know I
will have to have sex with a mate, but I would rather not."

"Do you have to mate?" I asked. "Can you just bond with another
female?"

Tripp sighed. "Not really. Gaunt has the same problem you know. His
family wants him to mate."

I thought there might be a solution to their joint problem there, but
it was not my place to suggest a mating of convenience.

   
* Going Up River in Wiljam's Boat

Gaunt appeared at dinner time.

"Good news," he said. "We are going up river when when the tide
turns."

"How?" I asked.

"Wiljam is going to Fort Vickin. His captain has agreed to transport
us that far. We just have to get to the docks and Diluca has agreed to
rent a wagon to get us there before dawn."

"Rent?" I asked.

"Yes," Gaunt said. "I have arranged the sale of  our animals and gear.
We cannot take them with us in the boat. We can secure new ones if we
need to."

He was quite pleased with himself. He had made contacts with other
Tigerfoo and moved our investigations forward. I had been worried that
Gaunt would want to leave Marling now that he already had the missing
documents, or at least I had possession of the missing documents.
Maybe he still would propose that when we got to a place where our
paths would diverge. I was not sure how committed to finding the
treasure Gaunt was. My orders were clear. Grand Master Awk had focused
on the treasure map but not the treasure itself.

Did I really believe there was a treasure. Oh I think all cultures
have stories about buried treasure. I had read the old stories about
pirates and their ill--gotten gain being secreted away. I had been to
the Landscape of Thorns where dangerous chemicals had been stored and
warnings put up to discourage anyone from being exposed to their
deadly radiation. Hidden things always brought out people who wanted
to find them, possess them, get rich off of them whether it was
finding a lost spaceship derelict in space or looking in the depths of
oceans or climbing high mountains. Before I left Half Moon Bay Space
Station, word came that an artificial intelligence powered freighter
had been located in the ocean of a moon. People had braved the methane
and the cold to salvage the craft and claim its content as their own.
It had cost them dearly in money and lives, but the raw ore the
freighter was carrying was worth far more, two million fold or so I
had heard. I just wished I knew what the flimsy I carried signified.
Was it the key to the treasure or was it just an inventory list from
some long lost kitchen or laundry. My links were still working on the
decoding, but their computing capacity was very limited. If only I had
access to an uplink. I wondered if it would be worth traveling back to
Europe to be in touch with the Fungusian Network. That seemed extreme,
but the problem seemed insoluble at this point.

"So," Gaunt said, apparently for the second or third time, "can you be
ready by three?"

"Certainly," I said.

We said good-bye to Diluca who was in a hurry to leave us. He must
have been glad for the cover of darkness. His pale head disappeared
around the corner of a building as he drove his team away.. I noticed
he had worn a bandanna across his face, not wanting to be recognized
by the STar Children stevedores who brought our luggage onboard.

We had been given a cabin on one of the upper decks fitted out for
Tigerfoo. If I was expected to go below with the Star Children, I
pretended to know nothing about that. I found a corner to call my own
and settled down to be invisible during our journey. Gaunt had not
mentioned to Wiljam that he had an off world Star Child with him and
we had decided it would be best, given the network of gossip Anaseth
would have started not to fill him in or have him overhear any
maligning of me and the possibility of either wrongdoing in Nanc's
death or ulterior motives. I would pose as their servant who was not
coping well with our river journey and, as it turned out, I did not do
well with the motion of the boat, the smell of the fuel for the
engines and the food.

Tripp came back to the cabin regularly to check on me which I both
appreciated and found annoying in equal parts. I always thought she
was waking me up after I finally got to sleep on the one hand and
appreciated her concerned face and the edible food she found to
encourage me to eat. The Tigerfoo principles on this trip indulged in
a high quantity of meat. Plant based food was scarce but Tripp
developed a rapport with the cook who found food to bring me.

"Master Gaunt has been talking up Wiljam," she reported. "Wiljam wants
Master Gaunt to invest in some scheme which involves large tracks of
land in the Spanish territory. Master Gaunt assures me this is some
kind of shady business to defraud the investors. I really cannot
follow the particulars." She made a gesture of shame. "You would think
I would understand the financial procedure, but I do not. Perhaps it
is because it is so underhanded. Anyway, Gaunt assures me he will not
put any money into Wiljam's venture. His excuse is that he does not
have the capital with him and he would need to consult with his
advisors in MAgic City. It is a good plan and it is working to his
advantage. Wiljam very much wants a letter of introduction to the
powerful people on Magic City. Gaunt is stringing him along, hoping
the authorities there can finally stop Wiljam's double dealing. That
would be a bonus for our trip here."

"Sounds ambitious," I said. "What about the Middle Wizard?"

"All Wiljam will say is that his death was all quite a shame and that
Middle Wizard was in bad shape when he last saw him, clearly
struggling with addiction and depression. Wiljam dismisses the Middle
Wizard's death as a suicide, all very tragic, but it happened a long
time ago and there is nothing else to say."

"I bought him a bottle for the road," Wiljam told Gaunt. "Maybe that
was a nasty thing to do as things turned out, but he was ill and I
thought he might be able to use it for medicinal purposes going along
the Natchez Trace. They have lousy drink along that road from what I
hear and barely edible food. I did not want him to suffer that sort of
degradation. After all, he did our country such a service going out to
the west coast like he did. A definite hero and we are the poorer for
his loss."


"We will be at Vickin soon," Tripp told me. "We do have to pass near
an island in the River. Everyone is anxious because pirates sometimes
come out from there and attack bigger boats like ours."        

* Pirates from the River Islands

At that moment we heard shouts from above. Tripp went to leave.

"Stay here," I commanded. "Lock the door. We cannot help with the
defense of the boat. It is unlikely that door will hold against any
attack, but it might slow an attacker down."

I made sure I was fully dressed, armed and in personal possession of
the documents. Tripp also strapped on her diplomatic pouch.

"What about Gaunt's pouch?" I asked.

Tripp quickly found it along with his money. We divided the money and
she strapped on the additional pouch. We waited in anxious silence,
listening to the canons thunder and the pitch of the boat as they
ejecgtted their cannon balls, were brought back to reload on their
carriages and shot again.

That did not last very long before we heard the sounds of sword
hitting sword and the sounds of small arms fire.

"Yes, I have the advantage," he agreed, continued to laugh. Some of
his crew laughed with him but I did not detect any humor in their
laughter. They simply laughed because the 
"We have been boarded," Tripp whispered. She pressed her body against
mine. She was shaking.

I had never been boarded by pirates before nor had I ever participated
in a pirate raid. I hoped the pirates were more about booty then
pillage.

The sounds of fighting died away. We waited for an all clear. It did
not come. We heard feet on the stairs. (The boat workers called them
ladders.) A knock. We kept silent.

"I know you are in there," a Tigerfoo voice said. "Open the door. We
are not here to hurt you. You are our prisoners now and we are taking
you to the island."

The Tigerfoo was localized in accent. Definitely one of the pirates.
But I did not doubt his words.

Tripp opened the door. We were escorted above decks. There was nowhere
to run. Besides, our pirate's pistol and sword made it clear he was in
charge..

We were loaded onto a launch of sorts rowed by more pirates. Gaunt was
among the prisoners as well as Wiljam who was harranging them with
promises of ransom   
and threats of reprisal. Gaunt was silent. He moved over when we came
into the boat. I managed to sit on the deck. The pirate captain
squeezed in behind me.

"So you are the Dark Child I have heard so much about," he said.

"I remained silent. What could I say? He was not unpleasant to look
at. He looked a little the worse for wear with some nasty scars on his
body.

"We have not been introduced," he continued, "I am Pirate Jawbone.
Perhaps you have heard of me."

Still I remained silent.

"Does she speak Tigerfoo?" Pirate Jawbone asked Master Gaunt.

"I suspect she has nothing to say," Master Gaunt replied. "You have us
all at a bit of a disadvantage."

Pirate Jawbone laughed heartily at this.
So did a few members of his crew but there was no humor in it. I
suspected they laughed because their boss laughed.

We were taken around the island to the other side where there was a
quiet cove. We stepped out of the boat onto a small dock.. From there
we were marched inland to the pirates camp which consisted of a few
rough-looking buildings.

"Here you go," Pirate Jawbone said to us. "A private villa seeing as
you are government officials. I am certain we can work out an
arrangement so you can be on your way. No telling what that Dark Child
can do to us. I have heard she can be really nasty with a knife."

I was glad I was not looking at him. My face would have given me away.
Pirate Jawbone knew about that incident at the inn. What did not he
know about? We had thought we had kept ourselves to ourselves, but
this was not proving to be the case.

I wondered how we were going to get ourselves out of this mess. It was
not like we could send a message and get any governmental official to
insist upon our release.

But in the days that followed, we learned several things.

1. The cargo that our boat was carrying came from the Spanish
   territory. It seemed that Wiljam was smuggling goods across the
   border. There were no tax stamps to be found and much of the cargo
   was on the prohibited list. The pirates were delighted. They
   planned to requisition some of it and sell the rest on the black
   market. They also used their acquisitions in bargaining with Wiljam.
2. The pirates of the island had a grievance against the general. They
   said he was giving them a bad name on the river when they were just
   trying to trade with everyone who came along. Wiljam's entry into
   the smuggling business was cutting into their margins. They had
   taken to kidnapping not because they wanted to but because they had
   been forced to. They were proposing a live and let live policy for
   river traffic. 

The argument became heated. Pirates had their hands on their sword
hilts. Wiljam was blustering, but he clearly was outnumbered and the
pirates had no incentive to keep him alive. They said the garrison
commander at Vickin would thank them for ggetting rid  of him rather
than returning him.

Master Gaunt shifted uneasily whether from the threats of violence or
the lawlessness of it all. He was not a frontiersman. He was from a
civilized culture that disliked violence and was only in a war because
the People of the Rainbow Sky had brought war to them. Their military
drilled, of course, but was more for deterrents than actual warfare.
Planets in far flung star systems often foun it difficult to
participate in a confederacy. Going it alone seemed preferable until
the bad guys showed up. Then strength in numbers sounded like a better
option.

While the dispute heightened in intensity while Wiljam's crew members
drifted over to their commander, Pirate Jawone's second in command
drifted over to us.

"There's an old boat at another dock," he said. "We put your gear on
it. Feel free to wander over there to make sure everything is in
order. No one will miss you until the morning."

We found the trail, difficult to follow in the dark, but it did lead
us to a small boat. Yes indeed our things were there. Gaunt fired up
the engine and guided the little craft into the river. The current
caught us and started moving us down the river on its far shore. Soon
another cove appeared and we steered the boat into it. No one was
there though remnants of fires suggested it was a frequent stopping
point. We unloaded the boat and with the light of dawn began scouting
the area.

A trail led north and we agreed to follow it. We had to leave a lot of
gear behind. We put it back onto the boat with a note requesting that
the Pirates store it for us. We knew they would be on the lookout for
their boat and the sooner we left it the better. No need to be accused
of stealing it.

Now on foot we began to make our way north again this time in foreign
territory. Who knew what trouble would ensue.

* River People  

We were in luck. On the third day, quite foot sore, hungry and very
tired, we came to the place where the western river joined the Big
River. Gaunt and I had been here before when we returned from finding
Ruand. We were even recognized by some of the river people. We
explained what had happened to us.

"You were quite lucky," they said. "Obviously Pirate Jawbone was not
interested in you. He would have come after you if he was. He was
having a parlay with Wiljam and confiscating his goods. It is an old
battle between those two. No telling how it will work out in the end."

But they could not help us directly with our desire to get to Saint
Louis. They did not have any craft that was capable of going upstream.

"If you ride for a day or two," they said, "you should be able to
connect  
with the trail Star Children. They can guide you there.

And so we set out. It was an uneventful though long trip, taking
almost a week, but in time we connected to the Trail Star Children and
they agreed to take us to Saint Louis. Our trip again was long but
uneventful.

* Saint Louis Library

Although long and uncomfortable, our journey to Saint Louis need not
be recounted here except to say that one of our guides was not a Star
Child of the Trail group.. She had been captured from another group
further west and raised as a Trail Star Child. This practice is common
among the Star Children of this continent. When she rode with me she
asked if I was a member of the Musical Mountains group. I asked her to
tell me about them and why she thought I might be from there.

"I have never been to the Musical Mountains," Ariz said. "My
people--my birth people--traded with an intermediate group. As I have
come to live with the Trail People, so this intermediate group had
members that had been captured from the Musical Mountain People. I
know this sounds confusing."

Note to Self: This definitely needs to be cleaned up and it is not a
by-the-way statement. It should be a scene of its own and it is quite
important.

"I follow," I said. 'Your groups are a bit fluid in this regard and
people move back and forth as the result of raids."

"Exactly," Ariz said. "Anyway, a number of dark-haired Star Children
lived with them. Apparently, in the Musical Mountain People, dark hair
and darker skin is normal while our pale coloring is not. That is why
I asked."

"And where are these Musical Mountains?" I asked. "Are they far from
here?"

"I think so," Ariz said. She pointed to the southwest. "They are still
in what you call Spanish territory, but some distance away."

I promised to tell her people of origin she was all right if I ever
met them. I told her I was hoping to visit the Musical Mountains and
meet more people of my tribe. There was no reason to explain I was an
off worlder and that I had no relation to anyone on this planet.

When we arrived in Saint Louis, several important things happened.

1. Master Gaunt established our government bona fides with the Middle
   Territory government. This allowed us to pass through government
   facilities and for Master Gaunt to replenish our funds which were
   running low. It further allowed him to submit reports which would
   eventually be transmitted back to MAgic City.
2. Establish a meeting with the Tigerfoo in Charge to see if we could
   learn anything more about Middle Wizard and his errand. They knew,
   of course, about his death and they were satisfied he committed
   suicide. His behavior had been unusual in the months before he set
   out on his final journey.
3. I went to the library to see what I could uncover about Middle
   Wizard's investigations and if they had any information on the
   history of the continent or I could find a map showing the Musical
   Mountains.

Note to self:I need to show how Ronnie learns about Middle Wizard's
investigations. Oh, I can do that now when Ronnie asks the librarian.
Yay!

I went into the library and spoke to the librarian. I had no idea if I
would be able to access any information. He was surprised by my
government credentials but complied with my requests.

"I do not get much call for old records," he said. "Most people want
the latest information we have. The former Middle Wizard was very
interested in learning everything he could about this continent. I
guess that was because of his trip out west."

Bingo, I thought. I am finally getting somewhere.

"And what did you show him?" I asked. "That would be very interesting
to me."

He complied, bringing me to a dingy corner of the library. I could
tell that no one came here very often. At least, no one dusted here
very often. The librarian apologized for the poor  condition of the
stacks and then left me to poke around on my own. After rummaging
through a number of boxes, I surmised that the flimsy I possessed came
from one of these boxes. I could not read any of them. I knew my links
could not process any kind of translation. And then I came upon a box
with a device in it. My links went crazy. It was a very ancient
communications device. My links wanted to activate it so they could
transmit. I was very dubious. After all, the Followers of the Stars
had not been around for many millennia.

Nevertheless, I took the box to the librarian and asked to check it
out. He looked dubious. They did not check out items from their
ancient collection. I pointed out that I was a government employee
here on government business--classified government business as a
matter of fact. I was prepared to play the patriotism and war effort
card if needed, but the librarian relented and I took the box back to
my room at the hotel.

My links had an entire article on this device and assured me if I
turned it on, an upload link could be established and all their
backups could be transmitted to the Fungusian Network. I decided it
was not worth arguing with the artificial intelligence built into my
links. It would just not power up and that would be that. 

Except it did. I was shocked. There was no apparent power source and
no way it could have stayed charged all this time and yet it was live
and not only could my links upload they could download as well.

The only notice of interest to me, besides the usual security updates,
was that a more efficient connection between this region of space and
the network had been established which should greatly improve turn
around time. The network noted that they had been pinging me for some
time and I had not responded. Dire warnings of security hacks
followed. I smiled and dismissed them. I wondered what the Fungusians
would think when they received my upload from this device. I suspected
they would be very very excited, that is, if Fungusians got excited.

The other item I had managed to check out of the library was a map. I
spread it out on the floor having no suitable table on which to do so.
It was crude having come from some Spanish explorers. Their own names
were on physical features--mountain ranges, valleys and rivers. Yet
studying it, I saw a possible location for the Musical Mountains. This
was largely due to Ariz's name. I saw a region by that name  on the map.  
On this map, the mountain range was called Foam. It was a long way
from Saint Louis and I doubted we would be able to get there. No
waterways connected us. The map indicated large open areas and many of
them labeled desert. I am not so well-versed in planetary climatology,
but I do know deserts are hard to cross when your own means of
transportation is riding on an animal, especially not an animal
suitable for desert crossings.

I was still pondering this when someone scratched at my door. I opened
it, expecting to see either Master Gaunt or Tripp standing there.
Instead I saw a rather strange looking humanoid.

At first I thought it was a Dark Child, but on further inspection I
realized it was some sort of robot.

"Hello," I said in the Star Child language. "Are you a mechanical
device?" I had no word for robot. They were unknown on this world as
far as I knew.

"Yes," it replied.

"And what do you want from me?" I asked.

"I wish to speak with you," it said.

"Do you wish me any harm?" I asked.

My links were interested in this device but had no comment on it so
nothing appeared in its databases. Interesting. The Fungusians would
no doubt want to know about it so I knew my links were paying close
attention.

"Please wait," I said to the robot.

I closed the door. No warnings were posted. Robots typically did not
hurt people unless they were programmed to and they did not lie unless
they were programmed to. I decided to hide my map and the uplink box.
No need for the robot to see either of them. For all I knew it would
be able to transmit via the box as well and since I did not know
anything about it, I did not want to take that chance.

I reopened my door. The robot was still standing there.

"Who sent you?" I asked.

"I am sent from the Musical Mountains facility," it said.

I was floored. If this was a ruse, it was certainly a timely one. I
could not believe that there were either surveillance cameras in my
hotel room or the library or that there were hidden microphones along
the trail we had used to come into Saint Louis.

The robot came in and stood in the middle of the room. It said, "I am
reporting as instructed."

I had the presence of mind not to contradict the robot. I was not sure
who it thought I was, but but its report would be interesting enough.
I made sure my links were recording.

  
