#+TITLE: A Long Morning Walk with Nick
#+DATE: 2016-09-09
#+FILETAGS: :Dog:Nick:

Nick, my Seeing Eye dog, and I took a walk this morning.

Now I know that taking a walk with your dog is not a novel experience for any dog owner. What was significant about this walk was that it took place immediately after my breakfast and before my exercise class at the senior center.

Normally I would have listened to my podcast app while sucking down at least one large cup of coffee. Instead, I skipped my morning coffee and got walking.

Our walk lasted about 40 minutes. We walked a route we just learned from our friend Sandy, but we walked it backwards. Nick trotted right along and got very excited when I chose to walk on the other side of Terrace Avenue. Nick had not walked down this side of the street yet.

I'm not sure how long the route is, maybe over 2 miles.

We have not been able to walk for several days because of our schedule and the rain. As it was not raining and it was fairly cool, it was a wonderful time to walk.
