#+TITLE:  Brilliant!
#+Date: <2013-06-15>
#+FILETAGS: RaspberryPi

I've been using text mode to write these blog entries. Additionally, I
have been using [[http://www.daringfireball.net/projects/markdown/][markdown]] to format
them. As I do not have markdown enabled yet in emacspeak and because I
am unable to install pandoc on the pi, I've been copying them to my
Vinux machine for processing and posting.

I've discovered how to create a web page and convert it to html. This
post is a test case. 

***  Some Confusion

In reading Alex's [[http://emacspeak.sourceforge.net/info/html/tutorial.html][explanation]], I was confused because he talks about creating a web page. This "page" (I've surrounded the word page with quotation marks.) is not something which is published on the web. It is a file a browser can read and interpret. What Alex has you do is write a file that acts as a list of bookmarks to your favorite sites so you can launch it and get around the web quickly and easily. fterI understood this, his explanations made a lot more sense.

*Note:* The extension ".org" refers to org mode not the domain type as in "raspberryvi.org". This also confused me. I thought at first org mode was not installed, but that is because I was hearing "aug" mode as in "augmented" or ""August". It's "org" as in "organized".

***  What I've Learned So Far

Sadly, my menu structure is different from the one described so I'm reading the [[http://orgmode.org/manual/index.html][Org Manual]]. 

One of the exciting discoveries I've made says You can publish this file and there will be navigation as part of the publishing process. I'm currently reading the manual and each section of the book is a separate page with navigation to other sections built in.

I've looked at the html code generated and it is overly fussy. I'll try it with tidy and see what happens. s the code is correct, tidy has no effect. 

I'm publishing the full html that was generated including the preamble and postamble. I am not sure how to disable this. 
