#+TITLE: Caitlin: Great Dog, Loyal Friend and Partner in Ministry: A Tribute
#+DATE: 2025-09-06
#+FILETAGS: :Dog:Faith:Caitlin:


Note: I must have written this some time in July, 2006 before I had a regular blog. but it seems appropriate for me to post this on the 33-year anniversary of her birth.

- The Time -- January 4, 1994 - July 10, 2006
- The Place -- Everywhere I went
- The Situation -- Working together, my [[https://seeing.org][Seeing Eye dog]] and me
- My Spirituality -- God watch over my dog and me.

*** First Meeting

Caitlin was brought to my room at the Seeing Eye on the afternoon of
January 4, 1994. I asked twice how her name was spelled. I would have
spelled it Katelyn. Now Caitlin only seems the right way to spell it.

My instructions were to spend time with her, to play with her, to pet
her and not to discipline her. We did that for a long time. I was
getting tired. Doesn't a dog ever have enough attention? Suddenly,
Caitlin just fell over and didn't move. I touched her. She didn't move.
I picked up one of her paws. She didn't move.

Oh, no! I thought. I've killed her! How am I going to tell them I killed
this $20,000 dog.

I put my hand on her chest. I felt her heart beating. I felt her chest
going up and down. She was sound asleep. All the playing and petting and
attention had worn her out. At sixteen months old, Caitlin was still
very much a puppy and she slept like a kid--out cold.

***#Particulars

- Born September 6, 1992
- Chocolate Labrador Retriever
- Daughter of Walsh and Raisin
- Raised by a fourteen-year-old boy with a mother, brother, father and dog already in the household.
- Died July 10, 2006

*** Let's Go!
From our first meeting, Caitlin and I had a dynamic
relationship. In what follows, I don't comment on her guide work in
detail. She was excellent

- in her work
- in her visual memory
- in her learning new routes and new routines

Caitlin's greatness as a guide dog makes it possible to remember her
with gratitude and laughter.

​*** Still A Dog At Heart

Caitlin was a handful from day one. Even at the end, she was incredibly
strong and opinionated. I never quite got the knack of a leash
correction so I depended far more on persuasion and asserting my
position as alpha female.

Caitlin viewed my children as litter mates. I was particularly aware of
this the day my daughter came home from school and fixed herself a plate
of nachos. She ate them and left her plate and the just-opened cheese on
the table. Seeing a yummy opportunity in the unguarded and within reach
cheese, Caitlin ate the whole pound. If I had left the cheese, it would
have still been there at dinnertime. This, I learned, did not apply to
anything left on a surface level with her nose. Food on coffee tables
were fair gain.

*** ​Surmises

Caitlin could not tell me about her early life. I only knew the few
facts I list above in the Particulars. However, I was able to deduce
some more information:

1. The boys were active. Caitlin wanted to chase bicycles, join the soccer game, play rambunctiously. she seemed familiar with the playing fields around the school.
2. The family watched football. She would stop near a television with a game on. The name "Joe Montana" seemed to get a reaction.
3. They were junk food junkies. That dog could hear a pretzel bag open anywhere in the house. It was the only people food I ever shared with her and that only near the end. In a shopping mall food court, Caitlin would walk past a discarded piece of hamburger to get to the French fries.
4. Along with her command vocabulary, Caitlin knew the phrase Night night.

I brought her home, spread out a blanket on my side of the bed and
attached her to her bed chain. She just stood there, apparently not
knowing what to do. How do you tell a dog this is your home?

- This is where you live now.
- This is your space.
- It's time for bed.

I said, "Night night." and she laid down.

Even now, it makes me sad. I thought of being a fourteen-year-old boy,
trying to be grown-up and yet still very much a boy and saying to your
Seeing Eye puppy, "Night night."

Shortly before her death, I had to go out-of-town. I couldn't take
Caitlin with me. I left her with friends. I called it going to camp
because she had kids and cats to play with and could spend time on the
deck watching the traffic go by--all activities she enjoyed. The night
before she was to come home, her "counselor" called to say Caitlin seems
quite lonely. Would I talk to her on the phone?

What do you say to a dog over the phone? I said Hi and You're a good
girl and finally, Night night. That worked. She settled down for the
evening.

​*** Church Stories

A great deal of our working time was spent in church. Caitlin really
didn't care for church. Her favorite part was recessing. She did that
with great enthusiasm and speed which often threatened to disrupt the
decorum of worship. We were always among the last to recess.
Torchbearers, acolites and crucifer as well as the choir needed to
precede us.

There are many worship stories to tell. Let me relate three of them.
They all happened at First Lutheran Church, Jamestown, new York. They
all happened in the nave, a huge room that seats a thousand people, has
a choir loft, a balcony and a sixty-five-foot ceiling.

**** What Did You Say?

On our first Sunday, all went smoothly until Communion. My
responsibility was to stand in front of the chancel steps at the head of
the center aisle to administer the common cup to whoever wanted it.
Typically, the assisting ministers went up these two steps, crossed the
floor at this level and mounted three more wide steps to the alter.

No way, I told the pastor. I can't carry a full chalice of wine in one
hand and manage Caitlin in the other. It won't be good liturgy.

I suggested I position myself at my station and someone could then bring
me the cup.

I settled Caitlin down along the step so I could stand on her leash and
in front of her body. I thought both she and the communicants would be
less likely to fraternize this way.

The organist stopped playing. While the pastor was giving Communion to
the other assisting ministers at the alter, the choir came down the
stairs of the choir loft directly across from Caitlin. In the quietness
that comes from reverent waiting, Caitlin stood up and barked.

Chagrinned, I quickly turned to resettle her.

The woman at the head of the choir line took a lot of ribbing. The
general consensus was that the choir descending en mass upon Caitlin in
their red robes had frightened her. This makes sense to me because
people in other than regular clothing made her uneasy.

**** I've Heard It All Before

To preach in the nave, I needed to mount nine steps from the chancel. To
be seen over the pulpit, I stood on a large wooden box. There was enough
room for the two of us. Caitlin loved the place in the very front. It
came to a point and was a perfect denfor a dog. Unfortunately, there
wasn't enough room for both my feet and her body. Moving her was often
difficult. She knew prime real estate when she saw it. I was very
self-conscious about the time it took to reposition her. The entire
congregation was standing, waiting for me to announce the Gospel so they
could respond and then sit down.

One day she was particularly obstinate. I thought, Oh well, she knows
the drill. She'll settle down, and I left her to it. Wrong!

As I began speaking, I heard her moving around. I learned later she
stuck her nose through the railing and was sniffing the pastor's hair.
He dutifully ignored her. As it turned out, this was a mistake.

I continued to speak. Then I heard thump, thump, thump! Caitlin had
discovered she was loose and was making her way down the pulpit steps.
Should I stop and catch her? No, I thought. Both she and the pastor have
already heard my sermon at the earlier service. They'll have to figure
something out between them. And they did.

**** Where Are You Taking Me, Dog?

On another Sunday I was giving the children's sermon. My text was Luke
10:1-11 in which Jesus instructs his disciples to be missionaries before
sending them out. I decided we would pretend to be travellers, walking
around the nave, stopping at points to go over Jesus' instructions. I
asked our organist to play Siyahamba We Are Marching as our walking
music as we went from point to point around the nave.

I imagined our trip:

- down the side aisle to the back
- to the center aisle
- onto the other side aisle and
- back up front

Easy, right? Wrong.

All went well until we made for the side aisle to walk back to the front
of the nave. I told Caitlin to turn left and she did. The aisle seemed
quite narrow. We came to a wall and she stopped. The organist kept
playing.

"Where are we?" I whispered to one of the kids.

"Turn left," he said.

I did. We found the wide side aisle and made our way forward, concluding
our journey.

What I didn't know, and what, apparently, Caitlin did, is that the nave
possesses two additional side aisles against the nave's outside walls.
We had stopped where the choir loft juts out. A horizontal aisle leads
to the "main" side aisle at this point.

Most of the congregation didn't know we were lost.

The organist couldn't see us when we went down the skinny aisle. He was
in the choir loft directly above us at the piano. He had the presence of
mind to keep playing until we reappeared.

Nothing like getting lost in your own church while leading worship!

*** One Among Equals

In Caitlin's understanding of human language, dog always meant Caitlin.
She considered herself a person. As an individual, she had her own
opinions, developed a circle of human friends with whom she had
relationships apart from me.

For several years now I have been attending an early morning weekday
healing service. We kneel at the alter rail. Caitlin settled herself
down next to someone. As the priest anoints and prays for each one
individually, members of the healing team lay hands on that person, too,
and pray. Caitlin's solution to being skipped was to get the person next
to her to pet her.

Recognizing petting when she saw it, sharing the peace was very
important to her at this service.

​Final Journey

With some expansion here and some editing there, I use the email I sent
out to family and friends Monday, July 10, 2006.

Mother Susan and I took Caitlin to the vet for her final journey at noon
today. Caitlin has been failing. This week she stopped eating. Nothing
would stay down, even biscuits.

Excursus: Biscuits. Caitlin was very fond of dog biscuits. In the last
few months of life, she preferred them to her regular food. The vet
suggested I pour low sodium chicken broth over her food. That worked for
a while, then even that did not interest her.

Saturday evening I went to the 5 o'clock service at St. Luke's. When I
came home, I found Caitlin in bed already. This made me certain we were
very near the end. It wasn't dark. It wasn't even six o'clock yet.

Sunday she moved onto the kitchen floor and seemed pretty much out of
it. She drank water once. I checked on her regularly throughout the day.

I decided to camp out on the studio floor next to the kitchen overnight.
I didn't want her following me into the bedroom. I wasn't sure if she
could. I didn't want her to be alone at the end or think I had abandoned
her. I wasn't sure if I would wake up often enough to check on her.

During the night, she lost bladder control and seemed unable to stand
though I found she could get up to drink more water. I changed towels
underneath her to keep her as dry as possible and ran the washer and
dryer throughout the night.

After evening worship on Saturday, Susan had said to call on her for
whatever I needed so i did. The vet could take us at noon if I wanted to
be present when she received her shot.

once the time had been fixed I did normal tasks during the morning. I
also took a shower. When I was getting dressed in the bedroom I heard
something. It was Caitlin coming to see what I was up to. I had been
gone too long. Maybe something was wrong. In Caitlin's mind, I was
always likely to need supervision, or at least, that is what I always
told myself when I found her waiting outside the bathroom door or
watching from her blanket in the bedroom.

Susan and the S t. Luke sexton came to carry her to the car. Caitlin
didn't care for this. She tried to get down while we were in the
elevator.

She seemed to enjoy being in the van. I petted her. I told her over and
over again what a good dog she was.

Excursus: Vans. At the Seeing Eye the dogs are brought to and from the
kennel for their training in vans. When in class, both human and dog are
transported to and from their training routes in vans. Caitlin loved
traveling in a van. One day when my daughter had taken her out for me,
there was an open van in the parking lot from the local cable company.
Caitlin jumped in, ready to ride. I'm glad a van played a part in her
final journey.

When we arrived at the vet's, Caitlin turned herself around to be ready
to get out of the door. She sat up and looked out the window. She walked
into the room which has an entrance from the parking lott so you don't
have to go through the waiting room. I had not thought it necessary to
bring her leash. I expected we would carry her.

Like all good funeral folk, the clinic personnel have it down.

- Write the check first.
- Tell them what you want to do with the body first.

After the injection, it takes about two minutes for unconsciousness.
Caitlin stuck her nose in the technician's business. What was she doing?
Caitlin was always good about shots. In fact, the vet's never bothered
her. The groomer's on the other hand ... they got you wet and touched
your feet. Yuck!

Gently, I pulled her nose away. Susan and I prayed. God watch over my
dog and me. I began speaking to her about this final journey, reminding
her of all the places we had gone together.

"She's gone," the tech interrupted.

Caitlin's head dropped. She was still warm. It was as if she was asleep.
We got her settled on the table so I could step away.

*** ​Final Arrangements

I decided to have Caitlin cremated to keep her near me. I've always
thought people who did this were carrying things a bit too far, however,
I decided it is what Caitlin would want --to be with me. I always
thought she should have a proper interment.

The ASPCA which handles animal cremation in this area returned Caitlin's
ashes in a sealed jewelry box. I bought a dog tag in the shape of a dog
head with angel wings and tied it onto the latch with a leather thong I
received at Lenten worship to bind unto myself today the strong name of
the Trinity(Lorica)

I set the box on the bookshelf Chip made for me which stands near my
desk where I am writing this now. Caitlin often laid between me and the
bookshelf. Several angel figurines surround the box.

*** ​Some Final Thoughts

There are many more stories to tell about Caitlin. These are some of my
favorites and seem to fit with my theme of faith journey.

Losing her has been like losing a part of myself. All of my daily living
seems to have been wrapped around her. I feel as if I am unraveling in
her absence.

Caitlin was never a comfort.

- If I was anxious, she was anxious.
- When I sneezed, she came to be reassured I was all right.
- When I left her, she waited, sometimes for hours, at the door for myreturn.
- If I went into a room, she followed.
- When I was working somewhere, she was present, stretching herself outon the floor so I had to climb over her in order to get somewhereelse.

Caitlin told jokes. They were dog jokes, of course, quite childish.
Blocking my path was one of them.

Another way she understood humor was harness on, harness off. I taught
this to nursery school children.

When Caitlin was in harness, she was working. She laid on the floor very
still. When her harness was off, she was at play and could be petted.
The children processed it as a game.

"Put the harness on!" they cried. I would. Caitlin became like a statue.

"Take it off!" With her harness off, she rolled onto her back and put
her feet in the air. The children swarmed all over her.

The more we played, the more correct Caitlin became with her harness on
and the wilder she became when the harness was taken off. She and the
children loved the game.!

- Caitlin taught me about interdependence and loyalty.
- She taught me how to be present to someone else without speaking.
- She taught me how much she meant to other people. I received cards,phone calls and memorials to mark her passing and to honor her lifeamong us.
- She was one of God's creatures who did God's will unquestioningly.
