#+TITLE:    Everyone's A Critic
#+DATE:     2005-05-28
#+FILETAGS: Creativity
You might think that, being blind, I have no interest in paintings or other forms of visual art. You would be wrong about that. I'm fascinated
by art and what other people bring to the pictures. Last year people at
the "Stations of the Windows" Friday Lenten worship services at[[https://stlukesjamestown.org/][St. Luke's Jamestown]]described the stained glass windows.
They were so enthusiastic it grew dark before we could finish the window
descriptions and the service.

Today's[[https://www.nytimes.com/2005/05/28/arts/design/with-irreverence-and-an-ipod-recreating-the-museum-tour.html][New York Times]] described a 
project at Marymount Manhattan College  called [[https://mod.blogs.com/art_mobs/][Art Mobs.]] Even if you're not at the Museum of
Modern Art in New York City, you can download the podcasts and look at
the paintings online. I downloaded the podcast on Pablo Picasso's Les
Demoiselles d'Avignon, a Discussion by Cheryl Stoever & Professor Jason
Rosenfeld.

It's rough. It's raw. It's fascinating. It's listening in on a college
professor going one on one with his student, asking her questions,
giving additional information about the painting, giving a perspective
on what the picture is about. It's just the sort of thing I want people
to tell me about art.

/Note/: Now, twenty years later, the audio files have been remixed. The Times article is behind a pay wall and I had to update the church web site address!
