#+title: The Spirituality of Risk Taking
#+DATE:< 2004-01-01>
#+FILETAGS: :Page:Faith:
** The Spirituality of Risk Taking 
I'm a science fiction fan. I like a good space opera with spaceships,
aliens and lots of action. I also like science fiction that explores
what if's. Unlike alternate histories, I don't have to know the real
history before I can enjoy the scenario being laid out before me.

More specifically, I'm a Trekkie. (Yeah, yeah, I know, we're called
trekkers, but, we were called Trekkies first.

The Next Generation episode of Star Trek that changed my life (really,
it did!) is [[https://en.wikipedia.org/wiki/Tapestry_(Star_Trek:_The_Next_Generation)][ Tapestry]].

After having his artificial heart short-circuited, Captain Picard has an
opportunity to change the trajectory of his life. As a young officer,
Jean-Luc made a choice that now has fatal consequences for him. When
he's given a chance to undo his behavior, his future life changes, too.
Unfortunately, although he's alive, he's miserable. He has, in this new
life, always played it safe. Picard learns that one of the qualities
that makes his life satisfying to him and, coincidentally, makes him a
good starship captain is taking risks.

I hadn't seen the series when it aired. I watched it as late night
reruns. As I laid in bed thinking about this particular episode, I
reflected on my own life. It's a scary thing to see an Enterprise
captain

reduced to a mature lieutenant junior grade

running errands for his superior officers

humiliated by the ship's senior staff who once looked up to him

I thought about my own life. I realized I benefited more from the
chances I had taken than the times I had played it safe. For example, I
had left a good paying job at IBM when I was offered a buy-out package.
At the time, people close to me thought my action was foolhardy. Later,
when

the site was closed

the company's stock dropped dramatically in price

those still employed by the company had to interview for jobs as if they
were candidates off the street,

My decision looked like a wise one.

I learned to take risks with my life and work.

Sure. There are things that really scare me, risks I won't take:

skydiving

Ferris wheels now that I'm too big to have my dad riding between my
sister and me

Roller coasters I did go with my daughter on  [[https://en.wikipedia.org/wiki/Big_Thunder_Mountain_Railroad][Big Thunder Mountain Railroad]]  in the
Magic Kingdom. She laughed at my fear. What made the ride almost
bearable was sitting in front of some park employees. One was describing
to the other where you could take people off the ride if you had to.)

In Babylon Five when Captain Sheridan is dying on zhadum, [[https://en.wikipedia.org/wiki/List_of_Babylon_5_characters][Lorien]] asks
him: [[https://www.chronology.org/noframes/b-five/monologues.html][Who are you? Why are you here?]] Sheridan must answer these basic questions about his existence to
Lorine's satisfaction in order to survive.

Socrates is purported to have said, [[https://thedailyidea.org/socrates-examined-life/]["The unexamined life is not worth living."]]  Haraman quoted this to me a
long time ago. Because Haraman told me and because I have had many years
to test this saying, I have come to believe it is true.

I learned to reflect on my own life

I have many favorite biblical passages. Those of us who find solace and
encouragement and challenge in the Bible do. One of them goes like this:



For copyright reasons, I'll read this quotation from The Holy Bible,
American Standard Version.

He hath showed thee, O man, what is good; and what doth Jehovah require
of thee, but to do justly, and to love kindness, and to walk humbly with
thy God?

(From Micah 6:8)

Humble-walking may suggest to you modesty or submissiveness. In
Charlotte's Web ``humble'' was the last adjective Charlotte the spider
used to describe Wilbur the pig. In this context, it meant low to the
ground.

In my experience, to walk humbly with my God means

An Openness to another point of view

a willingness to change my mind

a deep desire to align my desires with God's desires

Sometimes Christians call this doing God's will.

I learned to desire what God desires.

So here's the part where I bring my learnings (my spellchecker won't
like this word) together into a spirituality of risk taking. The parts
are:

risk taking

questions about the nature of my existence

a need to examine these questions to draw some conclusions about the
meaning of my life

A Scriptural observation about how life is to be lived.

a spiritual response to these observations

It really boils down to Lorine's questions only Lorine isn't asking
them. I am. God is.

Who are you?

Why are you here?

I believe I ask these questions about myself and God asks me these
questions about myself in prayer.

I am calling all these disparate pieces a spirituality of risk taking.
It's still quite rough. I hope to

risk more

reflect more

relate more

write more

And share more with you in the days ahead.
