The [[https://preview.nanowrimo.org/][Nanowrimo]] Prep email arrived in my inbox last week or maybe
earlier. I opened it up to find I have access to an entire workbook
and a weekly schedule to get ready. I've been going through the
document. Sadly many of the links were eight broken or not even inside
the pdf. Nevertheless, there's enough there to get started.

I haven't been able to write the story of Ronnie Camberwell arriving
in the Magic Lands and how she got stuck there. Perhaps it is one of
those stories that can eluded to but never written. I remember
that Rumpole had such a story.. Eventually John Mortimer wrote it and
it was so disappointing. It worked so much better when Rumpole
referenced it but kept the details foggy.

Working under this idea, I have decided to write a different story
while Ronnie is confined. 
 
Here's my outline so far.

** Initial Idea
  :PROPERTIES:
  :CUSTOM_ID: initial-idea
  :END:

- The novel is called Mulberry Bend, A Ronnie Camberwell Novel

- It takes place after The Three Laws of Magic

- It takes place in the capital city of the Magic Lands.

- To the uninitiated, the city appears to be a medieval city. To Ronnie,
  it is a city with very extremes of well-being.

- In a very poor area called Five Points, there is a winding street
  called Mulberry Bend.

- The mystery centers in this area and on this street.

** I read a prompt recently about a lost girl. 

The lost girl ends up in this section of the city. (This is based on
the 19th century area of New York City.) Tripp and Ronnie set out to find her. Explores the relationship between Tripp and Ronnie and is Ronnie's first trip outside of the wizard compound. Ronnie is restricted to the city. Tripp is still sexually attracted to Ronnie. Ronnie is conflicted, wanting Tripp but also tied to the absent Captain Star Runner.

** Some ideas about the lost girl:

  - a Tigerfu
  - Not from the capital city
  - Grand Mistress Luna is very anxious that the girl be found so the
    wizards reputation does not suffer but she is not invested in the
    girl at all. Ronnie is appalled. Tripp is philosophical.
  - The leader of the field trip is anxious that her reputation will
    suffer if the lost girl is not found, but she is not really
    invested in the girl either. Ronnie presses her to
    understand. The girl is mute and her guardian merely wants the
    girl off her hands. It seems everyone has this attitude. With
    four hands, Ronnie can't figure out why the girl cannot sign and
    make herself understood.
  - Tripp explains the Tigerfu in this part of the Confederacy is not
    particularly sympathetic to disabilities. It's a very frontier
    mentality and everyone has to pull their own weight.
  - Ronnie has to rethink her idea about the Tigerfu and their
    openness. Why doesn't this girl get any help. Can her disability
    be mitigated? The Tigerfu are very advanced with surgery and
    psychology. Can the girl speak and chooses not to because of
    trauma or is she physically unable to speak?
  - Ronnie checks the library catalog. Muteness is covered in the
    catalog. From the entry, Ronnie believes the ancient wizards knew
    something about it but she has not delved deeply enough into
    reading the library volumes on these subjects to be fluent enough
    to read the texts easily.

** The Rest of the Story

So I have the opening of the story but not what Tripp and Ronnie find
in Five Points. I don't know what becomes of the lost girl. Stay tuned!

** Where is Ronnie in Her Life When All is Said and Done

I don't know how Ronnie grows in this story and how her relationship
with the Tribunal of Wizards is changed. I've had a sense for some
time that Ronnie will eventually become the Grand Mistress and will
choose to stay, providing leadership for this collections of worlds
within the Tigerfu Confederacy. Her travel ban will be lifted so that
future adventures may occur elsewhere. But that is in the future and will not be realized in this novel.
